### ISSUE TITLE
Quaternion constructor order doesn't depend on GLM_FORCE_QUAT_DATA_WXYZ

### ISSUE THREAD

**Issue by Yoshimaster96** [g-truc/glm#1005]
What it says on the tin.

Currently it looks like this (see glm/detail/type_quat.hpp):
```
		// -- Explicit basic constructors --

		GLM_FUNC_DECL GLM_CONSTEXPR qua(T s, vec<3, T, Q> const& v);
		GLM_FUNC_DECL GLM_CONSTEXPR qua(T w, T x, T y, T z);
```

Personally, I think it'd be more natural to make this depend on GLM_FORCE_QUAT_DATA_WXYZ, so like this:
```
		// -- Explicit basic constructors --

#		ifdef GLM_FORCE_QUAT_DATA_WXYZ
			GLM_FUNC_DECL GLM_CONSTEXPR qua(T s, vec<3, T, Q> const& v);
			GLM_FUNC_DECL GLM_CONSTEXPR qua(T w, T x, T y, T z);
#		else
			GLM_FUNC_DECL GLM_CONSTEXPR qua(vec<3, T, Q> const& v, T s);
			GLM_FUNC_DECL GLM_CONSTEXPR qua(T x, T y, T z, T w);
#		endif
```

Of course, glm/detail/type_quat.inl will have to be modified as well (among others?), but I feel that this would be beneficial to many users.

**Comment by christophe-lunarg** [comment]
This was reverted because it broke backward compatibility
