### ISSUE TITLE
glm::unProject with perspective projection matrix fails

### ISSUE THREAD

**Issue by alzhuravlev** [g-truc/glm#119]
file: glm/gtc/matrix_transform.inl
method: glm::unProject

Actual:
                ...
		tmp = tmp * T(2) - T(1);
                ...

Expected:
                ...
		tmp.x = tmp.x * T(2) - T(1);
		tmp.y = tmp.y * T(2) - T(1);
                ...

Otherwise when we unproject value in perspective projection depth value (tmp.z) will be corrupted by tmp * T(2) - T(1);

**Comment by JesseTG** [comment]
Has this been fixed already?  0.9.6 was a while ago.

**Comment by Groovounet** [comment]
This wasn't fixed, I applied the proposed fix but I probably need to double check the math...

**Comment by JesseTG** [comment]
Ah, ok.  Could've sworn I'd seen something like this in the code base somewhere before...

**Comment by Groovounet** [comment]
This is fixed in GLM 0.9.8.

Thanks,
Christophe
