### ISSUE TITLE
Swizzle support for CUDA

### ISSUE THREAD

**Issue by theHamsta** [g-truc/glm#1192]
Thank you for this awesome library! Especially that I can use it both on CPU and also for CUDA.

A minor inconvenience is that the swizzle operations currently raise a compiler error since the member function used are not marked with `__device__`. A solution to this could be to mark them with `GLM_CUDA_FUNC_DEF` https://github.com/g-truc/glm/compare/master...theHamsta:glm:enable-cuda-swizzle . I'm however not familiar with the inclusion order of those internal header to know which GLM macros we can assume as defined. Could you help me with how this should be done?

An alternative approach would be to mark the swizzle functions with the `constexpr` macro, but this would require an experimental compiler switch to use the functions in device code.

**Comment by theHamsta** [comment]
Probably `GLM_FUNC_QUALIFIER` would be enough.

**Comment by gottfriedleibniz** [comment]
The other configuration dependent [swizzle](https://github.com/g-truc/glm/blob/master/glm/detail/_swizzle.hpp) implementation may also be referenced. It is correctly qualified and allows swizzling in device code. 

Your proposed change(s) should be enough.

**Comment by tomix1024** [comment]
#1110 and #1173 should do the trick.

**Comment by gottfriedleibniz** [comment]
The issue is related to `GLM_FORCE_SWIZZLE` interacting with `GLM_SWIZZLE_FUNCTION` and generating "undefined in device code" errors.
