### ISSUE TITLE
Make HIP compatible

### ISSUE THREAD

**Issue by niansa** [g-truc/glm#1209]
Currently, using glm in HIP is quite hacky:

```
#include <hip/hip_runtime.h>
#include <glm/detail/setup.hpp>
#undef GLM_CUDA_FUNC_DEF
#undef GLM_CUDA_FUNC_DECL
#define GLM_CUDA_FUNC_DEF __device__ __host__
#define GLM_CUDA_FUNC_DECL __device__ __host__
#include <glm/glm.hpp>
```

It'd be nice if there'd be a cleaner (or even auto detected) way to do this!

**Comment by christophe-lunarg** [comment]
Please make a PR if you want this to happen.

Thanks!

**Comment by niansa** [comment]
Mh, my bad. I should've checked the master branch before opening this issue.
It's already been implemented and working as intended!

**Comment by niansa** [comment]
Happy new years eve either way! :-)
