### ISSUE TITLE
No unused function result warning

### ISSUE THREAD

**Issue by iyadahmed** [g-truc/glm#1217]
I'm using glm::rotate, and if I forget to use the function result somewhere in my code, the error is silent, the results will be wrong,

marking glm::rotate as [[nodiscard]] fixes it, but that needs to be done for all similar functions

**Comment by christophe-lunarg** [comment]
I like this feature request, I'll try to implement it someday soon (TM)!

**Comment by iyadahmed** [comment]
That was quick ☺️☺️🤍

**Comment by christophe-lunarg** [comment]
> That was quick, thanks a ton for awesome work ☺️☺️🤍

It's probably not exaustive but future contributions would be welcome!
