### ISSUE TITLE
epsilonEqual and epsilonNotEqual

### ISSUE THREAD

**Issue by gottfriedleibniz** [g-truc/glm#1220]
The [implementations](https://github.com/g-truc/glm/blob/b06b775c1c80af51a1183c0e167f9de3b2351a79/glm/gtc/epsilon.inl#L10-L29) to epsilonEqual and epsilonNotEqual are fully specialized and no [generic](https://github.com/g-truc/glm/blob/b06b775c1c80af51a1183c0e167f9de3b2351a79/glm/gtc/epsilon.hpp#L40-L41) implementation exists. Can this be simplified or made more generic (e.g., supporting long double and other types)?

Secondly, should the definition to epsilonEqual be: `|x - y| <= epsilon`, not `... < epsilon` (and opposite for epsilonNotEqual)? Otherwise `glm::epsilonEqual(1.f, 1.f, 0.f)` returns false even though the values are identical.

**Comment by christophe-lunarg** [comment]
Correct me if I am missing something but the vector and scalar relational extension implements that in the generic approach you are requesting :
https://github.com/g-truc/glm/blob/master/glm/ext/scalar_relational.inl
https://github.com/g-truc/glm/blob/master/glm/ext/vector_relational.inl

So really the implementation called "epsilonEqual" and "epsilonNotEqual" are kind of deprecated and I'll rather not change these.

Reopen if I missed something!

**Comment by gottfriedleibniz** [comment]
> are kind of deprecated and I'll rather not change these.

Is this documented anywhere?
