### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by janisozaur** [g-truc/glm#1226]
Last release, https://github.com/g-truc/glm/releases/tag/0.9.9.8 will soon be 4 years old. GitHub says there were 363 commits since. Can you make another release?

**Comment by minerscale** [comment]
I second this, the cmake throws warnings about the cmake_policy being too old for the latest version! At the same time I wouldn't want to depend on master. (maybe that's unreasonable, though).

**Comment by christophe-lunarg** [comment]
This issue is being release by https://github.com/g-truc/glm/pull/1180
