### ISSUE TITLE
Build error on Android

### ISSUE THREAD

**Issue by xiaozhuai** [g-truc/glm#1231]
See also https://github.com/microsoft/vcpkg/pull/36358

Here is the log
[install-arm64-android-dbg-out.log](https://github.com/g-truc/glm/files/14052575/install-arm64-android-dbg-out.log)

It seems caused by these lines
https://github.com/g-truc/glm/blob/33b0eb9fa336ffd8551024b1d2690e418014553b/glm/detail/setup.hpp#L299-L311

**Comment by gottfriedleibniz** [comment]
In the install logs you are compiling with `-Weverything`. Is this intentional?

**Comment by xiaozhuai** [comment]
> In the install logs you are compiling with -Weverything. Is this intentional?

No, I just specify following options.
```
-DGLM_BUILD_LIBRARY=ON
-DGLM_BUILD_TESTS=OFF
-DGLM_BUILD_INSTALL=ON
```

Should I pass `GLM_ENABLE_CXX_xxxxx` ?

**Comment by christophe-lunarg** [comment]
`-Weverything` includes `-Wc++98-compat`. If you don't want to get these warnings, you can build with `-Weverything` and  `-Wnoc++98-compat`.

No need to pass `GLM_ENABLE_CXX_xxxxx`.
