### ISSUE TITLE
Fails to compile for emscripten since 27/Jan/2024

### ISSUE THREAD

**Issue by WillisMedwell** [g-truc/glm#1246]
Since the latest push to Vcpkg on the 27/Jan/2024, glm is failing to compile. This is due to the added warnings "-Werror -Weverything" I think.
 
The history of vcpkg changes for glm can be found [here.](https://vcpkg.link/ports/glm/versions)
There's a warning being set off from a union array access in "\glm\detail\func_packing.inl"

More info about the issue has been logged [here.](https://github.com/microsoft/vcpkg/issues/36652)

For anyone else facing this issue, just switch to an older commit of vcpkg in the meantime. (The one below is the 20/Jan/2024)
```cmd
C:\apps\vcpkg\vcpkg>git checkout a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6
```

**Comment by christophe-lunarg** [comment]
> Since the latest push to Vcpkg on the 27/Jan/2024, glm is failing to compile. This is due to the added warnings "-Werror -Weverything" I think.
> 
> The history of vcpkg changes for glm can be found [here.](https://vcpkg.link/ports/glm/versions) There's a warning being set off from a union array access in "\glm\detail\func_packing.inl"
> 
> More info about the issue has been logged [here.](https://github.com/microsoft/vcpkg/issues/36652)
> 
> For anyone else facing this issue, just switch to an older commit of vcpkg in the meantime. (The one below is the 20/Jan/2024)
> 
> ```batchfile
> C:\apps\vcpkg\vcpkg>git checkout a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6
> ```

Correct me if I am wrong, but I believe this is resolved on master branch and I'll release a 1.0.1 revision soon.
GLM only uses "-Werror -Weverything" for testing now.
