### ISSUE TITLE
Why is there breaking changes to build (#error) with zero changelogs or descriptive commits? @christophe-lunarg

### ISSUE THREAD

**Issue by kikaxa** [g-truc/glm#1247]
Why is there breaking changes to build (#error) with zero changelogs or descriptive commits? @christophe-lunarg

_Originally posted by @kikaxa in https://github.com/g-truc/glm/issues/1213#issuecomment-1929053304_

**Comment by christophe-lunarg** [comment]
I iterated for a long time to figure out all the warnings that I tried to resolve and the commits were squash in the end.

There are jobs opportunities for you at schools, in the police and prisons.

**Comment by kikaxa** [comment]
> I iterated for a long time to figure out all the warnings that I tried to resolve and the commits were squash in the end.
> 
> There are jobs opportunities for you at schools, in the police and prisons.

If you are working from one does not mean everyone else does the same or follow this level of standards. 
Any comments on actual issue?
