### ISSUE TITLE
Add matrix adjoint function

### ISSUE THREAD

**Issue by dustin-biser** [g-truc/glm#151]
Looking through the matrix functions, I didn't see any functions that returns the adjoint of a matrix.  Although it looks like the inverse functions are computing the adjoint as preliminary step.

The adjoint of a matrix is useful for things like computing a matrix for transforming lighting normals.  "Real-Time Rendering, 3rd edition" pg.63, suggests to use the transpose of the adjoint of the model-view matrix for correctly transforming lighting normals. As glm currently stands, only the inverse method is available for this, which returns the input matrix's adjoint divided by the input matrix's determinant.  

If an adjoint function was available it could be used instead of the inverse function to more efficiently compute the normal matrix by removing the unncessary division by the matrix's determinant.

**Comment by naruse** [comment]
any update on this, I just stumbled on this as well and hoped glm had this implemented.

**Comment by Groovounet** [comment]
Another old thing I didn't really investigate even if it's pretty trivial to implement...
https://en.wikipedia.org/wiki/Adjugate_matrix

**Comment by Groovounet** [comment]
This feature was added to dev branch and should reach master branch for GLM 0.9.9.3 release.

Better now than never XD

**Comment by gszauer** [comment]
@Groovounet , I think this implementation of adjugate is actually transposed.

If i'm not mistaken, dividng the adjugate by the determinant of the matrix is supposed to equal the inverse of the matrix. [inv(A) == (1 / det(A)) * Adj(A)](https://youtu.be/nNOz6Ez8Fn4?t=9)

```
glm::mat4 mat = glm::rotate(glm::radians(90.0f), glm::vec3(1, 0, 0));
glm::mat4 inv = glm::inverse(mat);
glm::mat4 adj = glm::adjugate(mat);
float det = glm::determinant(mat);
glm::mat4 test = adj * (1.0f / det);

if (inv != test) {
	std::cout << "(1.0f / determinant) * adjugate != inverse\n";

	adj = glm::transpose(adj);
	test = adj * (1.0f / det);
	if (inv == test) {
		std::cout << "adjugate was transposed\n";
	}
}
else {
	std::cout << "(1.0f / determinant) * adjugate == inverse\n";
}
```
