### ISSUE TITLE
Strict Aliasing Problem

### ISSUE THREAD

**Issue by BryceMehring** [g-truc/glm#152]
Using the -O2 flag for g++ 4.8.1 with glm, I get aliasing warnings everywhere:

`warning: dereferencing type-punned pointer will break strict-aliasing rules`

Edit: I'm also using the -Wall flag

**Comment by spartan-117** [comment]
I just downloaded the version 0.9.7.4 and there is an issue very similar
http://paste.ubuntu.com/15767015/

Regards
Quentin
