### ISSUE TITLE
Using constexpr for constant functions.

### ISSUE THREAD

**Issue by suikki** [g-truc/glm#198]
It would be nice if glm would use the ```constexpr``` keyword more.

For example constats:

```c++
	template <typename genType>
	GLM_FUNC_DECL genType pi();
```

Would instead be:

```c++
	template <typename genType>
	GLM_FUNC_DECL GLM_CONSTEXPR genType pi();
```

Also some functions like ```degrees()``` and ```radians()``` should use it too.

It would allow using glm constants and many functions like degrees to radians conversion in users own constexpr functions.

It would make sense to add ```constexpr``` to many more places too, like some vector and matrix constructors and math operations. It would make possible to move some matrix/vector math to compile time.

**Comment by JesseTG** [comment]
To really take advantage of this, C++14 has to be fully implemented in all the major compilers; C++11 heavily restricts what `constexpr` functions can do, but C++14 doesn't.

**Comment by Groovounet** [comment]
This change has been made in master branch for GLM 0.9.7.1 release.
constexpr coverage could still be improved but that will be for later.

Thanks for contributing,
Christophe
