### ISSUE TITLE
test-gtc_packing fails on i686

### ISSUE THREAD

**Issue by muep** [g-truc/glm#212]
Seems to happen with all 0.9.5\* versions.

Steps to reproduce on GCC 4.8 on GNU/Linux, starting with PWD at the glm repository root

mkdir build
cd build
g++ -m32 -O2 -Wall -I .. ../test/gtc/gtc_packing.cpp
./a.out ; echo $?

The resulting test program exits with value 6, failing the test set.

So far, I have only had this happen on i686. Also it does not happen with -O1.

**Comment by muep** [comment]
Just a note that this issue is still present with GCC 4.9 as shipped in Fedora 21.

The issue does not appear if the -ffloat-store option is passed to GCC.

**Comment by Groovounet** [comment]
I finally figured the problem with this issue: Denorms!

This issue is fixed in master and 0.9.8 branches for GLM 0.9.8.4 release.

Thanks for reporting,
Christophe
