### ISSUE TITLE
OpenCL support status

### ISSUE THREAD

**Issue by promethe42** [g-truc/glm#218]
Hello,

I've seen there is a header to declare OpenCL types. But I could not find any further documentation about the support status of OpenCL.

Could you please tell me what's supported and what's in the roadmap?
Thank you!

**Comment by acterhd** [comment]
As I know, OpenCL 2.1 supports C++14, and OpenCL 1.2 (not 2.0) also support by AMD. So I think need made support for OpenCL 1.2, and later - for 2.1.

**Comment by Groovounet** [comment]
If someone is interested to add OpenCL support in GLM, I would suggest to make a pull request with some unit tests. :D

CUDA support was essentially added thanks to users contribution.

**Comment by Groovounet** [comment]
It looks like there is no interest for this so closing unresolved.
