### ISSUE TITLE
CUDA: compile error with swizzles: a pointer to a bound function may only be used to call the function

### ISSUE THREAD

**Issue by hrehfeld** [g-truc/glm#220]
I get 

```
Error   1   error : a pointer to a bound function may only be used to call the function D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\samples\v5.5\0_Simple\matrixMul\matrixMul.cu 51  matrixMul (Visual Studio 2010)  1
```

whenever I use 

```
#define GLM_SWIZZLE
#include <glm/glm.hpp>

    ::glm::vec4 v;
    ::glm::vec3 r = v.xyz; //error happens here
```

And I can't quite figure out why. This also happens with VS11/12, but not in cpu code. I assume it's the CUDA compiler itself.

Reproduce by inserting the above into one of the cuda samples.

It worked in earlier versions: https://github.com/tszirr/glm

**Comment by GeorgeR** [comment]
I'm getting these same errors with cuda 7 and vs2013 with glm 0.9.6.1.

**Comment by Groovounet** [comment]
Any update on the current status of that bug?

**Comment by hrehfeld** [comment]
Didn't have time to test latest glm yet... :/

**Comment by mickymuis** [comment]
I can confirm that this problem still exists with the latest GLM on CUDA 5.0. Haven't tested a more recent CUDA though. To clarify: I tested the function-style swizzles, not the C++11 swizzles.

**Comment by Groovounet** [comment]
I just tried with CUDA 8 and master branch (GLM 0.9.9). 

It seems to work just fine for me.

Here is basically the code I used:
```
__global__ void simple_vbo_kernel(glm::vec4 *pos, unsigned int width, unsigned int height, float time)
{
    unsigned int x = blockIdx.x*blockDim.x + threadIdx.x;
    unsigned int y = blockIdx.y*blockDim.y + threadIdx.y;

	glm::vec2 Size((float) width, (float) height);
	glm::vec2 Pos(x, y);
	glm::vec2 Coord = (Pos / Size) * 2.f - 1.f;

    // calculate simple sine wave pattern
    float freq = 4.0f;
    float w = sinf(Coord.x*freq + time) * cosf(Coord.y*freq + time) * 0.5f;

    // write output vertex
	glm::vec4 v = glm::vec4(Coord.x, w, Coord.y, 1.f);
	glm::vec3 u = v.xyz;
	glm::vec4 t(u, 1.f);

    pos[y*width+x] = t.xyzw;//make_float4(Coord.x, w, Coord.y, 1.0f);
}
```

And the includes:
```
#define GLM_FORCE_SWIZZLE
#include <glm/glm.hpp>
#include <glm/ext.hpp>
```

So, I'll assume this bug is fixed.
