### ISSUE TITLE
[feat.request] Quaternion LookAt

### ISSUE THREAD

**Issue by Calvin1602** [g-truc/glm#23]
There is no quaternion-based LookAt function. Ideally, this function would take a view direction, and an up vector. Here is one possible implementation, whi²ch assumes that the "front" of the object is towards +Z (should probably be an optional argument) :

```
vec3 right = cross(direction, desiredUp);
desiredUp = cross(right, direction); // re-orthogonalize

quat rot1 = RotationBetweenVectors(vec3(0.0f, 0.0f, 1.0f), direction);
vec3 newUp = rot1 * vec3(0.0f, 1.0f, 0.0f);
quat rot2 = RotationBetweenVectors(newUp, desiredUp);

return rot2 * rot1;
```

**Comment by CaptainCarrot** [comment]
Is there still interest in such a function? I recently required this functionality and have implemented it in the same fashion (LH/RH distinction) as the existing matrix version.

**Comment by Groovounet** [comment]
Wohhhhh! That would be great! Would you be happy to make a PR for this feature?

**Comment by CaptainCarrot** [comment]
I will happily do so (before that I'll need to figure out how to do this properly, so please excuse any mistakes on the process on my end). What would you want to baptise this function, something like quatLookAt?

**Comment by Groovounet** [comment]
Name it the way you want. :p 

gtx/quaternion.hpp/inl? sounds like a good fit. 
Also, it would be great it you could add a test for this function in test/gtx/quaternion.cpp
Historically, functions without a test ends up broken which is always disappointing. I hope we will be able to promote this feature in the stable quaternion features.

Thanks for contributing!

**Comment by Groovounet** [comment]
Done in master branch.
Christophe
