### ISSUE TITLE
glm doesn't compile with gcc's -pedantic flag

### ISSUE THREAD

**Issue by mrzzzrm** [g-truc/glm#251]
```
#include "glm/glm.hpp"

int main()
{
        return 0;
}
```

compiled with

`gcc -pedantic -std=c++11 main.cpp`

results in

`glm/detail/type_vec4.hpp:123:6: warning: ISO C++ prohibits anonymous structs [-Wpedantic]`

on the current master.

From the gcc manpage:

```
-pedantic
           Issue all the warnings demanded by strict ISO C and ISO C++; reject all programs that use forbidden extensions, and some other programs that do not follow ISO C and ISO C++.  For ISO C,
           follows the version of the ISO C standard specified by any -std option used.
```

So anonymous structs aren't a ISO C++11 feature, yet glm uses them. Are you aware of this? 
I would welcome glm to be C++ standard compatible by default, enabling non-std features only on demand.

**Comment by Groovounet** [comment]
It seems that issue https://github.com/hpicgs/globjects/issues/263 is closed. Closing this too then because it's not possible to detect if -pedantic is set and using -pedantic compatible is a too big lost of functionality for GLM.

Use GLM_FORCE_CXX98 if necessary.

Thanks,
Christophe
