### ISSUE TITLE
Issue while using new release of GLM (0.9.6.0) : quaternion & align

### ISSUE THREAD

**Issue by MarkTheFox** [g-truc/glm#283]
We are updating GLM from 0.9.5.4 (everything went well with #define GLM_FORCE_RADIANS) to 0.9.6.0 and it seems something goes wrong : Here is the message given by Visual 2012:

`GLM: Windows platform detected`
`GLM: Visual C++ compiler detected`
 `GLM: 32 bits model`
 `GLM: C++ with language extensions`
`GLM: #define GLM_FORCE_CXX98, GLM_FORCE_CXX03, GLM_LANG_CXX11 or GLM_FORCE_CXX1Y to force using a specific version of the C++ language`
`GLM: SSE2 instruction set`
 `GLM: #define GLM_FORCE_PURE to avoid using platform specific instruction sets`
`GLM: Swizzling operators enabled`
 `GLM: .length() returns glm::length_t, a typedef of int following the GLSL specification`
`GLM: #define GLM_FORCE_SIZE_T_LENGTH for .length() to return a size_t`
 `GLM: Core library included`
 `GLM: GLM_GTC_constants extension included`
`GLM: GLM_GTC_matrix_transform extension included`
`GLM: GLM_GTC_matrix_inverse extension included`
 `GLM: GLM_GTC_quaternion extension included`
`XXXXXXX\glm-0.9.6.0\glm\gtc\quaternion.hpp(116): error C2071: 'glm::tquat<T,P>::operator glm::tmat3x3<T,P>' : classe de stockage non conforme`
`XXXXXXX\glm-0.9.6.0\glm\gtc\quaternion.hpp(138) : voir la référence à l'instanciation de la classe modèle 'glm::tquat<T,P>' en cours de compilation`
`XXXXXXXXX\glm-0.9.6.0\glm\gtc\quaternion.hpp(117): error C2071: 'glm::tquat<T,P>::operator glm::tmat4x4<T,P>' : classe de stockage non conforme`

Other issue appeared : the data won't be aligned if not given as reference ?
`le paramètre formel avec __declspec(align('16')) ne sera pas aligné`

Thanks in advance,

**Comment by noizex** [comment]
Slightly different thing, but once I started using new glm (0.9.6.x) with GLM_FORCE_PURE (otherwise it complained about alignment) under MSVC, at some point I started getting some terrible heap corruptions in std::vector which allocated some structs with glm:: members inside. I spent week going through the code from the bottom to top, checking for mem leaks, memory overwrites and I was sure it's gone but then it came again, in the same place. 

I reverted glm to 0.9.4 and all was fine. Back to 0.9.6 and it went crazy again. I decided to try and fix alignment problems, and now I'm using 0.9.6.x without problems (but not #defining GLM_FORCE_PURE). I can't be 100% sure it was the cause, but I'm 90% positive it was new glm that caused this totally weird std::vector behaviour. 

I will try to reproduce it in some isolated testcase in the future, and fill a bug report if it still happens. Consider this as some remark on the topic, maybe someone has similar issues and no idea what causes them - try reverting glm to older version and see if it helps. Just guessing here as these things are hell to track and debug.

**Comment by amc522** [comment]
So I just got latest from the master branch of glm (0.9.7) and I too ran into the alignment issue. I'm compiling with vs2013 november ctp. I compile for both x86 and x64. When I do my compiling I run with /W4, which spit out a lot of warnings about non standard extensions.
```
warning C4201: nonstandard extension used : nameless struct/union (..\..\source\RenderAL\Color.cpp)
```
This warning has to do with anonymous structs inside another anonymous struct or union. Whenever this was introduced into the vector types, is when the alignment issue popped up.

Only the x86 architecture is showing errors about alignment. After figuring that out, I commented out the following line in glm/detail/setup.hpp
``` c++
#define GLM_HAS_ANONYMOUS_UNION !defined(GLM_FORCE_CXX98) && !defined(GLM_FORCE_CXX03) && (GLM_LANG & GLM_LANG_CXXMS_FLAG)
```

That fixed all the issues. Ill do some digging into why the msvc compiler has alignment issues with that code. Possibly file a bug with microsoft. For now I changed the line to following
``` c++
#define GLM_HAS_ANONYMOUS_UNION !defined(GLM_FORCE_CXX98) && !defined(GLM_FORCE_CXX03) && (GLM_LANG & GLM_LANG_CXXMS_FLAG) && !(GLM_COMPILER & GLM_COMPILER_VC)
```
(added '&& !(GLM_COMPILER & GLM_COMPILER_VC' to the end)
Hope this helps some people.

**Comment by tm4n** [comment]
I'm still having the same problem with glm 0.9.6.3 when compiling x86 code with Visual Studio Community 2013:

    error C2719: 'mVPMatrix': formal parameter with __declspec(align('16')) won't be aligned

in the code:

    virtual void draw(glm::mat4 mVPMatrix);

**Comment by noizex** [comment]
Try passing by reference.

**Comment by tm4n** [comment]
@noizex I can do that as a workaround, but then I get other problems:

    warning C4316: 'Mesh' : object allocated on the heap may not be aligned 16

for the object Mesh which has two glm:mat4 members. My code also hits a breakpoint in ntdll on deleting another object with glm::mat4 members. There is still something wrong here.
Linux 32 Bit build with gcc works fine. The glm version I was using before was also fine with visual studio (glm 9.5.x, dont know exactly right now). I also couldn't get GLM_FORCE_PURE to work.

**Comment by noizex** [comment]
For classes that use glm's aligned members I just inherit from a special allocator which allows allocating on heap without warnings. It works and does not cause crashes or memory leaks so I think it's okay. Link to that class is here: https://dl.dropboxusercontent.com/u/1040763/aligned_allocator.h. Then:
```
typedef AlignedAllocator<16> AlignedAllocator16;
class Mesh: public AlignedAllocator16
{
   glm::mat4   foo;
   glm::mat3   bar;
}
```
That's what I found after some reasearch about aligned members, but treat it with some reserve as I'm not C++ expert :)
