### ISSUE TITLE
0.9.6.1: vec4 Debugger visualizer for Visual Studio 2013

### ISSUE THREAD

**Issue by traits** [g-truc/glm#288]
glm.natvis seems OK to me and works for 3-dimensional vectors. For tvec4 on the other hand,  it seemingly has a parsing problem inside tvec4's definition and the VS2013 debugger will end up with the standard visualization. One line affecting the visualizer (still not quite correct) seems to be 

type_vec4.hpp:118:   typename detail::simd<T>::type data;

at the begin of tvec4's first union. Of course, this sounds be more like a MS problem, but possibly some refactoring could be the easier workaround.

Michael

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.6 branch for GLM 0.9.6.2 release.

Thanks for reporting!
Christophe
