### ISSUE TITLE
Negative numbers for unpackSnorm1x8 and unpackSnorm1x16

### ISSUE THREAD

**Issue by casfire** [g-truc/glm#292]
Both functions return 1 for negative numbers. Example:
```
glm::unpackSnorm1x8 (glm::packSnorm1x8 (-0.5))
glm::unpackSnorm1x16(glm::packSnorm1x16(-0.5))
```

Is this expected behaviour?

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.6 branch for GLM 0.9.6.2 release.

Thanks for contributing!
Christophe
