### ISSUE TITLE
gtc_packing signed to unsigned conversion warnings

### ISSUE THREAD

**Issue by bcrist** [g-truc/glm#295]
The functions `floatTo11bit` and `floatTo10bit` used by GLM_GTC_packing both return unsigned integers, and they both contain the statement `return ~0;`.

This should use an unsigned literal zero to avoid warnings about conversion from `int` to `unsigned int`:

    return ~0u;

**Comment by Groovounet** [comment]
This issue should be fixed in GLM 0.9.6 for GLM 0.9.6.2 release.

Thanks for contributing,
Christophe
