### ISSUE TITLE
test-gtc_integer fails on i686

### ISSUE THREAD

**Issue by muep** [g-truc/glm#296]
Seems to happen on master and the 0.9.6 branch

Steps to reproduce on GCC 4.9 as shipped in Fedora 21, starting with PWD at the glm repository root:

```
mkdir build
cd build
g++ -m32 -O2 -Wall -I .. ../test/gtc/gtc_integer.cpp
./a.out ; echo $?
```

By changing the optimization level, at least results 0, 1 and 4 can be obtained on my system. Passing the -ffloat-store option to GCC makes the test always succeed.

This could also be related to issue #212.

**Comment by Groovounet** [comment]
GLM is now automatically tested on Linux with GCC in both pure x86 and with SIMD instructions.
https://travis-ci.org/g-truc/glm

I believe this issue it fixed.

Thanks for contributing,
Christophe
