### ISSUE TITLE
invalid mat2x3 * mat3x2 operator overload

### ISSUE THREAD

**Issue by ekpyron** [g-truc/glm#297]
In glm/detail/type_mat2x3.inl line 435 why is there a second definition of operator*(mat2x3,mat3x2) returning a mat4x3? This doesn't make sense mathematically and conflicts with the corrent definition in line 405 resulting in compile time errors like:

ambiguous overload for 'operator*' (operand types are 'T {aka glm::tmat2x3<float, (glm::precision)0u>}' and 'V {aka glm::tmat3x2<float, (glm::precision)0u>}')

**Comment by Groovounet** [comment]
Sounds like a bug!

**Comment by ekpyron** [comment]
I think it should be mat2x3*mat4x2 instead of mat2x3*mat3x2 - that one seems to be missing

**Comment by ekpyron** [comment]
(and for mat2x3 * mat4x2 the function on line 435 seems correct and the return value would match)

**Comment by ekpyron** [comment]
So I suggest this patch: http://pastebin.com/diVdwrHT

**Comment by Groovounet** [comment]
This issue is fixed in branch 0.9.6 for GLM 0.9.6.2 release. 

Thanks for reporting,
Christophe
