### ISSUE TITLE
perspective with zFar < zNear

### ISSUE THREAD

**Issue by ekpyron** [g-truc/glm#298]
Could you remove the assertion "assert (zFar > zNear);" in glm/gtc/matrix_transform.inl line 221 and thus allowing perspective(...) to be called with zFar < zNear? It's common practice to switch the values of zFar and zNear in order to obtain a (perfectly valid) projection matrix that produces inversed depth values (i.e. it moves the near clipping plane to depth value 1.0 and the far clipping plane to 0.0, which for floating point depth buffers can result in a better precision distribution).

**Comment by Groovounet** [comment]
That's a good point.

I'll apply this change.

**Comment by ekpyron** [comment]
Thank you!

**Comment by Groovounet** [comment]
Done in GLM 0.9.6 branch for GLM 0.9.6.2 release

Thanks for contributing!
Christophe
