### ISSUE TITLE
Possibly an alignment problem on iOS armv7 32bit

### ISSUE THREAD

**Issue by datgame** [g-truc/glm#299]
Getting exception EXC_BAD_ACCESS (SIGBUS), subtype EXC_ARM_DA_ALIGN in vec3<float> default ctor.
This does not happen on arm64, nor in the ios-simulator (both 32 and 64 bit tested).
The problematic struct where the vec3 member is, is packed using #pragma pack(1).
Not packing the structs avoids the problem.
I found the GLM_FORCE_PURE macro to disable simd, as I figured those might crash on bad alignment, but setting this makes no difference.

**Comment by Groovounet** [comment]
Hi,

I suspect that this is a duplicate bug from #303 which should be fixed in GLM 0.9.6.2.

Thanks,
Christophe
