### ISSUE TITLE
Functions not inlined llvm on linux

### ISSUE THREAD

**Issue by zkellsworth** [g-truc/glm#302]
This may be an issue with clang and not glm.

On line 783 in setup.hpp GLM_INLINE is defined as "__attribute__((__always_inline__))". I have a static library that uses GLM linking to my application that also uses GLM. I'm also using the GLM_FORCE_INLINE macro.

When linking as is, I'll get duplicate definition problems. Modifying GLM_INLINE to be defined the same as the GCC line above "inline __attribute__((__always_inline__))" resolves this issue, but I don't want to submit a pull because I don't know if this has unintended consequences for other users of the library (and I really don't know pull etiquette). I'm also not sure if it is even a proper fix, as my reading around lead me to believe we're hinting to the compiler and its up to  the compiler rather or not to disregard the inline attribute. Also, I'm not really a programmer, I just like to pretend I am.

As far as my env setup goes, as reported from #GLM_MESSAGES
GLM: version 0.9.7
GLM: Linux platform detected
GLM: LLVM compiler detected
GLM: 64 bits model
GLM: C++11
GLM: SSE2 instruction set
GLM: Swizzling operators disabled [..etc]
GLM: .length() returns glm::length_t [..etc]

I hope I'm not wasting your time, but I've been banging my head against this wall for a couple of days now because everything looked correct to me. I just hope to save someone else some grief. The only other thing I think could be relevent to this, is it seems llvm-ld/link has been deprecated, and these days the the system linker is used (gnu ld in my case), at least until their lld project matures.

**Comment by Groovounet** [comment]
I think your analyse of the issue is correct. Clang and GCC can use the same force inline attributes so this is how GLM does it now.

Thanks for contributing!
Christophe
