### ISSUE TITLE
Program segfaults when using glm::value_ptr(glm::mat4)

### ISSUE THREAD

**Issue by anthonybakermpls** [g-truc/glm#309]
Hi, for some reason I can't use either glm::value_ptr() or &m[][] methods for passing a glm::mat4 to glUniformMatrix4fv.

 program fails in 
0  0x00007ffff68bfb80  __memcpy_sse2_unaligned  /build/buildd/eglibc-2.19/string/../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S  33

**Comment by Groovounet** [comment]
Hi,

On what platform do you encounter this issue?

Could you add #define GLM_MESSAGES before including GLM and report the compiler log?

Thanks,
Christophe

**Comment by Groovounet** [comment]
Otherwise, a workaround is probably #define GLM_FORCE_PURE 

Thanks,
Christophe

**Comment by anthonybakermpls** [comment]
Bah, I can't reproduce this in a stub now. Seems related to risky polymorphic behavior. Closing issue.
