### ISSUE TITLE
glm/gtx/scalar_relational.hpp not included in headers

### ISSUE THREAD

**Issue by jesusdz** [g-truc/glm#313]
glm/gtx/scalar_relational.hpp is not included anywhere in the headers, and it contains functions required by some methods in glm/detail/func_common.hpp/inl (e.g step()), so whenever I use them, the code doesn't compile.

**Comment by Groovounet** [comment]
Experimental extensions are never supposed to be included within core functionalities.

My expectation here is that you are using step functions with an unexpected series of arguments as of core features.
Including glm/gtx/scalar_relational.hpp my be a way to relax this behavior but that not the default behavior.

Thanks,
Christophe

**Comment by huyderman** [comment]
However, in GLSL [`step` accepts `genType` arguments](https://www.opengl.org/sdk/docs/man4/html/step.xhtml). However, since the implementation uses `lessThan` which requires `vecType`s, using scalars won't work as expected.
