### ISSUE TITLE
Formal parameter won't be aligned, Visual Vtudio

### ISSUE THREAD

**Issue by laelath** [g-truc/glm#316]
When compiling I get the compiler error "formal parameter with __declspec(align('16')) won't be aligned" seemingly randomly happening to certain variables, I'm using C++11, Visual Studio Express 2013 for Windows Desktop, Windows 7, compiling 32 bit. Have also tested it on my laptop with the same settings but Windows 8 instead. I don't get this on glm 0.9.5.4, only on all later versions.

**Comment by amc522** [comment]
So I just got latest from the master branch of glm (0.9.7) and I too ran into the alignment issue. I'm compiling with vs2013 november ctp. I compile for both x86 and x64. When I do my compiling I run with /W4, which spit out a lot of warnings about non standard extensions.
```
warning C4201: nonstandard extension used : nameless struct/union (..\..\source\RenderAL\Color.cpp)
```
This warning has to do with anonymous structs inside another anonymous struct or union. Whenever this was introduced into the vector types, is when the alignment issue popped up.

Only the x86 architecture is showing errors about alignment. After figuring that out, I commented out the following line in glm/detail/setup.hpp
```
#define GLM_HAS_ANONYMOUS_UNION !defined(GLM_FORCE_CXX98) && !defined(GLM_FORCE_CXX03) && (GLM_LANG & GLM_LANG_CXXMS_FLAG)
```
That fixed all the issues. Ill do some digging into why the msvc compiler has alignment issues with that code. Possibly file a bug with microsoft. For now I changed the line to following
```
#define GLM_HAS_ANONYMOUS_UNION !defined(GLM_FORCE_CXX98) && !defined(GLM_FORCE_CXX03) && (GLM_LANG & GLM_LANG_CXXMS_FLAG) && !(GLM_COMPILER & GLM_COMPILER_VC)
```
(added '&& !(GLM_COMPILER & GLM_COMPILER_VC' to the end)
Hope this helps.

**Comment by engineer0x47** [comment]
See my post on #235 .

**Comment by Groovounet** [comment]
Hi,

Can you still reproduce this issue on the master branch?
I never managed to reproduce it. A repro case would be great!

Thanks,
Christophe
