### ISSUE TITLE
Visual studio 2015 ctp 5 intellisence crashes on android native activity project.

### ISSUE THREAD

**Issue by aminroosta** [g-truc/glm#318]
I've enabled -c++11 compiler flag and set up the linker to link against gnu_staticstl.
as soon as i `#include<glm/glm.hpp>` or any of `glm` header files, visual studio intellisence crashes.

here is my project : https://github.com/aminroosta/persian-traffic-racer/tree/master/App/App.NativeActivity

**Comment by Groovounet** [comment]
I think a better place would be to report this issue to Microsoft.

**Comment by aminroosta** [comment]
@Groovounet you are right. i will do that right now :)
