### ISSUE TITLE
VS2013 warning C4316 object allocated on the heap may not be aligned 16

### ISSUE THREAD

**Issue by bonizz** [g-truc/glm#322]
Not sure if this is the same issue as https://github.com/g-truc/glm/issues/316

I upgraded from 0.9.5.4 to 0.9.6.3 and get this warning:
`warning C4316: 'B' : object allocated on the heap may not be aligned 16`

Here's a simplified code sample which gives this warning:
```c
class A
{
};

class B : public A
{
	glm::vec4 a;
};

int main()
{
	B *t = new B();
	return 0;
}
```
Is this a bug? Or are there new alignment requirements?

Thanks

**Comment by TomVeltmeijer** [comment]
This seems to be the same issue as #235, where allocating a ```vec4``` or ```mat4``` on the heap causes ```warning C4316```.
Not sure if #316 is the same issue, but the workaround provided in the comment section there does get rid of this warning for me.

**Comment by engineer0x47** [comment]
See my comment on #235 .  This is not an issue unless you are attempting to run SSE instructions on it.

**Comment by Armada651** [comment]
This issue breaks GLI with VS2013, it can no longer correctly read headers because the struct size of the DDS header is incorrect.

**Comment by Groovounet** [comment]
Are you using master branch of GLI?

**Comment by Groovounet** [comment]
I am not quite sure how this issue affects GLI.

**Comment by Groovounet** [comment]
I'll update GLI to use master branch of GLM and that should fixed the problem.

**Comment by Groovounet** [comment]
This bug should be fixed by https://github.com/g-truc/glm/commit/c10df14b5855e8b0b7c4ad47968e828462ddf12e

I forgot to reference this bug number in the commit...

Thanks for reporting,
Christophe

**Comment by Armada651** [comment]
@Groovounet I recommend to also add a static assert on the size of that struct, to ensure it can't happen again.

**Comment by Groovounet** [comment]
Sounds good!

**Comment by Armada651** [comment]
You can do it like this and check the entire ddsHeader struct at once: https://github.com/Microsoft/DirectXTex/blob/1167ebb9c7615a1f515903b12e61ab3e98209315/DirectXTex/DDS.h#L234
