### ISSUE TITLE
Add access to array of columns in matrices

### ISSUE THREAD

**Issue by chbaker0** [g-truc/glm#323]
Currently you can access the columns of a matrix individually with the overload of `operator[]` but for some purposes it would be useful to be able to access the array of column vectors (i.e. for some generic programming purposes). I think this would be a useful addition, because currently I have to do stuff like this: `*static_cast<const glm::tvec4<T, P>(*)[4]>(static_cast<const void*>(&unit[0]))` to get that functionality.

**Comment by JesseTG-HBO** [comment]
[glm/matrix_access.hpp](https://github.com/g-truc/glm/blob/master/glm/gtc/matrix_access.hpp) provides this.

**Comment by JesseTG** [comment]
Is this issue considered fixed?

**Comment by Groovounet** [comment]
This functionality is already available with GLM_GTC_matrix_access.

Thanks,
Christophe
