### ISSUE TITLE
Document glm::perspective takes radians

### ISSUE THREAD

**Issue by gigadude** [g-truc/glm#326]
I just spent way too long tracking down an issue caused by my assumption that glm::perspective matched the GLU function (which is documented as taking degrees, not radians). This difference should be documented more prominently.

**Comment by Groovounet** [comment]
The manual for GLM 0.9.7 has been updated adding an entry to the FAQ to clarify this topic.

More information are available here: http://www.g-truc.net/post-0693.html#menu

Thanks for reporting,
Christophe
