### ISSUE TITLE
Proposal: Move parts of gtc_random into gtc_sampling

### ISSUE THREAD

**Issue by Nadrin** [g-truc/glm#328]
I propose that parts of `GTC_random` module be moved into new `GTC_sampling` module. Changes would include:
 * Moving `circularRand`, `sphericalRand`, `diskRand` & `ballRand` functions into `GTC_sampling` (possibly changing their names accordingly).
 * Making all sampling functions take a uniformly distributed sample value as an input to decouple them from the pseudorandom-number generator.

Rationale for this change is as follows:
 * Sampling functions usually transform a uniformly distributed random variable. It is sometimes beneficial to generate this variable separately ahead of time.
 * Some sampling functions, especially low-discrepancy sequence generators used in quasi Monte Carlo sampling, do not even use random numbers at all.

If this proposal is approved I'd be interested in implementing this change myself and further improving the new `GTC_sampling` module with hemispherical & cosine-weighted hemispherical sampling, improved disk sampling (without using rejection sampling), and implementing some low-discrepancy sampling techniques (mainly using Halton sequences & Hammersley sets).

**Comment by Groovounet** [comment]
I think this would be a valuable improvement.

Thanks,
Christophe

**Comment by Groovounet** [comment]
It seems this feature request has been abandoned. 
Also GLM doesn't have data structures so it's not obvious how to separate the sampling and data.

The feature sounds good but probably this is something the code using GLM should deal with.

Thanks,
Christophe
