### ISSUE TITLE
Provide pkg-config file

### ISSUE THREAD

**Issue by alzeih** [g-truc/glm#329]
It may be helpful to provide a pkg-config file with glm.

There is a guide here: http://people.freedesktop.org/~dbn/pkg-config-guide.html#writing

Expected outcome: `pkg-config --exists --print-errors glm` to not return an error.

**Comment by Groovounet** [comment]
Hi,

If this feature is important for you, I would recommend you to submit a pull request.

Thanks,
Christophe
