### ISSUE TITLE
Forcing -m64 for GCC disrupts testing on 32-bit systems

### ISSUE THREAD

**Issue by muep** [g-truc/glm#331]
Is it actually necessary to have CMakeLists.txt always specify -m64 like it does here:

```cmake
if(CMAKE_COMPILER_IS_GNUCXX)
	#add_definitions(-S)
	#add_definitions(-s)
	add_definitions(-m64)
	add_definitions(-O2)

	#add_definitions(-fprofile-arcs -ftest-coverage) gcov
	#ctest_enable_coverage()
endif()
```

I would normally expect to be able to build and run the tests on the native architecture of the host I use, without having to change the cmake setup on 32-bit hosts. This is also used in the Fedora packaging of glm, that runs the tests shipped alongside glm when packages are built.

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.7 release and I might back port it to GLM 0.9.6.4 if this is useful.

Thanks for contributing,
Christophe
