### ISSUE TITLE
Please bring hvec* back.

### ISSUE THREAD

**Issue by hypernewbie** [g-truc/glm#336]
They seem to have been removed because they were slow.

I think glm should assume the programmer knows that an overloaded operator half-float class will be conversion hell and be really slow.

Now the first thing I need to do when using glm is to code my own half-float with a warning sticker up the top say this is for packing only. This is dumb. It should be part of glm.

I don't think glm should go down the path of "assume programmer doesn't know what they're doing perf-wise" because those programmers wouldn't find a use for glm in the first place.

**Comment by Groovounet** [comment]
I think the packing functions are a better alternative to half vec types:
http://glm.g-truc.net/0.9.6/api/a00155.html
http://glm.g-truc.net/0.9.6/api/a00173.html

hvec* types only leads to writing slow and un-explicit code. Additionally, there are hard to maintain and can't get feature parity with others vec*. 

Thanks,
Christophe
