### ISSUE TITLE
Improve SIMD support and documentation

### ISSUE THREAD

**Issue by KammutierSpule** [g-truc/glm#337]
Hello, I wish you could provide more documentation regarding the SIMD.
I am trying to use the gtx/simd_vec4.hpp and I dont know how to proper include it and what flags or defines do I need to be able to build with it.
Any help?

**Comment by svenstaro** [comment]
This should be renamed to "Improve SIMD documentation" and I would agree that it should be improved.

**Comment by giordi91** [comment]
Hi any news on this front?

**Comment by Groovounet** [comment]
Not yet... hopefully with GLM 0.9.8 as I am working on SIMD improvements but it will take some times.

**Comment by Groovounet** [comment]
GLM 0.9.8 was released SIMD support is now transparent. If the compiler is configured to use SIMD instructions, GLM will follow the compiler settings. Only vec4 and mat4 really benefit from the SIMD optimizations.

GTX_simd_vec4 is deprecated in GLM 0.9.8 and removed in trunk.

Thanks,
Christophe

**Comment by kklouzal** [comment]
The GLM Manual should be a bit more specific and state which types benefit from SIMD enhancements. I went on a bit of a wild goose chase only to eventually have someone inform me only vec4 mat4 and quat benefit.

Aside from that are there any plans to enhance vec3 and mat3 or any other types?
