### ISSUE TITLE
bad include? intrinsic_integer.hpp:31:23 glm/glm.hpp: No such file

### ISSUE THREAD

**Issue by KammutierSpule** [g-truc/glm#338]
glm/gtx/../detail/intrinsic_integer.hpp:31:23: fatal error: glm/glm.hpp: No such file or directory
 #include "glm/glm.hpp"

Shall this be in a different way included?

**Comment by Groovounet** [comment]
This bug report lack of information on how to reproduce the issue hence I am not sure I properly fixed the problem but I pushed a tentative fix.

Thanks,
Christophe

**Comment by DaniBarca** [comment]
Why isn't this change (1294d4d) in the last release? Is it safe to change it myself? I'm not used to this kind of libraries and I don't know if I'm including it wrong or it's just the code.
