### ISSUE TITLE
Unresolved external symbol when using glm::linearRand

### ISSUE THREAD

**Issue by sasmaster** [g-truc/glm#340]
I am using glm version 0.9.4.1 

If I use glm::linearRand ,for example

   int frame_index = glm::linearRand(0,10);

I am getting this:

    Error	3	error LNK2019: unresolved external symbol "public: int __cdecl glm::detail::compute_linearRand::operator()<int>(int const &,int const &)const " (??$?RH@compute_linearRand@detail@glm@@QEBAHAEBH0@Z) referenced in function main	E:\Documents\visual studio 2012\Projects\XXX\XXXX\SomeObj.obj

**Comment by JesseTG** [comment]
Is this still an issue?

**Comment by Groovounet** [comment]
This issue was resolve a while ago, at least the fix is available in GLM 0.9.8.

Thanks,
Christophe

**Comment by Groovounet** [comment]
Fixed in GLM 0.9.6 with #230.

The fix added linear overloads for integers.

Thanks,
Christophe
