### ISSUE TITLE
linearRand compile issue in CUDA file

### ISSUE THREAD

**Issue by epoutot** [g-truc/glm#347]
With CUDA 7.0 and GLM 9.6.3 on Visual C++ 2010

Fail to compile in a C function (not a kernel) in a .cu file :
float f = glm::linearRand(0.f, 1.f);

Workaround that compiles :
float f = glm::linearRand(glm::tvec1<float>(0.f), glm::tvec1<float>(1.f)).x;

A bit ugly, maybe could be nice that the first line compiles in a .cu like it does in a .cpp

**Comment by Groovounet** [comment]
I think it's a (yet another!) CUDA compiler bug so I would suggest to report it to NVIDIA.

If there is a known workaround, I would be happy to accept a pull request.

Thanks,
Christophe
