### ISSUE TITLE
noexcept move ctors

### ISSUE THREAD

**Issue by gartenriese2** [g-truc/glm#353]
Are the move constructors noexcept? Sorry I couldn't find anything in the code.

**Comment by Groovounet** [comment]
There isn't but what would be the purpose of that in GLM?

**Comment by gartenriese2** [comment]
To ensure that move semantics are used when using std::vector for example.

**Comment by Groovounet** [comment]
Yes but GLM doesn't have and doesn't need move constructors.

**Comment by gartenriese2** [comment]
Can you elaborate why GLM doesn't need move semantics?

**Comment by chbaker0** [comment]
There are no resources being managed. All the classes just have plain old data, so a move constructor would do exactly the same thing as a copy constructor.

**Comment by gartenriese2** [comment]
Oh, I see, thanks!
