### ISSUE TITLE
Find another Web host

### ISSUE THREAD

**Issue by JesseTG-HBO** [g-truc/glm#356]
Seriously, your site's down, like, well over half the time.  What's up with that?

**Comment by Groovounet** [comment]
First time I see that complain. It works for me at the moment.

**Comment by JesseTG-HBO** [comment]
Is it a DNS thing?  I'm in New York, if that matters.

**Comment by Groovounet** [comment]
Is it possible that your employer is blocking some DNSs? For example, the website used to be blocked at NVIDIA because of the DNS something (tm) so they had to fix it.

**Comment by JesseTG-HBO** [comment]
Nope, same problem at home.  Also, if it were a block, I'd see a page alerting me as such.

**Comment by JesseTG-HBO** [comment]
(Also, for what it's worth, GitHub pages is absolutely free, and you can use your existing domain names; your site, being made of static content, would be an excellent fit for it)

**Comment by Groovounet** [comment]
I shall try then.

**Comment by JesseTG-HBO** [comment]
Also, money where my mouth is.

![capture](https://cloud.githubusercontent.com/assets/12735626/8777816/53fdce7a-2ec8-11e5-94d6-d203a6ee3cb8.PNG)

**Comment by JesseTG-HBO** [comment]
(Love this library, though!  Thanks for all the hard work; I do plan on contributing more to it!)

**Comment by richardeakin** [comment]
FWIW I've never seen glm.g-truc.net down.

**Comment by JesseTG-HBO** [comment]
[I feel like I'm taking crazy pills.](https://en.wikipedia.org/wiki/Zoolander)

**Comment by JesseTG-HBO** [comment]
You know what, maybe it actually *is* my employer's DNS.  But I haven't encountered any other websites that hang on me like this.

**Comment by Groovounet** [comment]
Can you try http://www.icare3d.org/? 

The same DNS blocking happen here. This said he found a workaround in theory.

This said, it might be worth asking your employer to white list the page.

**Comment by JesseTG-HBO** [comment]
That site works just fine for me.

**Comment by Groovounet** [comment]
It's the same server but he added a trick to workaround DNS blocks. \o/
It could be another option.

**Comment by JesseTG-HBO** [comment]
Where is the trick, on one of his blog posts?

**Comment by Groovounet** [comment]
No in the configuration of his server.

**Comment by JesseTG-HBO** [comment]
Well, I can't go and look at his server now, can I?

**Comment by chbaker0** [comment]
Also, for what it's worth, I could never access your website from my college campus, but I can at home. So I'm yet another person who's experienced this problem. Probably is DNS related.
