### ISSUE TITLE
Detect noexcept and use it if it exists

### ISSUE THREAD

**Issue by JesseTG** [g-truc/glm#357]
Might provide a free speed boost.  Or not.  Who knows?

**Comment by Groovounet** [comment]
Browsing this blog post: https://akrzemi1.wordpress.com/2011/06/10/using-noexcept/ I am not sure there is any use for noexcept in GLM.

**Comment by nireis** [comment]
I am trying to use GLM Types inside std::atomic and Clang fails to compile. Might be worth adding noexcept to GLM after all.

Code: https://gist.github.com/nireis/6a7669cb1822ca33c146e9eae4a84fe8

I want to use atomics for pushing data updates to a rendering thread without race conditions.

**Comment by scheibel** [comment]
There is functionality in cmake to detect noexcept availability in compilers.
 * [Handling compiler features documentation](https://cmake.org/cmake/help/v3.1/manual/cmake-compile-features.7.html#optional-compile-features), especially the section about optional compiler features using `write_compiler_detection_header`
 * [List of known features](https://cmake.org/cmake/help/v3.1/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES), including `cxx_noexcept`

**Comment by Groovounet** [comment]
It doesn't look like std::atomic requires noexcept, it only required defaulted constructors. At least, it compiles fine for me. Let me know if you encounter any issue.

Thanks,
Christophe

**Comment by AntonTokarev** [comment]
Having noexcept copy or move is essential when using with STL containers (or any other with exception safety).
For example, adding the glm-type field into an any class makes the default move constructor non-noexcept and std::vector of such class makes the full copy instead of move on resize.
