### ISSUE TITLE
Consider changing _vectorize.hpp to accept its functions as template arguments

### ISSUE THREAD

**Issue by JesseTG** [g-truc/glm#360]
It might provide a speedup.  Or it might bloat the code massively.  Who knows?

**Comment by Groovounet** [comment]
I am not sure what you mean here.

**Comment by JesseTG** [comment]
For example; what if `[wrapAngle](https://github.com/g-truc/glm/blob/master/glm/gtx/fast_trigonometry.inl#L70)` was passed in as a template parameter instead of a runtime parameter?  And in every other place you use a similar pattern for making functions operate component-wise?

**Comment by Groovounet** [comment]
I see. I might be worth looking at how this would perform and generated assembly.

**Comment by JesseTG** [comment]
I did some quick profiling of this today, actually, though only of functions in the `functor1` family.  There doesn't appear to be a benefit; the build times, test execution speed, and even test binary sizes are about the same.

So, while using function pointers as template arguments doesn't seem harmful, there's no apparent benefit to going into the code and changing everything that uses `_vectorize.hpp` to work that way.  But the feature itself could be useful in new code.  Perhaps another project.

**Comment by JesseTG** [comment]
Wait, actually, my test may have been fundamentally flawed; it may have been using the GLM headers I'd installed to my *system* includes instead of using the modified headers still in my workspace.  Son of a bitch.
