### ISSUE TITLE
OpenACC GCC issue

### ISSUE THREAD

**Issue by acterhd** [g-truc/glm#362]
I can't compile OpenACC program with GLM by MingW-w64. 

Archive: 
https://onedrive.live.com/redir?resid=54D7DA9CDEF82B01!29027&authkey=!AMwAGMwK7nMqPi4&ithint=file%2czip

I can no to give error log, because its too long.

**Comment by Groovounet** [comment]
No error log, I never heard of it so I would suggest a pull request if you want such support.
