### ISSUE TITLE
Add directive to force default constructors

### ISSUE THREAD

**Issue by patnashev** [g-truc/glm#366]
If constructors and assignment operator are defined as default:

    GLM_FUNC_DECL tvec2() = default;
    GLM_FUNC_DECL tvec2(tvec2<T, P> const & v) = default;
    GLM_FUNC_DECL tvec2<T, P>& operator=(tvec2<T, P> const & v) = default;

then tvec2 can be used in unions. Implicitly-defined constructors provide no functionality but make the classes non-trivial.

**Comment by plasmacel** [comment]
it's not a bad idea

**Comment by Groovounet** [comment]
I agree, I like it.

**Comment by Groovounet** [comment]
This feature has been in master branch for GLM 0.9.7 release.

Thanks,
Christophe
