### ISSUE TITLE
Figure out why the website is blocked from certain DNS servers and do something about it

### ISSUE THREAD

**Issue by JesseTG** [g-truc/glm#369]
As nice as GLM is, nobody's gonna use it if they can't access the website.

**Comment by tndev** [comment]
It doesn't look like it is a DNS problem. It seems as if a larger range of IP addresses are blocked. The IP itself is correctly resolved for `g-truc.net`, but connecting to the server is refused.

**Comment by tndev** [comment]
The IP `213.186.33.19` itself is regularly listed on black lists due to other sites distributing malware on the same server. So the glm documentation isn't reachable from many institutions.
