### ISSUE TITLE
Strict aliasing warning

### ISSUE THREAD

**Issue by preet** [g-truc/glm#370]
Hi, I get several warnings like:

.../thirdparty/glm/detail/func_packing.inl:54: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   return reinterpret_cast<uint const &>(Topack);
                                               ^
When compiling with glm (gcc 5.2). I'm using release 0.9.6.3. I noticed that there were a couple of similar issues before that were closed with a fix in the 0.9.5.x releases but they seem to have popped up again.

**Comment by Groovounet** [comment]
This issue should be fixed in master branch for GLM 0.9.7.1 release.

Thanks,
Christophe
