### ISSUE TITLE
glm::min / max difference behavior than std::min / max

### ISSUE THREAD

**Issue by KammutierSpule** [g-truc/glm#372]
Hello!
I am using float NAN to initialize my float vectors. In accord to the float.h from gnu builder, I found that it is expected that fmin fmax in the presence of a non number will choose the number.
i.e:
fmin( nan, value) == value
fmax( nan, value) == value

But it looks like the glm::min / max is not behaving the same. is it supposed?

Btw, is that too bad that I use a NAN to set the vector "not initialized" ?

**Comment by Groovounet** [comment]
fmin and fmax are C++11 only features which makes it hard to generalize to GLM.

I guess adding an extension exposing vector flavors or fmin and fmax could be nice.

If you carefully using your NaN vectors, that is to say, you are never doing any arithmetic on them, I guess it's not too bad. However, I would not consider it as a great coding practice.

Thanks,
Christophe

**Comment by KammutierSpule** [comment]
I was checking,  there is a c99 fminf and fmaxf but I didn't test if the behaviour is the same.
it should be:
http://man7.org/linux/man-pages/man3/fmin.3.html

**Comment by johnmcfarlane** [comment]
I'd expect for `glm::min` to behave the same as [`std::min`](http://en.cppreference.com/w/cpp/algorithm/min) and for `glm::fmin` to behave the same as [`std::fmin`](http://en.cppreference.com/w/cpp/numeric/math/fmin) etc.. 

The only minor exception would be that for `std::max(a, b)` where `a == b`, then `a` is returned whereas `b` should be returned. (This has subtle implications if `T` is a reference.)

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9 release. Better now that never XD.

Thanks for reporting,
Christophe
