### ISSUE TITLE
Getting a bunch of link errors 

### ISSUE THREAD

**Issue by mmmovania** [g-truc/glm#374]
I was previously using glm version 9.6.2 and the code runs fine. Now I am updating to the latest branch 9.7.0 but it gives me a bunch of linker errors like this

`error LNK2019: unresolved external symbol "public: __thiscall glm::tvec2<float,0>::tvec2<float,0>(struct glm::tvec2<float,0> const &)" (??0?$tvec2@M$0A@@glm@@QAE@ABU01@@Z) referenced in function ...`

glm spits the following info in the output windows about my platform.
`GLM: version 0.9.7.0
GLM: Windows platform detected
GLM: Visual C++ compiler detected
GLM: 32 bits model
GLM: C++0x
GLM: Language extensions enabled
GLM: SSE2 instruction set
GLM: Swizzling operators disabled, #define GLM_SWIZZLE to enable swizzle operators
GLM: .length() returns glm::length_t, a typedef of int following the GLSL specification
GLM: Core library included
GLM: GLM_GTC_constants extension included
GLM: GLM_GTC_matrix_transform extension included
GLM: GLM_GTC_quaternion extension included
GLM: GLM_GTC_type_ptr extension included`

I am including glm/glm.hpp as we did earlier. Does the new update require adding additional preprocessor flags?

**Comment by Groovounet** [comment]
You should be able to include GLM just the way you used to. 

It seems to work fine with me... is it possible that you updated GLM 0.9.7.0 on top of 0.9.6.2 and not all file got updated properly living some GLM 0.9.6.2 files?

Thanks,
Christophe

**Comment by mmmovania** [comment]
Strangely I cleaned and rebuilt and the code runs fine now.

**Comment by Groovounet** [comment]
I had this problem recently when switching to VC2015

**Comment by mmmovania** [comment]
yeah may be I was running this on vs2015 when I got these errors
