### ISSUE TITLE
Some alternative function name suggestion

### ISSUE THREAD

**Issue by plasmacel** [g-truc/glm#381]
As I now use glm as my core math library, I got some remarks and suggestions to make it more comfortable and intuitive. I know all the naming conventions came from the GLSL specification, however I'd like to propose some alternative function names, which should be an optional feature (if I'm not wrong glm already has something like it for some functions). 

So, the oddballs:

glm::inversesqrt
It's long. Really long. It bloats complicated computations, making them longer and harder to read.
I know inversesqrt comes from the GLSL specification, but we should have an option to have a shorter alternative besides the original one. I suggest an alternative glm::isqrt - it's short, expressive and makes sense.

glm::modf
Well, modf and mod are basically the same function - just different implementations for different types.
Just like atan2(x,y) is simply atan(x,y) in glm (again, it comes from GLSL, which is good in this case), which makes much sense, we should have the ability to use modf just the same way. Just some partial specialization of mod for floating point types.

glm::radians
Again, too long if you use it frequently. glm::rad would be better.

glm::degrees
Ctrl-C/Ctrl-V. glm::deg would be nice too.

So I'm looking forward your opinions.

**Comment by Groovounet** [comment]
I guess you answered in your message why the names are the way they are and why they won't be changed.

Thanks,
Christophe

**Comment by richardeakin** [comment]
Aside from the clear goal that the names are meant to match the glsl standard, my opinion is that the names listed are not too long. Clearity with a 4-11 letter name is better overall than relying on expert knowledge and using short names.

**Comment by plasmacel** [comment]
That's why I proposed it as an optional feature, like an extension. It's clear that the original naming shouldn't be changed, however the additional shorter alternatives can be more productive if someone doesn't want to stick to GLSL. GLM now has a broad usage area aside from computer graphics, just like simulation, image processing, calculus and general vector mathematics. On these areas GLSL strictness is not a priority. In a long complicated computation some would better see isqrt(rad(sin(45)) subpart than inversesqrt(sin(radians(45))).
