### ISSUE TITLE
epsilonEqual for mat types

### ISSUE THREAD

**Issue by richardeakin** [g-truc/glm#387]
Is there any interest in adding support to `gtc::epsilonEqual` for `matX` types?  I've been wanting it mainly for debugging, to ensure that a matrix is what I expect at a certain point.

**Comment by Groovounet** [comment]
Sounds like a good idea.

**Comment by Groovounet** [comment]
This sounds like a good idea however GLM doesn't support bmat making this feature tricky or overkill to implement.
