### ISSUE TITLE
Perspective matrix creation now takes radians, but is still degrees in manual

### ISSUE THREAD

**Issue by TimothyWrightSoftware** [g-truc/glm#389]
I noticed by accident that the perspective fov is now in radians, but the example code in the manual still shows degrees.  This should really be in huge letters somewhere.  If I switch versions, suddenly, nothing works, and I'm never going to suspect that the libraries' matrix creation routine just switched data types.

**Comment by TimothyWrightSoftware** [comment]
http://glm.g-truc.net/0.9.7/code.html

The example code also shows degrees, not radians.

**Comment by Groovounet** [comment]
There is a write up about how to transition from old versions of GLM to version using radians exclusively:
http://www.g-truc.net/post-0693.html#menu

I should probably copy this over to GLM website.

I'll fix the code sample.

**Comment by Groovounet** [comment]
This issue is now resolved. Thanks for reporting!
