### ISSUE TITLE
What is glm/detail/func_noise.hpp

### ISSUE THREAD

**Issue by richardeakin** [g-truc/glm#398]
Asking because some cinder users are finding these headers and including them instead of `glm/gtc/noise.hpp`, and also because there are compile errors with some of the overloads (see discussion [here](https://github.com/cinder/Cinder/issues/901#issuecomment-138105102)).  From what I can see, glm/detail/func_noise.hpp is not used by anything outside of the detail namespace, is it from a previous implementation and should no longer be used?

**Comment by Groovounet** [comment]
Ah yes this is legacy code that's no longer used. I'll removed it. 

Thanks,
Christophe
