### ISSUE TITLE
CUDA unresolved external symbol

### ISSUE THREAD

**Issue by dend456** [g-truc/glm#399]
Using GLM 9.7.0, Visual Studio 2013 and CUDA 6.5/7.5 the following code 

    #include <glm\vec3.hpp>
    using namespace glm;

    class Camera
    {
    public:
        vec3 pos;
        Camera(const vec3& p) : pos(p) {}
    };

    int main(int argc, char** argv)
    {   
        Camera c(vec3(0.0f, 0.0f, 0.0f));
        return 0;
    }

gives this error when compiling:

    error LNK2019: unresolved external symbol 
    "public: __thiscall glm::tvec3<float,0>::tvec3<float,0>(struct glm::tvec3<float,0> const &)" 
    (??0?$tvec3@M$0A@@glm@@QAE@ABU01@@Z) referenced in function 
    "public: __thiscall Camera::Camera(struct glm::tvec3<float,0> const &)" (??    0Camera@@QAE@ABU?$tvec3@M$0A@@glm@@@Z)

This error doesn't happen in non-CUDA projects and GLM version 9.6.2 does not have the problem (9.6.3 does).

**Comment by Groovounet** [comment]
Hi,

This issue should be fixed on master branch already. GLM 0.9.7.1 is going to be released with the fix tonight, it could great if you could confirm it fixes your issue too.

Thanks,
Christophe

**Comment by dend456** [comment]
Yup, the master branch works. Thanks.
