### ISSUE TITLE
Upgrading results in distorted perspective

### ISSUE THREAD

**Issue by mdeforge** [g-truc/glm#400]
What part of the 0.9.5.4 to 0.9.6.0 (or latest) upgrade could have caused my rendering to go from normal perpsective rendering to something whacky like this? http://screencast.com/t/cB1pqupy9 I've narrowed it down to these two versions. Works fine in 0.9.5.4 but as soon as I go to 0.9.6 my rendering goes crazy. 

I'm hoping to save myself hours of comparing versions by asking this here. I've read the change log but nothing jumps out. I've been looking at the matrix transformation classes but nothing has stood out as being a reason. Same goes for the perspective function.

My model view perspective matrix looks like this currently: mvp = ProjectionMatrix * ViewMatrix * ModelMatrix Something seems really off with either the projection or view matrix.

**Comment by Groovounet** [comment]
http://www.g-truc.net/post-0693.html

**Comment by mdeforge** [comment]
Bingo... thank you very much!
