### ISSUE TITLE
shearZ3D

### ISSUE THREAD

**Issue by TBurnettIII** [g-truc/glm#403]
Shouldn't the glm::shearZ3D transform be:

```
m[2][0] = s;
m[2][1] = t;
```

**Comment by plasmacel** [comment]
GLM should follow the GLSL convention and store it's matrices in column-major order.
According to that, not only shearZ3D, but all the shear functions are wrong.

references
http://www.cs.colorado.edu/~mcbryan/5229.03/mail/55.htm
http://run.usc.edu/cs480-s13/lec05-viewing/05-viewing-6up.pdf

**Comment by TBurnettIII** [comment]
Thanks for verifying that issue.  Has a bug report been submitted then?

Thomas.

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.8 branch for GLM 0.9.8.3 release.

Thanks for reporting,
Christophe
