### ISSUE TITLE
Proposal: Decouple feature detection into another library

### ISSUE THREAD

**Issue by JesseTG** [g-truc/glm#404]
[`setup.hpp`](https://github.com/g-truc/glm/blob/master/glm/detail/setup.hpp) is, honest to God, the best and most elegant cross-platform way of detecting C++ features I've seen.  I think that decoupling it into a separate library (and introducing it as a dependency of `glm`) might be of great benefit to C++ projects that don't use large frameworks (like Qt) that provide this functionality.  What do you think?

**Comment by Groovounet** [comment]
I think it's a good idea if that useful for someone, why not.
