### ISSUE TITLE
Add static unit vectors/identity matrix constants

### ISSUE THREAD

**Issue by JesseTG** [g-truc/glm#410]
Yeah, it's true that you could just use `something = vec4(0,0,1,0)`, but I think `something = vec4::Z` (where `Z` is `static const glm::vec4::Z {0, 0, 1, 0}` or something) would be convenient.

**Comment by Groovounet** [comment]
This is a duplicated feature request: https://github.com/g-truc/glm/issues/21

Thanks,
Christophe
