### ISSUE TITLE
Intel Compiler and C++11

### ISSUE THREAD

**Issue by rettenbs** [g-truc/glm#411]
Hi,

I am using the Intel Compiler (15.0) but without C++11 features.
When I include glm files, glm auto-detects C++11 (although it is not activated) due to those two lines in setup.hpp:
```
#                       elif GLM_COMPILER >= GLM_COMPILER_INTEL13
#                               define GLM_LANG (GLM_LANG_CXX0X | GLM_LANG_CXXMS_FLAG)
```

I have to define GLM_FORCE_CXX98 to compile your project with glm. Is this intended?

Best,
Sebastian

**Comment by Groovounet** [comment]
Hi,

Are you on Linux or MacOSX?
ICC supports on Linux is not really tested and because of the different compiler front end, it can make stuff complicated at times.

On Windows there is no enable so it's possible, we should add an enable for Linux.

Thanks,
Christophe

**Comment by rettenbs** [comment]
I am using Linux.

I can help testing if you want.
