### ISSUE TITLE
ceilMultiple wrong result

### ISSUE THREAD

**Issue by rettenbs** [g-truc/glm#412]
The result of ceilMultiple(3.4, 0.3) is 2.7. However, I would expect it to be 3.6.

There is this line, which seems to cause the problem:
```
genType Tmp = Source - genType(1);
```

There might be a similar bug in floorMultiple (for negative values).

**Comment by rettenbs** [comment]
I have created a pull request that fix this issue: https://github.com/g-truc/glm/pull/413

**Comment by Groovounet** [comment]
Thanks for submitting a pull request!

Christophe
