### ISSUE TITLE
detail/glm.cpp & detail/dummy.cpp

### ISSUE THREAD

**Issue by plasmacel** [g-truc/glm#433]
I have accidentally found two cpp files inside the detail folder: glm.cpp and dummy.cpp. dummy.cpp contains some basic stuff and structures for lights/materials. Are they part of the project and intended to be there? I mean glm is a header-only library, but if someone import the glm folder inside a project, then these cpp files will compile and create obj files to the output directory.

**Comment by Groovounet** [comment]
This is necessary for CMake to generate the unit test solution.

Thanks,
Christophe
