### ISSUE TITLE
GLM Include Error

### ISSUE THREAD

**Issue by Craytor** [g-truc/glm#434]
Hello!

I keep getting this error, and I have no clue what I'm doing wrong - or maybe it's a bug. When I try to compile my code I keep getting "type_half.inl" file not found. I've been dealing with this over the past 5 hours, and I can't figure out how to fix it.

Thanks

**Comment by Groovounet** [comment]
This issue was resolve here: https://github.com/jgh-/VideoCore/issues/209

**Comment by Craytor** [comment]
@Groovounet Oh my bad, forgot to close it.
