### ISSUE TITLE
define unary operator+ for glm types

### ISSUE THREAD

**Issue by plasmacel** [g-truc/glm#435]
glm types should define an overloaded unary operator+ to support the positive sign, which sometimes really improves the clarity and readability.

The simplest example of this is a lookup table with vector directions, like:

const vec2 axis_x(1, 0);
const vec2 axis_y(0, 1);
const vec2 LUT[4] = { - axis_x, + axis_x, - axis_y, + axis_y };

**Comment by Groovounet** [comment]
This is a bug. GLSL supports it so GLM should support it too.

Thanks for reporting!
Christophe

**Comment by Groovounet** [comment]
This bug has been fixed in master branch for GLM 0.9.8 release.

Thanks for contributing,
Christophe
