### ISSUE TITLE
Drop support for CMake 2.6

### ISSUE THREAD

**Issue by JesseTG** [g-truc/glm#439]
CMake 2.6 has long been unsupported.  My vote goes to CMake 3, personally.

**Comment by plasmacel** [comment]
yep

**Comment by Groovounet** [comment]
CMake 2.8 is required for https://drone.io/github.com/g-truc/glm

And then what dropping support for CMake 2.6 implies?

**Comment by JesseTG** [comment]
Really?  Huh.  Okay, 2.8, then.

As for dropping 2.6, it's just less you need to support.  Like a website dropping older versions of IE.

**Comment by Groovounet** [comment]
Typically the desire of dropping something is to require a feature. GLM cmake is super simple, it doesn't use features requiring newer versions of CMake so the request has no point.
