### ISSUE TITLE
unknown pragma warning in clang 3.8

### ISSUE THREAD

**Issue by plasmacel** [g-truc/glm#440]
`#pragma intrinsic(_BitScanReverse)`in func_integer.inl generates a lot of `unknown pragma ignored [-Wunknown-pragmas]` warning in Clang 3.8 (build r250698) from Visual Studio.

This is because when the `#if(GLM_COMPILER & GLM_COMPILER_VC)` preprocessor detects the presence of Visual Studio, it automatically assumes Visual C++ as the compiler:

    #if(GLM_COMPILER & GLM_COMPILER_VC)
    #include <intrin.h>
    #pragma intrinsic(_BitScanReverse)
    #endif

The issue probably affects another files too.

**Comment by Groovounet** [comment]
Ah yes support of Visual Studio Clang integration sounds good.

**Comment by Groovounet** [comment]
This issue should be fixed.

Thanks,
Christophe
