### ISSUE TITLE
vec1 type implicit scalar construction & conversion

### ISSUE THREAD

**Issue by plasmacel** [g-truc/glm#442]
`vec1` type currently doesn't support the implicit construction and conversion between the underlying scalar type. this causes several template metaprogramming and semantic problems:

1) they cannot be constructed by copy-list initializers, like other `vec` types

also mentioned in issue #252 

    template <class Vector>
    float func(Vector v);

    int main()
    {
        func<glm::vec1>(1.0); // error, no implicit constructor
        func<glm::vec1>({1.0}); // error, copy-list initialization cannot use an explicit constructor
        func<glm::vec2>({1.0, 2.0}); // it's ok
        func<glm::vec3>({1.0, 2.0, 3.0}); // it's ok
        func<glm::vec4>({1.0, 2.0, 3.0, 4.0}); // it's ok
    }

2) they represent the degenerate 1-dimensional (scalar) case, they support arithmetic operations with scalar types, yet they cannot be assigned from/to fundamental scalar types. this is semantically incorrect.

    using float1 = glm::vec1;

    float1 x(1.0f);
    float1 y = x + 3.0f; // it's ok, operations with scalar types are supported
    
    float s = 1.0f;
    float1 z = s; // error, no copy assignment for underlying scalar type
    s = static_cast<float>(z); // error, no conversion operator for underlying scalar type

3) issue #431 

fixing this issue automatically fixes issue #431 
the vec1 versions of length() and length2() will automatically accept scalar types

---

The issues can be fixed easily by removing the explicit keyword from the main constructor, and adding an implicit conversion operator. I will create a pull request soon.

**Comment by Groovounet** [comment]
At some point (years ago!) GLM used to have implicit constructors and conversion operators. It was a hell! Things casting all over the place resulting in calling the wrong code without noticing it or compiler error/warning.

I opened #252 because I think it's a problem to study but there are things like:
- func<glm::vec1>(1.0); // error, no implicit constructor
- the vec1 versions of length() and length2() doesn't accept scalar types
That is really want to keep. 

It might be semantically incorrect, I basically don't care. Automatically casting is very dangerous.

**Comment by plasmacel** [comment]
I agree that using implicit constructors and conversion operators on all the glm types would be a mess.

However glm::vec1 is really just a wrapper to handle scalar types by the common glm interface and functions. Even the memory layout of float and glm::tvec1<float> is generally the same, and if the operators are inlined (at most case they are), the generated code is also the same. I see no danger in it.

If you want to make initializer-list work, then you need an implicit constructor. All glm types have one implicit constructor with number of arguments matching the dimensionality. So vec1 should have too.
However, if you make an implicit constructor, then all functions that accept vec1 will implicitly accept a scalar too.

If you are not okay with it, maybe a macro definition like GLM_IMPLICIT_VEC1 to enable or disable this functionality solves this issue. An another, partial workaround would be the following: for any function accepting a vec1, we need an overload that will be dispatched for scalars only and will be static_asserted to false. Working example http://coliru.stacked-crooked.com/a/7bb822454f358e56
This will work on templated functions (like all glm functions), but non-template functions will continue to accept scalars (see the example). So the macro definition is maybe the best and most simple solution.

**Comment by Groovounet** [comment]
GLM_IMPLICIT_VEC1 sounds like a great idea. It will give the opportunity to test the feature without potentially breaking programs using GLM. Please add a test file too for vec1 with implicit cast.

Thanks! :)

**Comment by Groovounet** [comment]
No update on this bug for 6 months, closing.
