### ISSUE TITLE
glm::perspective takes radians

### ISSUE THREAD

**Issue by fordcars** [g-truc/glm#453]
Hi,
I am still new at glm and OpenGL, but while following a tutorial, I was troubled by the perspective function: it was taking radians? I looked online and didn't find an explanation to this :) I am not defining GLM_FORCE_RADIANS

Windows 7 Visual Studio 2010 Express

**Comment by Groovounet** [comment]
Hi,

Here is two links:
http://www.g-truc.net/post-0623.html
http://www.g-truc.net/post-0693.html

Thanks,
Christophe
