### ISSUE TITLE
Why no SIMD vec8? 

### ISSUE THREAD

**Issue by acterhd** [g-truc/glm#459]
Hello. I have one question. Why GLM have no SIMD optimized vec8? 
Also I want mat4x8 and mat8x4, both with SIMD. 

I made BVH builder, and need 8-cell for maximum speed of BVH builder. 
I already optimized for 4-cell SIMD of float.

**Comment by JesseTG** [comment]
Why not send a pull request?

**Comment by Groovounet** [comment]
Because nobody did it. Also, why would this be useful?

**Comment by acterhd** [comment]
I'm now working on 256bit vec8.

2015-12-07 1:44 GMT+08:00 Christophe R. <notifications@github.com>:

**Comment by acterhd** [comment]
I stopped working on 256 vectors and matrix, because very hard.

**Comment by Groovounet** [comment]
It sounds better to make a dedicated code for your problems. It's a lot less work!

**Comment by acterhd** [comment]
I'm sorry...

2015-12-07 2:33 GMT+08:00 Christophe R. <notifications@github.com>:

**Comment by Groovounet** [comment]
No need to be.
