### ISSUE TITLE
Different behavior between GLM 0.9.3.4 and GLM 0.9.6.3 ?

### ISSUE THREAD

**Issue by Flix01** [g-truc/glm#460]
Hi.

I had an old project (basically a skinning animation demo) that worked perfectly using GLM 0.9.3.4.
I ported it to GLM 0.9.6.3 (I had to change my code a bit to make it work): however now the result is very different (the final orientation of the skinned character is different).
When I switch back to the old version everything works as expected again.

The problem is that I can't "extract" a compact reproduction test case for it.
I wonder if this is a known behaviour, or there is some mistake on my side with the change in code.

P.S. I tried defining at the project level GLM_FORCE_PURE, but nothing changed.

I'm on Ubuntu 15.10 64bit.

**Comment by JesseTG** [comment]
> The problem is that I can't "extract" a compact reproduction test case for it.

Try.

**Comment by Flix01** [comment]
It will take ages!

**Comment by Groovounet** [comment]
http://www.g-truc.net/post-0693.html#menu ?

**Comment by ramassin** [comment]
I'd look at the functions taking an angle as an input, for the usual degrees vs radians input.
you can even try and define #define GLM_FORCE_RADIANS in the old project and test if it results in the same (bad) behaviour

**Comment by Flix01** [comment]
> you can even try and define #define GLM_FORCE_RADIANS in the old project and test if it results in the same (bad) behaviour

Done. Still works as expected.

**Comment by Flix01** [comment]
I'll never make it...

I was thinking that maybe it's a precision issue...
This is an example on how I split the code for the old and the new GLM versions (this particular function is one of a set of methods that is present in some math libraries [e.g. Ogre and Geometric Tools]):
```c++
#ifndef USE_OLD_GLM
    template <typename Real,precision prec=highp> GLM_INLINE void FromEulerXYZ (tmat3x3<Real,prec>& m,Real fYAngle,Real fPAngle,
                                                Real fRAngle,bool useAxisConventionOpenGL=true)
    {
        Real fCos, fSin;

        fCos = cos(fYAngle);
        fSin = sin(fYAngle);
        tmat3x3<Real,prec> kXMat(1.0,0.0,0.0,0.0,fCos,-fSin,0.0,fSin,fCos);

        fCos = cos(fPAngle);
        fSin = sin(fPAngle);
        tmat3x3<Real,prec> kYMat(fCos,0.0,fSin,0.0,1.0,0.0,-fSin,0.0,fCos);

        fCos = cos(fRAngle);
        fSin = sin(fRAngle);
        tmat3x3<Real,prec> kZMat(fCos,-fSin,0.0,fSin,fCos,0.0,0.0,0.0,1.0);

        if (useAxisConventionOpenGL)    m = kXMat*(kYMat*kZMat);
        else                            m = kZMat*kYMat*kXMat;
    }
#else //USE_OLD_GLM
    template <typename Real> GLM_INLINE void FromEulerXYZ (detail::tmat3x3<Real>& m,Real fYAngle,Real fPAngle,
                                                Real fRAngle,bool useAxisConventionOpenGL=true)
    {
        Real fCos, fSin;

        fCos = cos(fYAngle);
        fSin = sin(fYAngle);
        detail::tmat3x3<Real> kXMat(1.0,0.0,0.0,0.0,fCos,-fSin,0.0,fSin,fCos);

        fCos = cos(fPAngle);
        fSin = sin(fPAngle);
        detail::tmat3x3<Real> kYMat(fCos,0.0,fSin,0.0,1.0,0.0,-fSin,0.0,fCos);

        fCos = cos(fRAngle);
        fSin = sin(fRAngle);
        detail::tmat3x3<Real> kZMat(fCos,-fSin,0.0,fSin,fCos,0.0,0.0,0.0,1.0);

        if (useAxisConventionOpenGL)    m = kXMat*(kYMat*kZMat);
        else                            m = kZMat*kYMat*kXMat;
    }
#endif //USE_OLD_GLM
```
As you can see, in the new code I had to specify the precision (prec=highp): so maybe that can break symmetry...

I got tons of methods like that!

Or maybe there's some difference in the default initialization of some struct...

I guess I'll never sort it out... 

... but I can keep using the old version :)

**Comment by Flix01** [comment]
I've probably found the solution.

Basically: <b>glm::perspective(...)</b> now takes radians instead of degrees (breaking the compatibility with the old-school glu function <b>gluPerspective(...)</b>).

However it's still not 100% solved: the camera looks nearer with the newer version.
I've checked the first three decimals in the perspective matrix and they're the same...
I don't know... maybe I should check further decimals, or look for something in other methods...

<b>P.S.</b> <b>*GLM_FORCE_RADIANS*</b> in the old project didn't seem to correct this.
However @ramassin was right: I should have checked better!

**Comment by Groovounet** [comment]
GLM_FORCE_RADIANS was introduced in 0.9.4.

If you follow http://www.g-truc.net/post-0693.html, GLM will point you all the places you need to update in your code thanks to a compiler warning.

**Comment by Flix01** [comment]
@Groovounet 
Thanks for the link! I really need it!
