### ISSUE TITLE
[bug] 64-bit integer constants on x86 ~ glm/gtc/bitfield.inl 

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [g-truc/glm#463]
Versions: 0.9.7.1 (bitfield.inl),  0.9.5.4 (bit.inl)
Compiler: gcc 4.1 (fails both versions), gcc 4.8.3 (succeed both versions)

Tried to compile tests on x86, got this

` glm/./gtx/bit.inl:551: error: integer constant is too large for 'long' type `

Constants like 0xFFFF00000000FFFF is 64 bits long, which is allowed in C++11 only. 
Relatively new GCC just gives a warning, but old versions of GCC can't compile it, showing an error.

Maybe adding ULL to the constants can help (0xFFFF00000000FFFFULL). Didn't test, though.

**Comment by Groovounet** [comment]
Do you have a fix suggestion? 
GCC support a 64 bits extensions which is so useful GLM requires it.

GCC 4.1 is not supported anymore by GLM. GCC 4.6 generates warnings too: https://drone.io/github.com/g-truc/glm/latest

Currently GLM requires at least GCC 4.2 but I guess if there is issues with GCC 4.2, I'll rather rise the GCC version requires than hack away 64 bits support.

Thanks,
Christophe
