### ISSUE TITLE
Trouble converting from quaternion to euler angles and back

### ISSUE THREAD

**Issue by tylorr** [g-truc/glm#464]
I have a quaternion that I would like to convert to euler angles, display to the user, and let them edit it, then take the new euler angle and convert back to quaternion. But I am experiencing some problems when the euler y angle passes +/-90 degress. 

The problem boils down to something like below
```
glm::quat rotation;
...
// Each frame:
auto euler = degrees(eulerAngles(rotation)); // I have force radians turned on
euler.y += 1.0f;
rotation = glm::quat{radians(euler)};
```
I get different results depending on what machine I use which is odd as well. On my desktop when the y angle reaches 90 degrees the rotation locks in place and vibrates slightly.

On my laptop the rotation changes significantly over a few frames then settles on a sequence where a positive change in the y angle, when converted to quaternion and back, results in a negative change on the z angle.

I would like to avoid eulers if possible but as far as I know there is no better way to display rotations so that a human can easily understand and adjust. As far as I am aware the Unity3D game engine is doing something similar to what I am so I know it is possible. If there is a better way to do this let me know.

**Comment by sippeangelo** [comment]
Might be related to #461?

**Comment by tylorr** [comment]
#461 may have been the problem happening on my laptop and I haven't checked that yet. But I think I discovered what is happening on my desktop.

If I take a euler `(0, y, 0)` where `x > 90` and I convert it to a quaternion and back I get an euler of the form `(180, 180 - y, 180)`. A positive increase in the new y angle is actually the opposite rotation than before causing the rotation to flip back and forth across the 90 degree rotation on y, kind of locking it in place.

As I understand it, there are two euler values to represent each rotation. Is there an easy way to determine that I got the other euler than what I was expecting?

**Comment by tylorr** [comment]
I guess this may not be the right place to ask this question, it's more of a generic math question.
