### ISSUE TITLE
Non trivially copyable instantiations

### ISSUE THREAD

**Issue by nkyriazis** [g-truc/glm#465]
Understandably, GLM targets scalar instantiations of its templated types. Therefore, this issue might be of limited interest.

If a type with non-trivial copy constructor is used to instantiate e.g. glm::tvec4, then, in MSVC2013, the following compilation error occurs:

```
Error 1 error C2621: 'glm::tvec4<std::string,0>::data' : illegal union member; type 'XXX' has a copy constructor glm\glm\detail\type_vec4.hpp 143
```

A simple example to reproduce this error:

```cpp
#include <glm/glm.hpp>
#include <string>

void test()
{
    glm::tvec4<std::string> vec;
}
```

There is little reason behind using a string as a scalar, but this serves only as an example. In general (but also in my case) one might want to use complex scalar representations, which generates an error [here](https://github.com/g-truc/glm/blob/master/glm/detail/type_vec4.hpp#L143).

This is a type-dependent issue, so it seems appropriate to treat it with type-dependent compile-time selection of storage. E.g. typedef or derive storage as a function of type T.

**Comment by Groovounet** [comment]
Erm, I don't really understand the issue. GLM types only accept basic typenames: float, integer and bool and that it.

Thanks,
Christophe
