### ISSUE TITLE
Strict Aliasing (again)

### ISSUE THREAD

**Issue by Philip-Trettner** [g-truc/glm#473]
Basically the same problem as in #152 (though I didn't want to revive a 2-year-old thread).

gcc version 4.9.2 (Debian 4.9.2-10)
Flags: -O3 -std=c++11 -Wall -Werror

`error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   return reinterpret_cast<uint64 const &>(Topack);`
in `gtc/packing.inl` lines `{468, 473, 494, 499, 524, 529}` using Release 0.9.7.2 (head of master as of writing this).

I would like to propose a fix, but unfortunately, I'm not sure how to do this without undefined behavior (bye bye, access-through-union) and without copying (bye bye, memcpy).

**Comment by spartan-117** [comment]
I have the same error for version 0.9.7.4

Regards

**Comment by bcrist** [comment]
`memcpy` is the proper way to avoid strict aliasing.  Compilers are generally quite good at eliding memcpys when used in this way.

That said, I'm not sure GLM has ever officially supported strict aliasing rules, and there are probably other violations elsewhere.

**Comment by Philip-Trettner** [comment]
Thanks for the information.

Because I don't trust random "generally quite good" statements regarding compilers, I went ahead and tested it: https://godbolt.org/g/ZUatqF

Result: works like a charm. memcpy is so built-in that it doesn't even show as a function call in O0.

(With O0 the memcpy variant is still one or two instructions longer than the cast but starting with O1, they are both the same under reasonably modern gcc and clang)

**Comment by Groovounet** [comment]
Thanks for the test. I double check for Clang, Visual C++ and ICC: Only ICC doesn't do a good job. I'll update the code to use memcpy.

**Comment by Groovounet** [comment]
This issue should be fixed in master branch for GLM 0.9.8 release.

Thanks for contributing,
Christophe
