### ISSUE TITLE
rotation(orig, dest) confusion 

### ISSUE THREAD

**Issue by janspisiak** [g-truc/glm#494]
Hey,
first, thank you for your work on this great library.
Using (ver. 0.9.7.2):
`rot = rotation(orig, dest);`
You get:

```
dest == orig * rot;
dest == - rot * orig;
```

I am confused, because usually you see `quat * vec`, but it seems that rotation() implies `vec * quat` is expected. I might be wrong or confused, I haven't spent too much time with quaternions. Is this an issue, or should I just get used to `vec * quat`?
Thanks, again :)

**Comment by AntonyML** [comment]
The question is old but there is no answer yet. Here's my answer :) :

We got: 
```
quat Q1;
vec V1;
```
So:
```
Q1 * V1 != V1 * Q1
Q1 * V1 == V1 * Q1.inverse()
Q1.inverse() * V1 == V1 * Q1
```

Am I wrong?

**Comment by Groovounet** [comment]
I didn't read understand the question but at least what @Hokbras says is correct or at least expected from GLM.

Thanks,
Christophe
