### ISSUE TITLE
Preprocessor definition GLM_PLATFORM_CYGWIN is referenced in GLM code but not defined

### ISSUE THREAD

**Issue by zapolnov** [g-truc/glm#495]
In file `detail/setup.hpp` there is a code (near line 69):

```
#elif defined(__CYGWIN__)
#	define GLM_PLATFORM GLM_PLATFORM_CYGWIN
```

And constant `GLM_PLATFORM_CYGWIN ` is also referenced in other parts of the GLM code.

But there is no definition of this constant. This causes MSVC compiler to report warning 4668 (if enabled):
```
glm\glm\detail\setup.hpp(648): warning C4668: 'GLM_PLATFORM_CYGWIN' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```

**Comment by Groovounet** [comment]
This issue is fixed in master branch and 0.9.7 branch for GLM 0.9.7.4 release.

Thanks for contributing!
