### ISSUE TITLE
error : 'highestBitValue' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

### ISSUE THREAD

**Issue by Maddius** [g-truc/glm#503]
Looks like `round.inl` is missing a `#include "../gtx/bit.hpp"` - I get this when calling `glm::roundPowerOfTwo`

Let me know if you need any more information.

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.7 branch for GLM 0.9.7.5 release.

Thanks for contributing!
