### ISSUE TITLE
CUDA compiler error in type_vec4.inl

### ISSUE THREAD

**Issue by dasmysh** [g-truc/glm#504]
After commit [1becd76c5f6370d390c96ac523a6dffd7356a80f](https://github.com/g-truc/glm/commit/1becd76c5f6370d390c96ac523a6dffd7356a80f) a compiler error occurs in type_vec4.inl when used in a CUDA source file.

CUDA Version: 7.5
C++ Compiler: Visual C++ 2013
Error: `glm\detail\type_vec4.inl(1183): fatal error C1017: invalid integer constant expression`

**Comment by Groovounet** [comment]
Any idea what's cause the build error? The line looks good to me.

Could you declare #define GLM_MESSAGES before including GLM and report what the compiler says?

Thanks,
Christophe

**Comment by dasmysh** [comment]
Unfortunately GLM_MESSAGES (or any user defined pragma messages) do not show if there are any compiler errors in VC++. The error also occurs in multiple other files that contain a similar #if #endif structure at the end.

To my understanding the first condition should not be
`GLM_ARCH != GLM_FORCE_PURE`
but
`GLM_ARCH != GLM_ARCH_PURE`
to make this work again.

**Comment by dasmysh** [comment]
I changed this locally and it works fine for me. I do not have the glm tests running so i'm a bit reluctant to commit.

**Comment by Groovounet** [comment]
ohhhh! stupid mistake, too on my face to see it!

This issue should be fixed in master branch, thanks for reporting!
