### ISSUE TITLE
with GLM_FORCE_INLINE defined glm::to_string template cannot be used

### ISSUE THREAD

**Issue by afoksha** [g-truc/glm#506]
Sometimes it is good to print variable values to see what they are, but then GLM_FORCE_INLINE
has to be disabled.

I think it make sense to declare glm::to_string without inlining directive, as input/output operations are slow anyway. Then all the computation routines will be inlined and at the same time variables could be printed.

This is more of a suggestion, than an issue.

==============================================================
BTW, awesome library -- very nice and intuitive syntax. A lot of useful functions. Explicit access to members without annoying setters and getters crap, inlining + no constructor init if needed.

**Comment by regnirpsj** [comment]
are you aware of `glm/gtx/io.hpp`?

**Comment by afoksha** [comment]
Thanks for pointing out, sir.

Getting glm::to_string compilable with GLM_FORCE_INLINE defined makes sence anyway.

**Comment by Groovounet** [comment]
This was actually an issue that should be fixed in GLM 0.9.7.5 release. Thanks for reporting!
Christophe
