### ISSUE TITLE
r-value operator overloads

### ISSUE THREAD

**Issue by Alicemargatroid** [g-truc/glm#507]
I noticed that there are not overloads for operations that take r-value references, nor for overloading on r-value this. These could help significantly speed up long equations with lots of temporaries, and could be enabled for only C++11 compliant compilers via GLM_HAS_RVALUE_REFERENCES.

**Comment by Groovounet** [comment]
I think I need more detail to understand what this is and what it's supposed to do on specific cases. (And I don't care enough to search on my own. :p)

**Comment by Groovounet** [comment]
No update so closing.
