### ISSUE TITLE
length of vec2 always return 2

### ISSUE THREAD

**Issue by Discordia** [g-truc/glm#508]
A dvec2 set to different x,y always returns two, I was expecting it to be sqrt(x*x + y*y). Debugging shows that it is using this method on lines 100-104: https://github.com/g-truc/glm/blob/master/glm/detail/type_vec2.inl and it is implemented as just "return 2;". 

Doc is here: http://glm.g-truc.net/0.9.4/api/a00131.html#ga282360c8bb80b80d3c7f5bc00766d873

**Comment by adrianbroher** [comment]
`dvec2::length_type dvec2::length()` returns the number of elements within the the vector.

The function you linked returns the length of the vector (magnitude) and takes the vector as an input parameter.


For example:

```c
glm::dvec2 the_vector(3,5);

size_t number_of_elements = the_vector.length(); // 2
double magnitude = glm::length(the_vector); // ≈ 5.83
```

**Comment by Raikiri** [comment]
in my opinion, this is really quite bad/counter-intuitive design. should have used a different method name, components_count or something like that instead.
