### ISSUE TITLE
error in GLM_HAS_CXX11_STL macro

### ISSUE THREAD

**Issue by philip-hodgson** [g-truc/glm#510]
The GLM_HAS_CXX11_STL macro needs an extra pair of brackets around the compiler flags like this:

    #define GLM_HAS_CXX11_STL ((GLM_LANG & GLM_LANG_CXX0X_FLAG) && (\
		((GLM_COMPILER & GLM_COMPILER_GCC) && (GLM_COMPILER >= GLM_COMPILER_GCC48)) || \
		((GLM_COMPILER & GLM_COMPILER_VC) && (GLM_COMPILER >= GLM_COMPILER_VC2013)) || \
		((GLM_COMPILER & GLM_COMPILER_INTEL) && (GLM_COMPILER >= GLM_COMPILER_INTEL15))))

As it is written it says (CXX0X && GCC) || VC || INTEL not CXX0X && (GCC48 || VC || INTEL)

**Comment by Groovounet** [comment]
This issue is fixed for GLM 0.9.7.6 release. Thanks for contributing!
Christophe
