### ISSUE TITLE
Replace headers with Simd headers?

### ISSUE THREAD

**Issue by rahulchaphalkar** [g-truc/glm#513]
I have a code base which uses an older version of Glm library without Simd support added. Is the newly added simd support backward compatible? i.e do i need to rewrite the code to make use of the Simd functionality, or do I just need to replace some of the headers?

**Comment by Groovounet** [comment]
So were you using simdVec4 stuff? 

This is going to be deprecated in GLM 0.9.8 and removed in GLM 0.9.9. For the new simd support, you should be able to use typically GLM types (vec4, mat4).

You should be able to do something like:
```
#define GLM_FORCE_ALIGNED
typedef glm::vec4 simdVec4;
```
And it should almost work out of the box. 

SIMD instructions require vec4 to be 16 bytes aligned which will imply:

```
#define GLM_FORCE_ALIGNED
struct S
{
   int I;
  vec4 v;
};
static_assert(sizeof(S) == 32, "vec4 isn't 16 bytes aligned");
```

```
struct S
{
   int I;
  vec4 v;
};
static_assert(sizeof(S) == 20, "vec4 isn't packed");
```

In GLM 0.9.8, there will be aligned_vec4 and packed_vec4 to differential both behavior explicitly.

Keep in mind that this work is still work in progress in master branch for GLM 0.9.8.

Thanks,
Christophe
