### ISSUE TITLE
type_mat4x4_simd.inl empty?

### ISSUE THREAD

**Issue by rahulchaphalkar** [g-truc/glm#515]
My project is unable to get the simd intrinsics for mat4x4 type (vec4 is working fine), and after looking at the control path i'm wondering if this is because there is no data in type_mat4x4_simd.inl file? The corresponding type_vec4_simd.inl has intrinsics in it. Is there a substitute file to be used in place of type_mat4x4_simd.inl ?

**Comment by Groovounet** [comment]
Hi,
My felling is that that replace you version of GLM with but the copy didn't go well mixing multiple version of GLM files.
I saw this issue a few times.
Thanks,
Christophe
