### ISSUE TITLE
mat3 to mat4

### ISSUE THREAD

**Issue by julapy** [g-truc/glm#522]
hi,

i have a mat3 and need to decompose it so i can lerp or tween to another mat3.
my understanding is that i first need to decompose a matrix and lerp individual components such as translation, rotation etc, and then combine these back into the matrix after lerping.

i can see that glm supports the decomposition of a mat4 but not mat3.

so i started looking into ways of converting a mat3 into a mat4 which would then allow me to decompose it.
passing a mat3 into a mat4 constructor wasn't giving me the correct result,
so what ive done is this.
```
        glm::mat3 m3 = node->getTransform();
        glm::mat4 m4(m3[0][0], m3[0][1], 0, 0,
                     m3[1][0], m3[1][1], 0, 0,
                     0,        0,        1, 0,
                     m3[2][0], m3[2][1], 0, 1);
```

my questions are,
is the above correct?
is there a better way to decompose a mat3?
or is there a better way to convert a mat3 to a mat4 and then pass it to `glm::decompose`?

cheers.

**Comment by Groovounet** [comment]
It doesn't look like you have been lucky here. My suggestion would be to ask on StackExchange with usin GLM tag: http://stackoverflow.com/questions/tagged/glm

Thanks,
Christophe
