### ISSUE TITLE
Fixed-point math

### ISSUE THREAD

**Issue by ddovod** [g-truc/glm#525]
Hello guys.
Cannot find any info, so asking here.

Is there any plans to implement good/fast/robust/etc fixed-point math functions/operators and corresponding types? 

Thanks a lot!

**Comment by Groovounet** [comment]
Hi,

There isn't any plans for fixed point arithmetic, pull request welcome!

Thanks,
Christophe

**Comment by ddovod** [comment]
I got it, thank you!
