### ISSUE TITLE
Provide projection matrices implementation for both left-handed and right-handed coordinate systems.

### ISSUE THREAD

**Issue by jpvanoosten** [g-truc/glm#53]
Provide functions to build both left-handed and right-handed projection matrices (both orthographic and perspective projections).

Provide functions for building view matrices using LookAt for both left-handed and right-handed coordinate systems.

This would make this library useful for both OpenGL and DirectX applications (or OpenGL applications with a left-handed coordinate system!).

**Comment by JesseTG** [comment]
Since `GLM_LEFT_HANDED` is now a thing, can this be closed?
