### ISSUE TITLE
mac os X 10.10.5 sample of GLM core compilation issue

### ISSUE THREAD

**Issue by nyotis** [g-truc/glm#531]
<img width="1084" alt="screen shot 2016-07-26 at 21 04 02" src="https://cloud.githubusercontent.com/assets/658719/17151684/c71cb21e-5374-11e6-87bb-200651bc4e47.png">
<img width="964" alt="screen shot 2016-07-26 at 21 03 26" src="https://cloud.githubusercontent.com/assets/658719/17151686/ca35a352-5374-11e6-9fcb-e33ff69c3de4.png">

**Comment by amc522** [comment]
You are trying to create a 3 dimensional rotation matrix about a 2 dimensional axis. This doesn't really make sense. You are trying to call the following:

`glm::rotate(const glm::mat4&, const float&, const glm::vec2&)`

The rotation function signature looks like this:

`glm::rotate(const glm::mat4&, const float&, const glm::vec3&)`

Note that it takes a 3 dimensional axis in which the rotation is applied. Are you trying to create a first person style camera?

**Comment by nyotis** [comment]
I just tried to run the sample code provided by Christophe - cannot spot the link right now, that's all

**Comment by amc522** [comment]
You can find the most up to date samples here [http://glm.g-truc.net/0.9.7/code.html](http://glm.g-truc.net/0.9.7/code.html). The second sample looks like the one you were trying to use.

**Comment by Groovounet** [comment]
@amc522 is right. GLM matrix transform functions only support 3D not 2D. So the call is not valid.

Thanks,
Chirstophe

**Comment by nyotis** [comment]
I am just trying to figure out how this works

@Groovounet _GLM matrix transform functions only support 3D not 2D_

why then you provide a sample where the matrix transform (second example) accepts a 2D rotation [http://glm.g-truc.net/0.9.7/code.html](url)
same thing with the camera [http://glm.g-truc.net/0.9.7/index.html](url)

**Comment by nyotis** [comment]
the example that fails compiling is contained in your latest documentation - the 3rd parameter to `glm::rotate` is clearly 2D (`glm::vec2& up`)

<img width="816" alt="screen shot 2016-08-06 at 17 02 17" src="https://cloud.githubusercontent.com/assets/658719/17457409/bb2503fe-5bf7-11e6-9318-9421c9b52fe1.png">

**Comment by nyotis** [comment]
so I guess there is an error in your docs substituting 

`glm::mat4 transform(glm::vec2 const & Orientation, glm::vec3 const & Translate, glm::vec3 const & Up)`
with
`glm::mat4 transform(glm::vec2 const & Orientation, glm::vec3 const & Translate, glm::vec3 const & Up)
`
compiles fine

**Comment by amc522** [comment]
Did not realize you were talking about the generated documentation included in the repository. Sorry about that. The use of glm::vec2 for the 'Up' parameter is indeed a typo. This is a fairly easy fix. Thanks for pointing it out.

**Comment by Groovounet** [comment]
This issue has been fixed for the manual of GLM 0.9.8 and master branches.

Thanks for reporting,
Chirstophe
