### ISSUE TITLE
Normal Storage

### ISSUE THREAD

**Issue by adishavit** [g-truc/glm#533]
I've got a huge model with lots of normals. Currently I store them as `vec3`. However, being normalized normals, they really only have 2 free variables and can be stored losslessly as `vec2` (e.g. just `x` and `y`, or using polar angles only).

Is there a (better or) recommended way to losslessly store such length 1 normals?

**Comment by Groovounet** [comment]
a vec2 storing only x and y sounds great. Maybe you can afford  loosing precision and sorting int16 for each component. int16 would give you better precision than half because the exponent is fixed with normalized normals.

**Comment by amc522** [comment]
I know this issue is closed, but this blog might help.
[http://aras-p.info/texts/CompactNormalStorage.html](http://aras-p.info/texts/CompactNormalStorage.html)
I've used this as a starting point for my gbuffers before.
