### ISSUE TITLE
Wrap functions using non existant members

### ISSUE THREAD

**Issue by adishavit** [g-truc/glm#534]
The function [`repeat`, `mirrorRepeat` and `clamp`](https://github.com/g-truc/glm/blob/316460408a5ef0338029a7c8f387ac49a2f1561c/glm/gtx/wrap.inl) use API calls - `tvecX<T, P>::size_type` and `tvecX<T, P>::value_size()` - that do not exist:
```
...
for(typename tvec2<T, P>::size_type i = 0; i < tvec2<T, P>::value_size(); ++i)
...
```

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.8 and master branches.

Thanks for reporting,
Christophe
