### ISSUE TITLE
glm::quat from euler angles in constructor gives wrong  transform

### ISSUE THREAD

**Issue by sasmaster** [g-truc/glm#535]
I am not sure if it is a bug in glm:quat,but after spending several hour on it I would like to share the problem here:
So I want to init quaternion from euler angles.The glm::quat has a constructo into which it accepts glm::vec3() which contains euler angles.
Now,my reference of correct transforms is Unity3D.
The transform looks wrong if I pass into quaternion all 3 axis like this:

`glm::quat quat1 = gml::quat(glm::vec3(y,x,z));//where y,x,z are euler angles ,`

I also tried different order of roll,pitch,yaw ,same problem.

What I found working is this:

```
  glm::quat qPitch = glm::angleAxis(x, glm::vec3(1, 0, 0));
  glm::quat qYaw =  glm::angleAxis(y, glm::vec3(0, 1, 0));
  glm::quat qRoll = glm::angleAxis(z, glm::vec3(0, 0, 1));
 
///x,y,z are in radians
  glm::quat rotQuat = qYaw *qPitch * qRoll;
```

The chuck above results in correct transformation.I do have to negate the X and Y angles but that's due to Unity's left handed coordinate system.So my question is:Do I misuse the quat contructor,or maybe there is a bug?

**Comment by Groovounet** [comment]
Hi,

According to the documentation:
> 		/// Build a quaternion from euler angles (pitch, yaw, roll), in radians.
> 		GLM_FUNC_DECL GLM_EXPLICIT tquat(tvec3<T, P> const & eulerAngles);

So my understanding is that you should invert your x and y and it should just work.

Thanks,
Christophe

**Comment by jonomango** [comment]
Hey, I know this is a closed issue but I seem to be having the same problem... According to the glm documentation:
```
/// Build a quaternion from euler angles (pitch, yaw, roll), in radians.
GLM_FUNC_DECL GLM_EXPLICIT qua(vec<3, T, Q> const& eulerAngles);
```
However in actual use the pitch and yaw seem to be swapped? According to my understanding, pitch is responsible for the rotation around the y-axis and yaw is for the rotation around the x-axis. Taking this into consideration, this code:
```
glm::axis(glm::dquat{ glm::dvec3{ 1.0, 0.0, 0.0 } })
```
should produce
```
{ 0.0, 1.0, 0.0 }
```
yet instead it produces
```
{ 1.0, 0.0, 0.0 }
```
as if the x and y were switched around. My question is this: is this the correct outcome and I'm just overlooking some common convention or is this a design flaw?
