### ISSUE TITLE
Function proposition: Add Function lowestBitValue

### ISSUE THREAD

**Issue by Robert42** [g-truc/glm#536]
We've already got a function `highestBitValue`

	template <typename genIUType>
	GLM_FUNC_QUALIFIER genIUType highestBitValue(genIUType Value)
	{
		genIUType tmp = Value;
		genIUType result = genIUType(0);
		while(tmp)
		{
			result = (tmp & (~tmp + 1)); // grab lowest bit
			tmp &= ~result; // clear lowest bit
		}
		return result;
	}

I think an additional function lowestBitValue might be also useful for users (I needed it when using an bitfield as set, and I wanted to iterate over it)

	template <typename genIUType>
	GLM_FUNC_QUALIFIER genIUType lowestBitValue(genIUType Value)
	{
		return (Value & (~Value + 1)); // grab lowest bit
	}

	template <typename genIUType>
	GLM_FUNC_QUALIFIER genIUType highestBitValue(genIUType Value)
	{
		genIUType tmp = Value;
		genIUType result = genIUType(0);
		while(tmp)
		{
			result = lowestBitValue(tmp); // grab lowest bit
			tmp &= ~result; // clear lowest bit
		}
		return result;
	}

**Comment by Groovounet** [comment]
This feature has been added in GLM 0.9.8 for GLM 0.9.8.0 release.

Thanks for reporting,
Christophe
