### ISSUE TITLE
"GLM_COMPILER_LLVM" in setup.hpp:266 should be "GLM_COMPILER_CLANG"

### ISSUE THREAD

**Issue by FengLinqing** [g-truc/glm#537]
as mentioned in readme.md: "Factorized GLM_COMPILER_LLVM and GLM_COMPILER_APPLE_CLANG into GLM_COMPILER_CLANG"

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.8 branch. Thanks for reporting!
Christophe
