### ISSUE TITLE
quat*quat Result error

### ISSUE THREAD

**Issue by chinayangxiaowei** [g-truc/glm#538]
//http://cn.mathworks.com/help/aeroblks/quaternionmultiplication.html?requestedDomain=www.mathworks.com

	w = l(0)*r(0) - l(1)*r(1) - l(2)*r(2) - l(3)*r(3)
	x = l(0)*r(1) + l(1)*r(0) - l(2)*r(3) + l(3)*r(2)
	y = l(0)*r(2) + l(1)*r(3) + l(2)*r(0) - l(3)*r(1)
	z = l(0)*r(3) - l(1)*r(2) + l(2)*r(1) + l(3)*r(0)

	w = l.w*r.w - l.x*r.x - l.y*r.y - l.z*r.z
	x = l.w*r.x + l.x*r.w - l.y*r.z + l.z*r.y
	y = l.w*r.y + l.x*r.z + l.y*r.w - l.z*r.x
	z = l.w*r.z - l.x*r.y + l.y*r.x + l.z*r.w

`
//result = D3DXQuaternionMultiply
void QuatMultiply(const glm::quat& l, const glm::quat& r, glm::quat* dst)
{
	float d1, d2, d3, d4;
	float x, y, z, w;

	//w = l.w*r.w - l.x*r.x - l.y*r.y - l.z*r.z
	d1 = l.w*r.w;
	d2 = -l.x*r.x;
	d3 = -l.y*r.y;
	d4 = -l.z*r.z;
	w = d1 + d2 + d3 + d4;

	//x = l.w*r.x + l.x*r.w - l.y*r.z + l.z*r.y
	d1 = l.w*r.x;
	d2 = l.x*r.w;
	d3 = -l.y*r.z;
	d4 = l.z*r.y;
	x = d1 + d2 + d3 + d4;

	//y = l.w*r.y + l.x*r.z + l.y*r.w - l.z*r.x
	d1 = l.w*r.y;
	d2 = l.x*r.z;
	d3 = l.y*r.w;
	d4 = -l.z*r.x;
	y = d1 + d2 + d3 + d4;

	//z = l.w*r.z - l.x*r.y + l.y*r.x + l.z*r.w
	d1 = l.w*r.z;
	d2 = -l.x*r.y;
	d3 = l.y*r.x;
	d4 = l.z*r.w;
	z = d1 + d2 + d3 + d4;

	dst->w = w;
	dst->x = x;
	dst->y = y;
	dst->z = z;
}`

**Comment by Groovounet** [comment]
Hi,

What's the error here? I just double checked quaternions seems to work fine for me.

Thanks,
Christophe
