### ISSUE TITLE
CUDA compiler error in type_vec.hpp

### ISSUE THREAD

**Issue by dasmysh** [g-truc/glm#539]
When I try to use glm in CUDA I get some compile errors:

CUDA Version: 7.5
C++ Compiler: Visual C++ 2013
Errors:
`glm/detail/type_vec.hpp(23): error : constant "size" is not a type name`
`glm/detail/type_vec.hpp(23): error : expected a ";"`

It seems like the structure alignment used for CUDA (`__attribute__((aligned(X)))`) is not supported by CUDA. I hope I can find a fix to this and post it here.

**Comment by Groovounet** [comment]
What version of GLM are you using?

**Comment by dasmysh** [comment]
Oh, sorry forgot the version. I'm using the current master branch.

So currently I found several problems:
- in `glm/detail/setup.hpp` lines 574ff:
The correct attribute for alignment is platform dependent. There is an __align__(X) defined in the CUDA headers one could use. Adding a fourth ifdef case here will fix this.
- it seems like CUDA does not support template parameters for the alignment. I did not find a way around that.

**Comment by Groovounet** [comment]
Ok, another Cuda compiler bug... I think I have a workaround. :/ I'll push the fix in a couple of minutes. :)

**Comment by dasmysh** [comment]
Thanks.

**Comment by Groovounet** [comment]
This issue should be fixed by commit https://github.com/g-truc/glm/commit/09bf19db7e1f4ae82a8d7282b03eda00dbf770aa (sorry forgot to write the issue number in the commit message) in GLM 0.9.8 and master branch.

Thanks for letting me know whether this is resolving your problem,
Christophe

**Comment by dasmysh** [comment]
There is still a small error in the fix.
in file `glm/detail/type_vec.hpp(21)`:
replace
`#	if GLM_COMPILER & GLM_COMPILER_CUDA`
by
`#	if !(GLM_COMPILER & GLM_COMPILER_CUDA)`

**Comment by dasmysh** [comment]
Ok seems I was wrong from the beginning. This might not be a CUDA problem but a problem with Visual C++. Now that my CUDA code compiles I get the same errors for my non-CUDA code.
So maybe someone should check if this error actually exists when compiling with clang/gcc + CUDA.

**Comment by Groovounet** [comment]
Ah... I think there were a problem with Cuda actually and I have a better and actual fix. Maybe there is something else... investigating.

**Comment by Groovounet** [comment]
I pushed a new commit that would preserve the functionalities on Cuda and which is probably less disruptive. Do you care to give it a try?

**Comment by dasmysh** [comment]
Sorry. Had to leave work. I will try tomorrow morning. I had a look at the commit but I think it won't work.  This is probably a problem with the Visual C++ compiler (see http://stackoverflow.com/questions/388934/aligning-member-variables-by-template-type).

**Comment by dasmysh** [comment]
Just tested it. The errors above are solved but there is a new one as I expected. The current code uses the correct way to declare the alignment but the Visual C++ 2013 compiler does not support the alignment as template parameters.

New error message:
`glm/detail/type_vec.hpp(23): error C2059: syntax error: 'token'`

Should I open another issue for this?

**Comment by Groovounet** [comment]
Ah, I could reproduce the problem... I'll try workarounds. Almost surprising nobody reported it before. I guess it's holidays time!

**Comment by Groovounet** [comment]
This issue should be fixed (again! :D) in master and 0.9.8 branch. The workaround you suggested workaround just fine with the right magic applied.

Thanks for contributing,
Christophe
