### ISSUE TITLE
incorrect projection matrix with glm::perspectiveFov

### ISSUE THREAD

**Issue by bagobor** [g-truc/glm#55]
may be i'm wrong but:
		glm::mat4 proj = glm::perspective(45.0f, 1.0f, 0.1f, 3.0f);
		glm::mat4 proj = glm::perspectiveFov(45.0f, 128.0f, 128.0f, 0.1f, 3.0f);

result in (image)
![glm_perspectiveFov_bug](https://f.cloud.github.com/assets/708235/212703/de83f752-8328-11e2-9a3b-20b4378c9b36.png)

**Comment by JesseTG** [comment]
Has this been fixed yet?

**Comment by Groovounet** [comment]
This bug is still active.

**Comment by JesseTG** [comment]
Ah, OK, no problem

**Comment by Groovounet** [comment]
I doubled check this issue is fixed.
