### ISSUE TITLE
glm 0.9.8  vec4 as input param not showing in debugger

### ISSUE THREAD

**Issue by giordi91** [g-truc/glm#551]
Hi I am having some problem with visual studio 2015, is not the uber latest, I might be a sub version of two behind.

I had problem where any of the vec4 would not show the values in the debugger (just crap), i found this:
https://github.com/g-truc/glm/issues/288
Updated and now the ones created in the body of the function works. The one incoming as input parameter doesnt.

For example  if I try to debug void myFunc(vec4 input)

input would not show properly, althouhg if i do:

vec4 debug_input = input;

debug_input will show up properly. any idea?

**Comment by Groovounet** [comment]
Using Visual Studio 2015, it seems there isn't a use of glm.natvis to visualize GLM types.

I think this issue is unrelated to GLM.

Thanks,
Christophe

**Comment by giordi91** [comment]
Hi thank you for your reply. First of all I had no idea what natvis file was. I learned something new thanks.
Now, I am having hard time understanding your comment.  I found that there is a natvis file in the repository for glm. Is that file automatically picked up by visual studio ? If so is that the file giving problem? Should I delete it ? 

If I am completely wrong can you please explain me a little what the actual problem/solution is?
Thanks a lot for your help

M.
