### ISSUE TITLE
Static tvec member variables crash the compiler in Visual Studio 2015 Update 2 and Update 3 when GLM_FORCE_SWIZZLE is enabled

### ISSUE THREAD

**Issue by alexanderbock** [g-truc/glm#553]
Minimally working (or not-working) example based off commit 13754226bc109237bfc55376e1553b8ca25e8b94:

```cpp
#define GLM_FORCE_SWIZZLE
#include "glm/glm.hpp"

struct Foo {
    static glm::vec2 Bar;
};

glm::vec2 Foo::Bar = glm::vec2(1.f, 1.f);

int main(int argc, char** argv) {}
```

results in:
```
main.cpp(8): fatal error C1001: An internal error has occurred in the compiler.
```

**Comment by Groovounet** [comment]
It sounds like compiler bug but it might show something wrong is going on.

**Comment by alexanderbock** [comment]
It is definitely related to the `GLM_FORCE_SWIZZLE`  we updated our subrepo of GLM and needed to switch from the `GLM_SWIZZLE` default to `GLM_FORCE_SWIZZLE` and the compiler started crashing with the above kind of code.

We jumped from 767aa16e to ad262c3 and did not switch the compiler between the jump.

**Comment by Groovounet** [comment]
It's a compiler crash. Maybe something is wrong in GLM but a compiler crash is not an acceptable behavior.

**Comment by Inreal** [comment]
Having that issue too, I hope that it might be solved soon via VC++ update or GLM release :(
