### ISSUE TITLE
VC2012 compiler issues with min/max

### ISSUE THREAD

**Issue by siddharthuniv** [g-truc/glm#557]
Hi,

I use windows 7 x64, visual studio 2012.

I have a large project and wanted to use glm for our project. However, glm.hpp includes header file: #include "detail/_fixes.hpp" which undefs min and max macro. If my project using glm is included, then other projects that use the macro that comes with the windows SDK is broken.  For now, i tried commenting out including _fixes.hpp and renamed the min function usage inside of glm. And everything seems to compile fine. Could you suggest if theres something that can be done on your side, or anything that can be done on my side so that i dont need to edit glm headers?

Thank you,

Sid

**Comment by Groovounet** [comment]
Hi,

Maybe a fix for you would be to use #define NOMINMAX in your code?
http://stackoverflow.com/questions/4913922/possible-problems-with-nominmax-on-visual-c

Thanks,
Christophe

**Comment by Groovounet** [comment]
GLM 0.9.9 manual has a FAQ answering this question following by previous answer.

Thanks,
Christophe
