### ISSUE TITLE
master does not compile

### ISSUE THREAD

**Issue by fgfuchs** [g-truc/glm#559]
Master branch does not compile on linux. One of the many error messages:
glm/glm/detail/type_vec4_simd.inl: In constructor ‘constexpr glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)5u]’:
glm/glm/detail/type_vec4_simd.inl:367:19: error: call to non-constexpr function ‘__m128 _mm_set1_ps(float)’
   data(_mm_set1_ps(s))

**Comment by Groovounet** [comment]
This issue should be fixed in GLM 0.9.8 and master branches

Thanks,
Christophe
