### ISSUE TITLE
Consider replacing test/external/gli with a git submodule

### ISSUE THREAD

**Issue by sschuberth** [g-truc/glm#560]
This suggestion just came to my mind when browsing the code, so I'm sorry if I'm overlooking something: Would it make sense to replace the contents of `test/external/gli` with a git submodule to the [gli project](https://github.com/g-truc/gli/) to reduce code duplication? I realize the directory contents are a bit different, and probably some more work is required, but maybe it's still feasible to do.

**Comment by Groovounet** [comment]
This issue was already discussed in GLI GitHUb part.

**Comment by sschuberth** [comment]
Now that you mention it I've found https://github.com/g-truc/gli/issues/67.
