### ISSUE TITLE
 C++ Builder not supported?

### ISSUE THREAD

**Issue by wind2s** [g-truc/glm#561]
C++ builder is my favourite IDE, so I got really annoyed as soon as started getting compilation errors when trying to setup GLM.

Maybe these errors are trivial or maybe not. What are the chances of getting these errors solved?

First errors were................

[BCC32 Fatal Error] setup.hpp(606): F1003 Error directive: Define GLM_FORCE_DEPTH_ZERO_TO_ONE instead of GLM_DEPTH_ZERO_TO_ONE to use 0 to 1 clip space.

[BCC32 Fatal Error] setup.hpp(632): F1003 Error directive: Define GLM_FORCE_LEFT_HANDED instead of GLM_LEFT_HANDED left handed coordinate system by default.

If I override them by invalidating the piece of code (Define directive) between the symbols /*...*/

I get a bunch of errors for earlier and multiple declaration of variable types. ie

[BCC32 Error] type_int.hpp(78): E2238 Multiple declaration for 'make_signed<genType>'
[BCC32 Error] type_int.hpp(77): E2344 Earlier declaration of 'make_signed<genType>'
................
Regards

**Comment by Groovounet** [comment]
Yes, it's not supported.

The compiler is just too bad too old.
I recommend you to find a new favourite tool.

Thanks,
Christophe

**Comment by JesseTG** [comment]
Savage.
