### ISSUE TITLE
Incorrect header in glm/mat4x3.hpp

### ISSUE THREAD

**Issue by Kodar-le-dok** [g-truc/glm#562]
In version 0.9.8.1, the second line of file glm/mat4x3.hpp says
/// @file glm/mat4x4.hpp
which is incorrect, due to the file name.

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.8 and master branches.

Thanks for reporting,
Christophe

**Comment by Kodar-le-dok** [comment]
That's strange to me : I'm using brew to install GLM on macOS Sierra and I've just checked whether I had the very last version installed (with brew upgrade glm) and it appears I indeed have version 0.9.8.1 on my computer, in which the issue is supposed to be fixed.
Any explanation to that?

**Comment by Groovounet** [comment]
I didn't mean it was fixed, I meant I fixed it in GLM 0.9.8 branch. 

So that will be in for GLM 0.9.8.2 release.

Thanks,
Christophe
