### ISSUE TITLE
Unable to use GLM 0.9.7.3 with Android NDK

### ISSUE THREAD

**Issue by jandoerntlein** [g-truc/glm#564]
Duplicate of #284. Problem reoccurs in 0.9.7.3. There is no "GLM_PLATFORM_ANDROID" check in the file "setup.hpp" anymore. Was the patch intentionally removed from later versions?

**Comment by Groovounet** [comment]
What compiler are you using? Which STL library?

**Comment by Groovounet** [comment]
This issue should not happen with GLM 0.9.7.6 however it seems possible GLM 0.9.8.1 has the issue.

**Comment by Groovounet** [comment]
This issue should be fixed for GLM 0.9.8.3 and in master branch.
Currently, I don't know of anyway to detect whether the project is being compiled with a C++11 STL on Android so I always assumed it's a C++ 98 STL.

Developers can use GLM_FORCE_CXX11 to force the use of a C++11 STL but this will result into compilation error if the used STL isn't a C++11 STL.

Thanks for reporting,
Christophe

**Comment by jandoerntlein** [comment]
Sorry for the late reply. My 3rdparty database showed version 0.9.7.3, but checked-out was version 0.9.8.1 (which you mentioned has the issue). Therefore I will today upgrade to 0.9.8.3 as proposed and report if the issue is still experienceable.

**Comment by jandoerntlein** [comment]
Fixed. Thank you!
