### ISSUE TITLE
make vector/matrix component length() static

### ISSUE THREAD

**Issue by MaliusArth** [g-truc/glm#565]
length() returns a constant which is specific to a type so no need to rely on an instance, 
the need to create a temporary instance e.g in template functions is annoying and unnecessary
see:  glm/test/core/core_type_length.cpp

**Comment by Groovounet** [comment]
This issue is fixed in master branch and GLM 0.9.8.2 release.

**Comment by elect86** [comment]
I'd need also a parameter to return, for matrices, the number of elements

For a mat4 this means 16, where `length` actually return 4 (because of 4 columns)

It's not urgent at all, it's just sugar code, but it'd nice to have
