### ISSUE TITLE
Build failed with Cuda 8.0.44 NVCC 

### ISSUE THREAD

**Issue by FictionIO** [g-truc/glm#566]
Hi,

Just tried using GLM 0.9.8.2 with newly released Cuda 8.0.44 NVCC. Build fails with report:

`glm/gtx/../detail/type_vec2.inl: In member function 'T& glm::tvec2<T, P>::operator[](glm::length_t) [with T = short unsigned int, glm::precision P = (glm::precision)0u]':
glm/gtx/../detail/func_packing.inl:20:   instantiated from here
glm/gtx/../detail/type_vec2.inl:104: error: subscripted value is neither array nor pointer
glm/gtx/../detail/type_vec2.inl: In member function 'T& glm::tvec2<T, P>::operator[](glm::length_t) [with T = short int, glm::precision P = (glm::precision)0u]':
glm/gtx/../detail/func_packing.inl:49:   instantiated from here
glm/gtx/../detail/type_vec2.inl:104: error: subscripted value is neither array nor pointer
glm/gtx/../detail/type_vec4.inl: In member function 'T& glm::tvec4<T, P>::operator[](glm::length_t) [with T = unsigned char, glm::precision P = (glm::precision)0u]':
glm/gtx/../detail/func_packing.inl:78:   instantiated from here
glm/gtx/../detail/type_vec4.inl:331: error: subscripted value is neither array nor pointer
glm/gtx/../detail/type_vec4.inl: In member function 'T& glm::tvec4<T, P>::operator[](glm::length_t) [with T = signed char, glm::precision P = (glm::precision)0u]':
glm/gtx/../detail/func_packing.inl:109:   instantiated from here
glm/gtx/../detail/type_vec4.inl:331: error: subscripted value is neither array nor pointer
glm/gtx/../detail/type_vec2.inl: In member function 'const T& glm::tvec2<T, P>::operator[](glm::length_t) const [with T = unsigned int, glm::precision P = (glm::precision)0u]':
glm/gtx/../detail/func_packing.inl:138:   instantiated from here
glm/gtx/../detail/type_vec2.inl:111: error: subscripted value is neither array nor pointer`

**Comment by Groovounet** [comment]
ermmm, it looks like Cuda doesn't like "return (&x)[i];"

Is this a new issue from Cuda 8? Does it happen on Cuda 7? 
Or is it new in GLM 0.9.8?

Does return *((&x) + i); change anything?

**Comment by Groovounet** [comment]
Hi,

I just installed Cuda 8 to double check this issue but I couldn't reproduce it using master branch.
I assume this was a setup issue, maybe a broken GLM version after an update of the previous version?

Thanks,
Christophe

**Comment by FictionIO** [comment]
Hi, apologies for the delay. 

I tested with GCC 4.4.6 :

`glm-0.9.8.3/glm/detail/type_vec2.inl: In member function 'T& glm::tvec2<T, P>::operator[](glm::length_t) [with T = short unsigned int, glm::precision P = (glm::precision)0u]':
glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:20:   instantiated from here
glm-0.9.8.3/glm/detail/type_vec2.inl:104: error: subscripted value is neither array nor pointer
glm-0.9.8.3/glm/detail/type_vec2.inl: In member function 'T& glm::tvec2<T, P>::operator[](glm::length_t) [with T = short int, glm::precision P = (glm::precision)0u]':
glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:49:   instantiated from here
glm-0.9.8.3/glm/detail/type_vec2.inl:104: error: subscripted value is neither array nor pointer
glm-0.9.8.3/glm/detail/type_vec4.inl: In member function 'T& glm::tvec4<T, P>::operator[](glm::length_t) [with T = unsigned char, glm::precision P = (glm::precision)0u]':
glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:78:   instantiated from here
glm-0.9.8.3/glm/detail/type_vec4.inl:331: error: subscripted value is neither array nor pointer
glm-0.9.8.3/glm/detail/type_vec4.inl: In member function 'T& glm::tvec4<T, P>::operator[](glm::length_t) [with T = signed char, glm::precision P = (glm::precision)0u]':
glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:109:   instantiated from here
glm-0.9.8.3/glm/detail/type_vec4.inl:331: error: subscripted value is neither array nor pointer
glm-0.9.8.3/glm/detail/type_vec2.inl: In member function 'const T& glm::tvec2<T, P>::operator[](glm::length_t) const [with T = unsigned int, glm::precision P = (glm::precision)0u]':
glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:138:   instantiated from here
glm-0.9.8.3/glm/detail/type_vec2.inl:111: error: subscripted value is neither array nor pointer
`

**Comment by Groovounet** [comment]
Ah I didn't realized it was with GCC. I used Cuda 8 with Visual C++. 

Maybe the problem is not Cuda at all. Any reason to used such an old GCC version?

I haven't tested building GLM with such an old version for a long time so that the minimum requirements for GLM 0.9.9 is GCC 4.6. 

Did you try build with GLM_FORCE_PURE and/or GLM_FORCE_CXX98?

Thanks,
Christophe

**Comment by FictionIO** [comment]
Found this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51969

It looks like it was a fixed bug in GCC. I strictly need to use 4.4.6 due to pipeline requirements. Sadly I cannot benefit from this fix. Any suggestion?

**Comment by Groovounet** [comment]
Where you defining GLM_FORCE_PURE, GLM_FORCE_CXX98 before including any GLM file? Sorry, I forgot to clarify.

**Comment by Groovounet** [comment]
I think I may have a workaround...

**Comment by Groovounet** [comment]
Hi,

I pushed a tentative fix on GLM 0.9.8 branch. Can you have a look to check whether it fixes your issue?
Here is a snapshot: https://github.com/g-truc/glm/archive/0.9.8.zip

Thanks,
Christophe

**Comment by FictionIO** [comment]
Many thanks.

Sadly its still giving the same error:

`/glm/glm-0.9.8.3/glm/detail/type_vec2.inl: In member function 'T& glm::tvec2<T, P>::operator[](glm::length_t) [with T = short unsigned int, glm::precision P = (glm::precision)0u]':
/glm/glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:20:   instantiated from here
/glm/glm-0.9.8.3/glm/detail/type_vec2.inl:104: error: subscripted value is neither array nor pointer
/glm/glm-0.9.8.3/glm/detail/type_vec2.inl: In member function 'T& glm::tvec2<T, P>::operator[](glm::length_t) [with T = short int, glm::precision P = (glm::precision)0u]':
/glm/glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:49:   instantiated from here
/glm/glm-0.9.8.3/glm/detail/type_vec2.inl:104: error: subscripted value is neither array nor pointer
/glm/glm-0.9.8.3/glm/detail/type_vec4.inl: In member function 'T& glm::tvec4<T, P>::operator[](glm::length_t) [with T = unsigned char, glm::precision P = (glm::precision)0u]':
/glm/glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:78:   instantiated from here
/glm/glm-0.9.8.3/glm/detail/type_vec4.inl:331: error: subscripted value is neither array nor pointer
/glm/glm-0.9.8.3/glm/detail/type_vec4.inl: In member function 'T& glm::tvec4<T, P>::operator[](glm::length_t) [with T = signed char, glm::precision P = (glm::precision)0u]':
/glm/glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:109:   instantiated from here
/glm/glm-0.9.8.3/glm/detail/type_vec4.inl:331: error: subscripted value is neither array nor pointer
/glm/glm-0.9.8.3/glm/detail/type_vec2.inl: In member function 'const T& glm::tvec2<T, P>::operator[](glm::length_t) const [with T = unsigned int, glm::precision P = (glm::precision)0u]':
/glm/glm-0.9.8.3/glm/gtx/../detail/func_packing.inl:138:   instantiated from here
/glm/glm-0.9.8.3/glm/detail/type_vec2.inl:111: error: subscripted value is neither array nor pointer`

I have single GLM header, defined like this:

`
#pragma once
#define GLM_FORCE_PURE
#define GLM_FORCE_CXX98

#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>
#include <glm/mat4x4.hpp>
#include <glm/mat3x3.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/geometric.hpp>
#include <glm/vector_relational.hpp>
#include <glm/gtx/projection.hpp>
#include <glm/gtx/matrix_interpolation.hpp>
#include <glm/gtc/epsilon.hpp>
#include <glm/gtc/constants.hpp>`

Could this be because I am doing something wrong?

**Comment by Groovounet** [comment]
I read "glm-0.9.8.3" in your log, did you used this snapshot https://github.com/g-truc/glm/archive/0.9.8.zip?
