### ISSUE TITLE
CMake version specification doesn't work

### ISSUE THREAD

**Issue by rutsky** [g-truc/glm#572]
I'm using GLM version 0.9.8.1 from Debian package on 64-bit GNU/Linux (https://packages.debian.org/sid/libglm-dev).
When I'm trying to specify in my `CMakeLists.txt` minimal required GLM version:

```
find_package(glm 0.9.8 REQUIRED)
```

I get CMake error:

```
CMake Error at CMakeLists.txt:21 (find_package):
  Could not find a configuration file for package "glm" that is compatible
  with requested version "0.9.8".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/glm/glmConfig.cmake, version: unknown



*** cmake process exited with exit code 1.
```

Requirement without version specification works fine:

```
find_package(glm REQUIRED)
```

**Comment by Groovounet** [comment]
@shaxbee who contributed this feature in #324 might be interested to have a look.

Thanks for reporting,
Christophe

**Comment by shaxbee** [comment]
Could you be so kind and elaborate? What doesn't work?

**Comment by shaxbee** [comment]
Sorry, I see the problem. PR will follow shortly.

**Comment by shaxbee** [comment]
Seems like I named version file incorrectly - according to (https://cmake.org/Wiki/CMake/Tutorials/Packaging#Package_Version_Files) it should be ```glmConfigVersion.cmake``` not ```glmVersion.cmake```.

See #573.

**Comment by Groovounet** [comment]
Thanks @shaxbee for the quick resolution. Having a quick look I noticed this file name different but I haven't sue it matters.

@rutsky, it would be great if you could have a look to double check it's working just fine for you.

This is issue should be fixed in GLM 0.9.8 branch for GLM 0.9.8.3 release and in master branch.

Thanks,
Christophe

**Comment by rutsky** [comment]
@shaxbee thanks for the quick fix!

@Groovounet I can confirm that renaming `glmVersion.cmake` to `glmConfigVersion.cmake` fixes the issue on my system.

**Comment by Groovounet** [comment]
Thanks! :)
