### ISSUE TITLE
the operator *  

### ISSUE THREAD

**Issue by Narcissuscyn** [g-truc/glm#576]
Hello,
        It's  great for me to use glm,thanks for your contribution!
        But i have a problem when i study OpenGL with glm
        1.I didn't find the source code about overloading operator *,so i can't understand how two matrixes mutiply.For example:

         glm::mat4 rotate,translate,view;
         .....
         view=rotate*translate;

     //  I have tried to understand it with the multiplication of matrix like this:

      **mat4 view=mat4(0);
	for (int i = 0;i < 4;i++)
	{
		for (int j = 0;j < 4;j++)
		{
			for (int k = 0;k < 4;k++)
			{
				view[i][j] += rotate[i][k] * translate[k][j];
			}
		}
	}**

but the result is not the same.   
     I am expecting your answer!Thanks!

**Comment by Groovounet** [comment]
I guess this is what you were looking for:
```
	template <typename T, precision P>
	GLM_FUNC_QUALIFIER tmat4x4<T, P> operator*(tmat4x4<T, P> const & m1, tmat4x4<T, P> const & m2)
	{
		typename tmat4x4<T, P>::col_type const SrcA0 = m1[0];
		typename tmat4x4<T, P>::col_type const SrcA1 = m1[1];
		typename tmat4x4<T, P>::col_type const SrcA2 = m1[2];
		typename tmat4x4<T, P>::col_type const SrcA3 = m1[3];

		typename tmat4x4<T, P>::col_type const SrcB0 = m2[0];
		typename tmat4x4<T, P>::col_type const SrcB1 = m2[1];
		typename tmat4x4<T, P>::col_type const SrcB2 = m2[2];
		typename tmat4x4<T, P>::col_type const SrcB3 = m2[3];

		tmat4x4<T, P> Result(uninitialize);
		Result[0] = SrcA0 * SrcB0[0] + SrcA1 * SrcB0[1] + SrcA2 * SrcB0[2] + SrcA3 * SrcB0[3];
		Result[1] = SrcA0 * SrcB1[0] + SrcA1 * SrcB1[1] + SrcA2 * SrcB1[2] + SrcA3 * SrcB1[3];
		Result[2] = SrcA0 * SrcB2[0] + SrcA1 * SrcB2[1] + SrcA2 * SrcB2[2] + SrcA3 * SrcB2[3];
		Result[3] = SrcA0 * SrcB3[0] + SrcA1 * SrcB3[1] + SrcA2 * SrcB3[2] + SrcA3 * SrcB3[3];
		return Result;
	}
```
