### ISSUE TITLE
intersectRayPlane returns true in parallel case

### ISSUE THREAD

**Issue by Bargor** [g-truc/glm#578]
When ray is parallel to plane function intersectRayPlane returns true.

Eg glm::intersectRayPlane(glm::vec3(0.0f, 1.0f, 0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f), dist)

Problem can be solved by inverting sign of epsilon check:

		if(d < -Epsilon)
		{
			intersectionDistance = glm::dot(planeOrig - orig, planeNormal) / d;
			return true;
		}
		return false;

Edit: not sure how to handle case when plane and ray lies on same plane, since there are inifinite solutions.

**Comment by Groovounet** [comment]
This issue is fixed in both master and 0.9.8 branch with your proposed fix.

Thanks for contributing,
Christophe
