### ISSUE TITLE
NDK can not be developed

### ISSUE THREAD

**Issue by blue1991** [g-truc/glm#579]
hi,
   I copy the glm directory to the jni directory,and add "LOCAL_C_INCLUDES += $(realpath  $(LOCAL_PATH)/ijkmedia/ijkplayer/glm)" in jni/Android.mk.
add "APP_STL := gnustl_static" in jni/Application.mk
but,when i build,log that:
![image](https://cloud.githubusercontent.com/assets/22043241/20590786/1f929798-b260-11e6-9712-fdabf395a2f6.png)
Can you help me?

**Comment by Groovounet** [comment]
Hi,

Sorry but I don't think this is the right place to ask such question. I would recommend http://stackoverflow.com/

Thanks,
Christophe
