### ISSUE TITLE
std::isnan collides with isnan in fbxmath

### ISSUE THREAD

**Issue by sasmaster** [g-truc/glm#590]
In func_common,inl we have

```
#	if GLM_HAS_CXX11_STL
 	 using std::isnan;
#	else
```

Now,in my app I use FBX SDK.And it defines its isnan in the fbxmath.h.

I tried to undef etc but it doesn't help,getting:

 error C2039: 'isnan': is not a member of 'std'

So what I did for now is  
```
#	if GLM_HAS_CXX11_STL
 	// using std::isnan;
#	else
```

How can it be solve in the lib level?

Using VS2015, VC 140 compiler ,64bit project.
GLM version:0.9.7.6

**Comment by Groovounet** [comment]
I don't think it's really possible to fix it in GLM

Here is FBX code 
```
#if defined(FBXSDK_ENV_WIN)
	#ifndef isnan
		#define isnan	_isnan
	#endif
	#ifndef finite
		#define finite	_finite
	#endif
#endif
```

It just defines isnan on Windows which would conflict with cmath too...

I think the best is to just comment that define in FBX SDK.
