### ISSUE TITLE
Missing GLM_STATIC_CONST_MEMBERS

### ISSUE THREAD

**Issue by IntellectualKitty** [g-truc/glm#591]
When scanning the code after compiler errors about undefined values, I determined that GLM_STATIC_CONST_MEMBERS are provided only in:

    detail/type_mat4x2.inl
    detail/type_vec2.inl
    detail/type_vec3.inl

From a review of the PRs, it seems that they were previously included completely in #429, but they have apparently gone missing since then.

These are quite convenient and make for cleaner looking code, so it would be nice to re-include them.

**Comment by Groovounet** [comment]
You are right, this was left over from an old experiment.

Thanks for reporting,
Christophe
