### ISSUE TITLE
Requesting inclusion of GLM_STATIC_CONST_MEMBERS

### ISSUE THREAD

**Issue by IntellectualKitty** [g-truc/glm#592]
We had a communication failure regarding GLM_STATIC_CONST_MEMBERS with issue #591.  I think they are very valuable, and my goal was to have them re-added rather than removed.

For instance, ZERO and especially IDENTITY matrices are almost always needed.  As an example, in my scene graph code, a renderable node without a parent transformation node defaults to using the identity matrix for its world transformation.  If these matrices are not provided as constants in GLM -- and I think the cleanest place is to put them is as static members in the class rather than externally -- then I will have to provide them myself, which is both messy and a nuisance.

To give an example for vectors, I think it's far cleaner, easier, and makes for more understandable code if I initialize the world coordinates for the camera as:

```
    m_WorldPosition(glm::vec3::ZERO),
    m_WorldRight(glm::vec3::X),
    m_WorldUp(glm::vec3::Y),
    m_WorldForward(glm::vec3::Z),
```

rather than doing this:

```
    m_WorldPosition(glm::vec3(0.0,0.0,0.0)),
    m_WorldRight(glm::vec3(1.0,0.0,0.0)),
    m_WorldUp(glm::vec3(0.0,1.0,0.0)),
    m_WorldForward(glm::vec3(0.0,0.0,1.0)),
``` 

Using the GLM_STATIC_CONST_MEMBERS for this purpose -- in contrast to using a long list of numbers -- makes the code both easier to read and less error prone since its easy to make a mistake (and not see it) when you have to plug in a long list of numbers manually.  Even in a simpler case like setting the world axis for a billboard node, its easier to read `glm::vec3::Y` rather than `glm::vec3(0.0,1.0,0.0)` since you have mentally calculate what that list of numbers actually means.

So, I am definitely in favor of including and keeping GLM_STATIC_CONST_MEMBERS.  In fact, I would like to include the addition of ONE for the vectors as well as ZERO since this is a perfect way to initialize light and material colors to white rather than black.

**Comment by Groovounet** [comment]
Hi,

If you need an identity matrix, you can just do glm::mat4(1.0f) for example.

A better approach for m_WorldPosition(glm::vec3(0.0,0.0,0.0)), is actually:

```
m_WorldPosition(0.0f)
```

This is just following GLSL design which typically GLM is trying to do as much as possible so that GLM is not something new to learn.

This is why the static members is not something I am very keen of: It doesn't follow GLM precedent. 

To extend GLM, the library have "extensions" which allows additional features to not be invasive within GLM core features.

I guess this meant something like:
```
x<glm::vec3>(); // which would returns glm::vec3(1.0,0.0,0.0)
```

Maybe worth to try... not too sure.

Thanks,
Christophe

**Comment by IntellectualKitty** [comment]
> This is just following GLSL design which typically GLM is trying to do as much as possible so that GLM is not something new to learn.
>
> This is why the static members is not something I am very keen of: It doesn't follow GLM precedent.
>
> To extend GLM, the library have "extensions" which allows additional features to not be invasive within GLM core features.

Following GLSL design is an important goal, and I'm sure one of the reasons why GLM is so popular.  Also, making GLM easy to learn is undoubtedly helpful.

I'll follow the suggestions you made.  For instance, you're correct that `m_WorldPosition(0.0f)` would be better than `m_WorldPosition(glm::vec3(0.0,0.0,0.0))`.  Also, a function like `x<glm::vec3>()` would be convenient and useful.

However, I still think that adding static constants is valuable.  For instance, a problem that I have using `glm::mat4(1.0f)` is that there are times when I need to return a pointer to the identity matrix -- for example, in the case when a scene graph node is without a parent -- instead of returning a new instance.  I could include the identity matrix as a static constant in my scene graph class, but from a design perspective, it's cleaner to include it as a static constant in the matrix class.  For example, if I wanted to implement an old OpenGL-style matrix stack (like the Cinder library does) in addition to my scene graph, returning the identity matrix as a default when the stack is empty, I'd have to define the identity matrix as a constant in both places.

So, again, from a design perspective, it's simpler and cleaner to include the identity matrix as a static constant in the matrix class since it then only needs to be defined once and since it's really an attribute of the matrix class rather than anything that simply uses or depends on the matrix class.

Again, I think that you have good goals in trying to keep GLM simple and easy-to-learn and to carefully follow GLSL design.  However, GLM (or whatever mathematics library is used) is an extremely important linkage between OpenGL -- whose sole purpose really is just to drive the graphics hardware -- and the rest of the application, which can include scene graph operations, object culling, object picking, physics calculations, collision detection, etc.  All of these tasks are necessary and mathematically intensive.  So, from that perspective, GLM is far more than simple GLSL support, meaning that the GLM extensions, in addition to the core, are an important, vital, and necessary part of developing a complete application.  And the more mathematical power and convenience GLM can provide, the more useful it is to developers.

Finally, one of the things that I like about GLM is the fact that you can get support for the features that you want by including the files you need and by specifying macros such as GLM_SWIZZLE.  So, I still think that using GLM_STATIC_CONST_MEMBERS to include static constants -- or not -- depending on the particular needs of the developer, is a valuable and useful feature while still not adding undue complexity any more than an optional core feature like GLM_SWIZZLE.

Anyway, I understand and respect your reasons for being hesitant about this, and I appreciate your consideration.

Thank you,
IntellectualKitty
