### ISSUE TITLE
isfinite is not defined when integrate glm and Physx 3.3 on Android platform(ndk)

### ISSUE THREAD

**Issue by w359405949** [g-truc/glm#597]
isfinite is not defined when integrate glm and Physx 3.3 on Android platform(ndk)

**Comment by Groovounet** [comment]
A workaround of this issue is seems to not include glm/gtx/compatibility.hpp or glm/ext.hpp

I am under the impression this issue is actually independent from PhysiX 

Thanks,
Christophe
