### ISSUE TITLE
Rename of tvec3 and friends to vec

### ISSUE THREAD

**Issue by mgerhardy** [g-truc/glm#598]
The renaming leads to a lot of problems in some of my repositories and I can imagine that other people might be affected, too. There should still be typedefs to tvec3 to be compatible with older glm versions.

**Comment by JesseTG** [comment]
Yep, this hits me, too.  Both a project I'm working on and a library I contribute to have sufferred.

**Comment by Groovounet** [comment]
Hi,

This is a good point and an issue I allow personally encountered.... 
A approach is to use alias template which requires C++11. Do you think this would be enough for your use cases?

This still means that project requiring C++98 compiler couldn't benefit for this and would have to upgrade their projects.

Thanks,
Christophe

**Comment by JesseTG** [comment]
You've been planning that anyway, right?

**Comment by mgerhardy** [comment]
It would solve it for me, as all my proijects are >= c++11 - but of course I can't talk for others.

**Comment by Groovounet** [comment]
This issue should be fixed in master branch with https://github.com/g-truc/glm/commit/41cf89516e3b6a5747c2d2c7fee187d84eb6c5cb commit for project relying on C++ compilers that support template aliases.

Thanks for reporting,
Christophe

**Comment by JesseTG** [comment]
You forgot the matrices.

**Comment by JesseTG** [comment]
Ping @Groovounet

**Comment by JesseTG** [comment]
Notice me, senpai~

**Comment by JesseTG** [comment]
Thank you!
