### ISSUE TITLE
CMake glm detection doesn't work

### ISSUE THREAD

**Issue by blessed** [g-truc/glm#601]
Hi,

I'm using GLM version 0.9.8.3 from Arch package on 64-bit GNU/Linux (https://www.archlinux.org/packages/community/any/glm/).
When I'm trying to specify in my CMakeLists.txt:
`find_package(glm REQUIRED)`

The following error occurs:

`Could not find a configuration file for package "glm" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)
    /usr/lib/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)
    /lib64/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)
    /lib/cmake/glm/glmConfig.cmake, version: 0.9.8 (32bit)`

I'm not sure if this isn't an Arch package problem, though.

**Comment by Groovounet** [comment]
Maybe @shaxbee who worked on it may have an idea about this...

Thanks for reporting,
Christophe

**Comment by shaxbee** [comment]
Hello, from what I see in your log you're trying to do 32bit build on 64bit system - that might be the problem.

**Comment by blessed** [comment]
Well actually no. I have checked this and the config is 64bit. I have also disabled this module just to make sure and all other modules in my project produce 64bit binaries.

I don't know why it says 32bit in the parentheses, though. My guess would be that the problem really is in glm, as before the update to 0.9.8.3 it all worked just fine.

**Comment by shaxbee** [comment]
Understood. What was the previous version you've used? It's gonna make it
easier to compare.

**Comment by shaxbee** [comment]
It would also help if you could post following files:
/usr/lib/cmake/glm/glmConfig.cmake
/usr/lib/cmake/glm/glmConfigVersion.cmake

It seems that one of those files contains architecture information while it
shouldn't.

Since package is marked noarch in arch package manager it might be that
it's only built on 32bit system.

**Comment by blessed** [comment]
@shaxbee Sorry for the late reply, I didn't notice your response. But the problem seems to be solved with the newest arch package, so this really seems to be an os dependent problem. Here's the link where it was fixed [arch git](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/glm&id=8c00ab3ce44989915328f29a8648518c1da14697)

Thanks for your support!
