### ISSUE TITLE
transpose and imat

### ISSUE THREAD

**Issue by Philip-Trettner** [g-truc/glm#603]
Is there a reason why matrix transpose has a static_assert on `std::numeric_limits<T>::is_iec559` for transpose?

In my case, it's preventing me from transposing an integer matrix (imat4).

In general, transpose should work perfectly with ANY type (that is movable/copyable), right?

**Comment by BitquakeProgramming** [comment]
Hi Philip, I`m sorry I dont know the answer but I wanted to get in contact with you because of GlmSharp. Could you make your email visible for a few moments? I have some questions and performance considerations. You can also write an email to me: bitquakeengine@gmail.com.  

Best regards :-)

**Comment by Groovounet** [comment]
Hi,

You can define GLM_FORCE_UNRESTRICTED_GENTYPE before including <glm/glm.hpp> to enable integer matrices (and others types).

It's not supported by default because GLSL doesn't support it and GLM tries to implement as closely as possible.

Thanks,
Christophe
