### ISSUE TITLE
Wrong number of template arguments on gcc

### ISSUE THREAD

**Issue by nourikhalass** [g-truc/glm#605]
Hello,

I am having the same issue as described here: #600,
This means that compiling glm gives the following error:

`func_common.inl:193:51: error: wrong number of template arguments (5, should be 6)  struct compute_sign<T, P, vecType, false, Aligned>`

I am using g++ version 5.3.0 on Windows with MinGW 3.22

The issue can be solved by adding the missing template arguments.
```c++
#	if GLM_ARCH == GLM_ARCH_X86
	template<length_t L, typename T, precision P, template<length_t, typename, precision> class vecType, bool Aligned>
	struct compute_sign<L, T, P, vecType, false, Aligned>
	{
		GLM_FUNC_QUALIFIER static vecType<L, T, P> call(vecType<L, T, P> const & x)
		{
			T const Shift(static_cast<T>(sizeof(T) * 8 - 1));
			vecType<L, T, P> const y(vecType<L, typename make_unsigned<T>::type, P>(-x) >> typename make_unsigned<T>::type(Shift));

			return (x >> Shift) | y;
		}
	};
#	endif
```

I will (try) to make a pull request with the fix!

**Comment by nourikhalass** [comment]
Pull request fixing this particular issue: #606

**Comment by Groovounet** [comment]
Thanks for contributing!
