### ISSUE TITLE
CUDA Segfault

### ISSUE THREAD

**Issue by danem** [g-truc/glm#612]
I've encountered this weird bug that I haven't been able to quite track down. I'm trying to use GLM with a program compiled by nvcc 8.0.54. A call `glm::lookAt` in another source file causes a segfault [here](https://github.com/g-truc/glm/blob/e8962dda2a2652a6a97432449681a4366876fc84/glm/gtc/matrix_transform.inl#L528). If step through the program with lldb I see the value passed to normalize (ie: `center - eye`) is null, causing the segfault. Oddly enough I have found that this only segfaults if I reference certain GLM functions in the main cuda source file. [Here](https://gist.github.com/danem/19a9c81eabbf3f6f59d9a6831c9b0596) is a minimal program that demonstrates the behavior.

This is on OSX 10.11.6 using GLM 0.9.8.3. 

edit: I've also discovered that if I change the extension of the Camera.cc to Camera.cu everything works nicely. Suggesting the issue has something to do with how nvcc interprets the files.

**Comment by blahgeek** [comment]
Hi @danem could you test if #613 fixes your issue? (or you can just go to your .../include/glm/simd/platform.h line 175, change `GLM_COMPILER_CUDA` to `GLM_COMPILER_CUDA80` to see if it works)

**Comment by blahgeek** [comment]
`#define GLM_FORCE_CXX03` before including glm.hpp also works for me.

**Comment by danem** [comment]
@blahgeek That did the trick! Thanks! Just as a note, only the first suggestion worked for me, the second suggestion still resulted in a segfault.

**Comment by Groovounet** [comment]
Thanks @blahgeek for the fix!
Christophe
