### ISSUE TITLE
packF3x9_E1x5() invalid conversion to shared exponent format

### ISSUE THREAD

**Issue by Jojendersie** [g-truc/glm#614]
In file glm/gtc/packing.inl line 621 a wrong constant causes invalid outputs. The problem is the 16.f which must be 15.f (Exponent bias).

Possible test: Convert a fine gray gradient into shared exponent RGB9E5 format. There will be invalid dark (near black) lines at certain gray levels.

Please also fix this in the gli library. In gli/external/glm the same bug is present. It is actually gli where I spotted the bug while converting textures.

**Comment by Groovounet** [comment]
This issue is now fixed in GLM 0.9.8 ans master branches. 
I'll updated GLM in GLI as well.

Thanks for reporting,
Christophe
