### ISSUE TITLE
missing min(genIType, int) and max(genIType, int)

### ISSUE THREAD

**Issue by zholos** [g-truc/glm#616]
These used to work in GLM 0.9.7, but don't in GLM 0.9.8:

```c++
glm::min(glm::ivec2(1), 1);
glm::max(glm::ivec2(1), 1);
```

```
error: static_assert failed "'min' only accept floating-point inputs for the interpolator a"
error: static_assert failed "'max' only accept floating-point inputs for the interpolator a"
```

Since `min(genIType, int)` and `max(genIType, int)` are specified by GLSL, I think they should work in GLM even without defining `GLM_FORCE_UNRESTRICTED_GENTYPE` from #378.

**Comment by Groovounet** [comment]
This issue is fixed in GLM 0.9.8 branch for GLM 0.9.8.5 release.

Thanks for reporting!
Christophe
