### ISSUE TITLE
Unused variable s1 in glm/gtx/spline.inl

### ISSUE THREAD

**Issue by severinmeyer** [g-truc/glm#618]
In glm/gtx/spline.inl, the very useful `catmullRom()` and `hermite()` functions both declare a variable `s1` without using it. This throws a spanner in the compilation, as gcc -Wall reports it as an error:

    glm/gtx/spline.inl:16:32: error: unused variable ‘s1’ [-Werror=unused-variable]
       typename genType::value_type s1 = s;
                                    ^

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9 release.

Thanks for reporting,
Christophe
