### ISSUE TITLE
GLM_FORCE_UNRESTRICTED_GENTYPE binary incompatibility

### ISSUE THREAD

**Issue by Philip-Trettner** [g-truc/glm#619]
I have an executable built with GLM_FORCE_UNRESTRICTED_GENTYPE. This executable uses a static library that does NOT have this flag set.
The resulting code is incompatible, it does compile but crashes (the compiler generates different calling conventions).

Is this behavior by design?
Is there a way to generate a warning?
I thought this was only a diagnostic define, why does it alter the code?

**Comment by Groovounet** [comment]
I must say I have no idea why this is happening... I agree it's just a a diagnostic define.

To help detecting these scenarios where different version of GLM are included, I add a system to check whether GLM was already included. Unfortunately that system requires versions GLM that supports this system... to I guess it's just for future use.

Thanks,
Christophe
