### ISSUE TITLE
Detection of c++11 broken for clang 3.9 (debian)

### ISSUE THREAD

**Issue by mgerhardy** [g-truc/glm#620]
clang version 3.9.1-4 (tags/RELEASE_391/rc2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Including glm/gtx/hash.hpp will result in an error when using -std=gnu++14 with clang
_LIBCPP_VERSION is not defined

**Comment by mgerhardy** [comment]
According to https://sourceforge.net/p/predef/wiki/Libraries/ _LIBCPP_VERSION is only defined when using libcxx and at least one header is included from it.

**Comment by Groovounet** [comment]
Which version of GLM are you using?

**Comment by mgerhardy** [comment]
master revision from April 5th.

**Comment by Groovounet** [comment]
Oh the error is that?
```
GLM_GTX_hash requires C++11 standard library support"
```

If you are using libstdc++, there is no way to detection the STL versions with Clang but GCC profiles this define: GLM_FORCE_CXX14 which will force GLM to use all the C++ 14 feature including STL onces.

Thanks,
Christophe
