### ISSUE TITLE
SIGSEGV in intrinsics on macOS

### ISSUE THREAD

**Issue by msc-** [g-truc/glm#623]
glm::inverse & glm::transpose are crashing in intrinsics on macOS 64-bit.

![screen shot 2017-04-12 at 18 35 23](https://cloud.githubusercontent.com/assets/2244683/24951677/311066cc-1fb0-11e7-90b9-e9178ce45aa6.png)

My code that calls these runs fine on iOS and Linux. The same thing happens even if GLM_FORCE_PURE is defined. I also defined GLM_{FORCE_,}MESSAGES to try an see what architecture GLM thinks it is, but no messages about architecture are output, only messages indicating that the constants and matrix transform extensions are included.

The in pointer is valid and readable.

I using Xcode 8.3.1 (LLVM 8.1) on macOS 10.12.4. Same thing happened on 10.12.3. It's a Mac Mini with an Intel Core i5 processor.

The program I'm using is vkloadtests which is one of the targets in the project  at https://github.com/msc-/KTX. You need the vkloadtests branch.

**Comment by Groovounet** [comment]
Hi,
Which version of GLM are you using?
Thanks,
Christophe

**Comment by msc-** [comment]
I'll have to get back to you on that. It is from a clone of the GitHub repo I made a couple of months ago but the clone is on another machine that is turned off at present. There's no version number in glm.hpp.

Also, I will try to create a small program to reproduce the problem.

**Comment by Groovounet** [comment]
If you #define GLM_MESSAGES before including glm.hpp, GLM will prints a lot of information including the version number.

Thanks,
Christophe

**Comment by msc-** [comment]
The problem is fixed in the HEAD revision. I have no idea what commit had the fix.

I haven't had any luck with the messages. I did #define GLM_FORCE_MESSAGES with the HEAD revision but didn't see any messages. I didn't pursue it since my problem is fixed.
