### ISSUE TITLE
GLM_FORCE_SIZE_T_LENGTH fails with latest GLM (0.9.9.0)

### ISSUE THREAD

**Issue by IntellectualKitty** [g-truc/glm#624]
Using GLM_FORCE_SIZE_T_LENGTH with the latest release of GLM results in the following errors:

> /usr/local/include/glm/detail/func_matrix.hpp:38:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<2, 2, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:44:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<2, 3, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:50:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<2, 4, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:56:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<3, 2, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:62:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<3, 3, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:68:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<3, 4, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:74:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<4, 2, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:80:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<4, 3, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:86:40: error: template template argument has different template parameters than its corresponding template template parameter
>         struct outerProduct_trait<4, 4, T, P, vec, vec>
>                                               ^
> /usr/local/include/glm/detail/../detail/precision.hpp:35:20: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<length_t L, typename T, precision P = defaultp> struct vec;
>                           ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:66: error: template template argument has different template parameters than its corresponding template template parameter
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                         ^
> /usr/local/include/glm/detail/func_matrix.hpp:114:69: note: template non-type parameter has a different type 'length_t' (aka 'unsigned long') in template argument
>         template<int DA, int DB, typename T, precision P, template<length_t, typename, precision> class vecTypeA, template<length_t, typename, precision> class vecTypeB>
>                                                                            ^
> /usr/local/include/glm/detail/../detail/type_mat.hpp:11:71: note: previous non-type template parameter with type 'int' is here
>         template<int Columns, int Rows, typename T, precision P, template<int, class, precision> class colType, template<int, class, precision> class rowType>
>                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:87: error: expected a qualified name after 'typename'
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:91: error: expected ';' at end of declaration
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                  ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:92: error: C++ requires a type specifier for all declarations
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                   ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:105: error: use of undeclared identifier 'vecTypeA'
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                                ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:114: error: use of undeclared identifier 'DA'
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                                         ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:124: error: expected expression
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                                                   ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:121: error: use of undeclared identifier 'P'
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                                                ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:135: error: use of undeclared identifier 'vecTypeB'
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                                                              ^
> /usr/local/include/glm/detail/func_matrix.hpp:115:144: error: use of undeclared identifier 'DB'
>         GLM_FUNC_DECL typename detail::outerProduct_trait<DA, DB, T, P, vecTypeA, vecTypeB>::type outerProduct(vecTypeA<DA, T, P> const & c, vecTypeB<DB, T, P> const & r);
>                                                                                                                                                       ^

For reference, here is the output of GLM_FORCE_MESSAGES:

> GLM: Apple platform detected
> GLM: version 0.9.9.0
> GLM: Clang compiler detected
> GLM: 64 bits model
> GLM: SSE4.1 instruction set
> GLM: C++14
> GLM: Swizzling operators disabled, #define GLM_SWIZZLE to enable swizzle operators
> GLM: Depth clip space: negative one to one
> GLM: Coordinate system: right handed
> GLM: .length() returns glm::length_t, a typedef of std::size_t

**Comment by Groovounet** [comment]
This issue is fixed in master branch and now GLM_FORCE_SIZE_T_LENGTH has a dedicated test so that it doesn't happen again.

Thanks for reporting!
Christophe
