### ISSUE TITLE
Possible error in tdualquat comparison operator

### ISSUE THREAD

**Issue by renanti** [g-truc/glm#629]
Dual quaternion operator != implementation looks different from operator ==
`return (q1.real != q2.dual) || (q1.real != q2.dual);`
`return (q1.real == q2.real) && (q1.dual == q2.dual);`

https://github.com/g-truc/glm/blob/master/glm/gtx/dual_quaternion.inl#L220

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9 release. Thanks for contributing!
Christophe
