### ISSUE TITLE
It seems that the lhs and rhs of operator * are opposite.

### ISSUE THREAD

**Issue by saedrna** [g-truc/glm#630]
For example, the fourth row is what glm is doing.
``` cpp
mat3x4 A;
mat4x3 AT;
mat3x3 AAT = A*AT; // this is what is expected for 3x4 * 4x3 matrix to get 3x3 matrix
mat4x4 AAT2 = A*AT // this is what is doing in glm, will get a 4x4 matrix
```

**Comment by Groovounet** [comment]
Erm, my perception is that you are used to D3D / HLSL conversions but GLM follows OpenGL / GLSL / mathematics conversions: 
https://en.wikipedia.org/wiki/Matrix_multiplication

Thanks,
Christophe
