### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by jeduden** [g-truc/glm#631]
Currrently the build fails. Looks like the bitfields test is broken. 
does anybody now if the functionality is broken ? or the test itself ?

**Comment by Groovounet** [comment]
I think the code is not broken, it's just experimental code in the test framework that I am writing that cause the failure....

**Comment by Groovounet** [comment]
This issue is fixed in GLM master branch.

Thanks for reporting

**Comment by elect86** [comment]
I get also an error [here](https://github.com/g-truc/glm/blob/master/test/gtc/gtc_bitfield.cpp#L718)

When `j = 0` and `i = 1`, I get

    glm::uint32 A = bitfieldInterleave_u8vec4(glm::uint8(1), glm::uint8(0), glm::uint8(1), glm::uint8(0));
	glm::uint32 B = glm::bitfieldInterleave(glm::uint8(1), glm::uint8(0), glm::uint8(1), glm::uint8(0));

`A = 64` and `B = 5`
