### ISSUE TITLE
vec2<int>.length() always returns 2

### ISSUE THREAD

**Issue by rfosner** [g-truc/glm#632]
probably because that's how it's coded - intentional? type_vec2.inl ~ line 100

	template <typename T, precision P>
	GLM_FUNC_QUALIFIER GLM_CONSTEXPR typename tvec2<T, P>::length_type tvec2<T, P>::length() const
	{
		return 2;
	}

**Comment by rfosner** [comment]
Ahh user error!

**Comment by JesseTG** [comment]
To clarify, for anyone who sees this issue in the future: `tvec*<T, P>::length()` returns the *number of components* of a vector, not its Euclidean length.
