### ISSUE TITLE
could not compile glm::decompose on android studio ndk

### ISSUE THREAD

**Issue by PerspectivesLab** [g-truc/glm#634]
glm::mat4x4 glmMat;
glm::vec3 scale, translation, skew;
glm::vec4 perspective;
glm::quat rotation;

glm::decompose(glmMat, scale, rotation, translation, skew, perspective);

will produce :
Information:(166, 31) candidate function not viable: no known conversion from 'col_type' (aka 'tvec4<float, (glm::precision)0U>') to 'const tvec3<float, (glm::precision)0U>' for 1st argument

Error:(124, 17) error: no viable overloaded '='

**Comment by Groovounet** [comment]
GLM has a trivial test which works fine (tm)
```
int main()
{
	int Error(0);

	glm::mat4 Matrix(1);

	glm::vec3 Scale;
	glm::quat Orientation;
	glm::vec3 Translation;
	glm::vec3 Skew(1);
	glm::vec4 Perspective(1);

	glm::decompose(Matrix, Scale, Orientation, Translation, Skew, Perspective);

	return Error;
}
```
Could you define GLM_FORCE_MESSAGES before including GLM, build and share what GLM says?

**Comment by PerspectivesLab** [comment]
Hey, thx,
here is the full log, cant compile:


 Information:(471, 15) in instantiation of function template specialization 'glm::decompose<float, glm::precision::highp>' requested here
Information:(471, 15) note: in instantiation of function template specialization 'glm::decompose<float, glm::precision::highp>' requested here
Information:(166, 31) candidate function not viable: no known conversion from 'col_type' (aka 'tvec4<float, (glm::precision)0U>') to 'const tvec3<float, (glm::precision)0U>' for 1st argument
                GLM_FUNC_DECL tvec3<T, P> & operator= (tvec3<T, P> const & v);
Information:(169, 31) candidate template ignored: could not match 'tvec3' against 'tvec4'
Information:(166, 31) note: candidate function not viable: no known conversion from 'col_type' (aka 'tvec4<float, (glm::precision)0U>') to 'const tvec3<float, (glm::precision)0U>' for 1st argument
Information:(169, 31) note: candidate template ignored: could not match 'tvec3' against 'tvec4'
Error:(124, 17) error: no viable overloaded '='
Error:(129, 6) error: no matching function for call to 'v3Scale'
Information:(43, 26) candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
Error:(133, 15) error: no matching function for call to 'combine'
Information:(34, 41) candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
Error:(137, 6) error: no matching function for call to 'v3Scale'
Error:(142, 15) error: no matching function for call to 'combine'
Information:(34, 41) candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
        GLM_FUNC_QUALIFIER detail::tvec3<T, P> co
Error:(144, 15) error: no matching function for call to 'combine'
Error:(148, 6) error: no matching function for call to 'v3Scale'
Error:(129, 6) error: no matching function for call to 'v3Scale'
Error:(124, 17) error: no viable overloaded '='
Information:(43, 26) note: candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
Error:(133, 15) error: no matching function for call to 'combine'
Information:(34, 41) note: candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
Error:(137, 6) error: no matching function for call to 'v3Scale'
Information:(43, 26) note: candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
Error:(142, 15) error: no matching function for call to 'combine'
Information:(34, 41) note: candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
Error:(144, 15) error: no matching function for call to 'combine'
Information:(34, 41) note: candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')
Error:(148, 6) error: no matching function for call to 'v3Scale'
Information:(43, 26) note: candidate template ignored: deduced conflicting types for parameter 'T' ('float' vs. 'double')

**Comment by Groovounet** [comment]
Erm that doesn't show the GLM messages... what version of GLM are you using?

Maybe try #define GLM_MESSAGES before including glm.hpp.
