### ISSUE TITLE
glm::axisAngle returns NaN

### ISSUE THREAD

**Issue by Morloth1274** [g-truc/glm#638]
When given certain rotation matrixes, the glm::axisAngle function sometimes returns the right rotation vector but the angle is NaN. The rotation matrix in question is:

[1 0 -0.0174559 0 ]
[0 1 0 0 ]
[0.0174559 0 1 0 ]
[0 0 0 1 ]

Which gives the rotation vector: (0, -1, 0) and the angle: NaN.

Here is the test code:
[glm bug.cpp.txt](https://github.com/g-truc/glm/files/1072258/glm.bug.cpp.txt)

When I translate the rotation matrix to a quaternion it works just fine and returns the right values.

**Comment by Groovounet** [comment]
This issue should be fixed in master branch. 

Thanks for reporting,
Christophe
