### ISSUE TITLE
Packaging glm with conan

### ISSUE THREAD

**Issue by dimi309** [g-truc/glm#641]
Hello,

I've been using GLM for a while. Recently, I have packaged it with conan, an open source C/C++ package manager and placed the package on bintray:

https://bintray.com/dimi309/conan-packages/glm%3Adimi309

I hope you don't mind :)
The package is in the process of being evaluated for inclusion into a curated repository on bintray, which is to only contain good quality conan packages. I am writing to ask you if you would be interested in maintaining this package directly. I can provide you with the [packaging code](https://github.com/dimi309/conan-packages/tree/master/glm) (actually, you can just copy it, since it's open source) or even introduce a pull request with some non-intrusive changes that would allow you to package it directly from the main glm repository.

**Comment by Groovounet** [comment]
I am pretty sure I don't want to maintain that package but if you want to maintain it from this repository why not. That means that if there is bug report, I'll assign them to you :D.

Could you do a PR and create a subdirectory in "glm/util" with coana package?

Thanks!

**Comment by dimi309** [comment]
Sounds good. Thanks!
I'll make a pull request. Is it ok if I copy paste the glm logo from your page and add it to the package on bintray?

**Comment by Groovounet** [comment]
Sure feel free! 
The logo is here: https://github.com/g-truc/glm/blob/master/doc/manual/logo-mini.png
There is a high resolution logo here: https://github.com/g-truc/lib-website/blob/master/glm/image/logo.png

**Comment by dimi309** [comment]
Thanks again! I'll come back with the pull request.
