### ISSUE TITLE
1d noise (perlin or simplex)? how to seed noise functions?

### ISSUE THREAD

**Issue by powof2** [g-truc/glm#644]
hi,
thank you for this great library.

i searched glm and found that there is no 1d noise (perlin or simplex), why is that?

with current noise functions, how do i seed them? should i generate a random position (2d position for example), use that position as start point (or seed) to make noise?

thank you.

**Comment by Groovounet** [comment]
There is no 1D noise because nobody did it. :D 

Yes you generate a random (of the approach you wants) 2d position as a seed. I think you also need a (random) scaling factor.

Thanks,
Christophe
