### ISSUE TITLE
QR decomposition proposition

### ISSUE THREAD

**Issue by unordinateur** [g-truc/glm#645]
Hi!

While working with glm on a project; I encountered a need to do RQ (and QR) decomposition of some matrices.

I coded some functions to do that; that I would like to share them back to glm so you can integrate them to the library.

How can I do that? (That would be the first time I contribute to an open source project, so I'm not familiar with the usual procedures for that.)

Thank you!

**Comment by Groovounet** [comment]
Hi,

For that you need to do a pull request (PR). To write the feature, create an extension in here https://github.com/g-truc/glm/tree/master/glm/gtx, let's say call it qr_decomposition and create a test that should go here https://github.com/g-truc/glm/tree/master/test/gtx.

When you create the issue, the test infrastructure of the repository will run the test so you can see it's ok on others platforms that you own platform. 

If the PR is not perfect, it's ok, do what you thing you should do and I'll take it from there if it's reasonable. 
I might comment the PR for involvement in which case you might have to do a second iteration. 

Thanks for contributing!

**Comment by unordinateur** [comment]
Great, thanks!
I'll tell you when it's done.

**Comment by unordinateur** [comment]
So I just did a pull request with my implementations! (PR #654)

After a few fixes, it now passes all the tests, so it should be able to be merged without any problems! :)

Vincent
