### ISSUE TITLE
Fix to allow inheriting from vec<> classes

### ISSUE THREAD

**Issue by adrianstephens** [g-truc/glm#650]
Hi
I found when I inherit from the vec<> classes glm treats the values as scalars because they no longer exactly match the vec<L,T,P> signature.
I've got a fix here that I wanted to give you if you'd like them. I'm not sure if this is something you need to authorise first, or if I just create a pull request?

**Comment by Groovounet** [comment]
Yes please create a pull request.

Thanks,
Christophe

**Comment by Groovounet** [comment]
I created a test and inheritance seems to work just fine...

Thanks,
Christophe
