### ISSUE TITLE
Compilation error in 0.9.8 branch

### ISSUE THREAD

**Issue by sanjay-nambiar** [g-truc/glm#652]
I upgraded to 0.9.8 from 0.9.7 and started getting this compilation error:

> Cannot open include file: '../detail/intrinsic_matrix.hpp': No such file or directory

I investigated the issue a bit further and found that glm/gtx/simd_mat4.hpp conditionally includes 
../detail/intrinsic_matrix.hpp. Checking the source code repository, I see that this file is present in 0.9.7 but removed from 0.9.8. Since that file is not present in the directory, I think it is incorrect to have that as a conditional include in the source file.

**Comment by Groovounet** [comment]
This issue is fixed in 0.9.8 branch for GLM 0.9.8.5 release

Thanks for reporting,
Christophe
