### ISSUE TITLE
Compiler warning related to __has_feature definition

### ISSUE THREAD

**Issue by alexanderbock** [g-truc/glm#655]
On MSVC 2017.2, C4574  'identifier' is defined to be '0': did you mean to use '#if identifier'?  is thrown in https://github.com/fmtlib/fmt (https://github.com/fmtlib/fmt/pull/539) as it checks for existence of `__has_feature` .

https://github.com/g-truc/glm/blob/master/glm/detail/setup.hpp#L768:
```cpp
#ifndef __has_feature
#	define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif
```

Is that compatibility reason still valid?

**Comment by Groovounet** [comment]
I think you are right, this code is obsolete. Each time __has_feature is used it's protected by a check that the compiler is Clang.

Thanks for contributing,
Christophe
