### ISSUE TITLE
templated quat initialized with basic type

### ISSUE THREAD

**Issue by padeler** [g-truc/glm#656]
In line [383](https://github.com/g-truc/glm/blob/master/glm/gtc/quaternion.inl#L383), the templated tquat is initialized with basic type instead of the templated type. This is an issue when using GLM with a library like CERES.

The line should be changed to: 
```cpp
	return tquat<T, P>(T(1) T(0), T(0), T(0));
```

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9 release.

Thanks fore reporting,
Christophe
