### ISSUE TITLE
glm::vec<L,T,P>::length() should be marked constexpr where supported

### ISSUE THREAD

**Issue by aheysse** [g-truc/glm#657]
As far as I can tell, there is no way to get the length of a glm::vec without using glm::vec::length(). Marking length as constexpr when compilers support it would allow for compile time deduction of the function. This could be useful when writing template code that consumes glm::vec.

Cheers

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9 release.

Thanks for contributing,
Christophe
