### ISSUE TITLE
Can't compile on linux?

### ISSUE THREAD

**Issue by WarpspeedSCP** [g-truc/glm#660]
When I run make, the build fails with this-

`Scanning dependencies of target glm_dummy
[ 33%] Building CXX object glm/CMakeFiles/glm_dummy.dir/detail/glm.cpp.o
c++: error: unrecognized command line option ‘-Weverything’
glm/CMakeFiles/glm_dummy.dir/build.make:62: recipe for target 'glm/CMakeFiles/glm_dummy.dir/detail/glm.cpp.o' failed
make[2]: *** [glm/CMakeFiles/glm_dummy.dir/detail/glm.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'glm/CMakeFiles/glm_dummy.dir/all' failed
make[1]: *** [glm/CMakeFiles/glm_dummy.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

Is there a fix?

**Comment by SeriousAlexej** [comment]
Got the same problem.
Try to change CMakeLists.txt, line 17 to this:
`add_definitions(-D_CRT_SECURE_NO_WARNINGS)`

**Comment by Groovounet** [comment]
This issue should be fixed.

Thanks for contributing,
Christophe
