### ISSUE TITLE
Constexpr matrix

### ISSUE THREAD

**Issue by doginthenight** [g-truc/glm#661]
According to issue #493 vectors, matrices and quaternions can be constructed in constant expressions since GLM 0.9.8. 

However, compilation fails when I try to compile any of the following lines:
`constexpr glm::mat2x2 a;`
`constexpr glm::mat2x2 a = glm::mat2x2(1.f,2.f,3.f,4.f);`
`constexpr glm::mat2x2 a(1.f,2.f,3.f,4.f);`
In all cases the compiler complains about a call to a non-constexpr function.

I noticed that the `GLM_CONSTEXPR` declarations were removed from the mat2x2 constructors in commit d0c4bbaef7d04c5b11e906924a73f645ba37b183, while `GLM_CONSTEXPR_CTOR` was added to the empty constructor in commit 6d302792ab849193aaeaec27b0ef1460484a974b.

How do I properly use matrices in a constant expression?

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.1 release.

Thanks for contributing,
Christophe
