### ISSUE TITLE
master fails to compile with gcc version 6.3.1

### ISSUE THREAD

**Issue by fgfuchs** [g-truc/glm#664]
Compiling the following cpp file (that only includes glm.hpp):

#include <glm/glm.hpp>

works fine with gcc versions 4.9.4 and 5.4.0, but gives the following errors with gcc version 6.3.1:

glm/detail/type_vec4_simd.inl: In constructor ‘constexpr glm::vec<4, T, P>::vec(T) [with T = int; glm::precision P = (glm::precision)4]’:
glm/detail/type_vec4_simd.inl:381:22: error: call to non-constexpr function ‘__m128i _mm_set1_epi32(int)’
   data(_mm_set1_epi32(_s))

glm/detail/type_vec4_simd.inl: In constructor ‘constexpr glm::vec<4, T, P>::vec(X, Y, Z, W) [with X = int; Y = int; Z = int; W = int; T = float; glm::precision P = (glm::precision)4]’:
glm/detail/type_vec4_simd.inl:448:24: error: call to non-constexpr function ‘__m128 _mm_castsi128_ps(__m128i)’
   data(_mm_castsi128_ps(_mm_set_epi32(_w, _z, _y, _x)))

**Comment by BartekkPL** [comment]
Latest changes provide some compile error in my case too (sample error below). I download newest version of glm 2-3 times per week and today glm version doesn't work:

```
../glm/detail/type_vec4_simd.inl: In constructor ‘constexpr glm::vec<4, T, P>::vec(T) [with T = float; glm::precision P = (glm::precision)5u]’:
/glm/detail/type_vec4_simd.inl:344:21: error: call to non-constexpr function ‘__m128 _mm_set1_ps(float)’
   : data(_mm_set1_ps(_s))
```

**Comment by capitalknew** [comment]
In MingW W64 too

**Comment by Klowner** [comment]
Just ran into this too, looks like 950d2261 introduced the problem. aa026cc0 still works fine for now.

**Comment by fwsGonzo** [comment]
Can confirm my builds broke to this change too

**Comment by Groovounet** [comment]
This issue should be fixed on master branch.

Thanks for reporting,
Christophe
