### ISSUE TITLE
Can't see values for vec or mat in the debugger

### ISSUE THREAD

**Issue by derekhendrickx** [g-truc/glm#665]
Hey!

It seems I can't see the values for `glm::vec` or `glm::mat` in the debugger. I'm using Visual Studio Code, my debugger is `lldb` and my compiler is `clang`.

![2017-07-28_12-03-03](https://user-images.githubusercontent.com/1218149/28726007-6067bc64-738d-11e7-84b0-142e8aa8cc4d.png)

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.1 release.

You can define GLM_FORCE_XYZW_ONLY to ensure that values are trivial to debug.

Thanks for reporting,
Christophe
