### ISSUE TITLE
Split headers to improve compilation time

### ISSUE THREAD

**Issue by skhoroshavin** [g-truc/glm#670]
Modern versions of GLM incur quite hefty compilation time. I saw recommendation to use `glm/fwd.hpp`, unfortunatelly it doesn't work when one needs to declare _types_ that depend on vectors and matrices. As a (dirty) workaround we use `glm/detail/types_vec.hpp` etc, and it does the trick, but it would be much better to have these headers available in public part. 

Also, `glm/gtc/quaternion.hpp` includes glm/vec*.h (which inhibits attempts to reduce compilation time), while it would be much better to have `glm/gtc/types_quaternion.hpp`, declaring just quaternion type, and separate `glm/gtc/quaternion.hpp` defining all needed operations.

**Comment by Groovounet** [comment]
In master branch, I split headers for vec types for fine grain inclusion of what an application need.
I am falling the same approach for EXT extensions. I didn't reach the point for quaternions yet but this is coming along with quaternions being promoted as EXT extensions.

Thanks for contributing,
Christophe
