### ISSUE TITLE
GLM: Using GLM_FORCE_CXX11/CXX14 but there is no known version of Visual C++ compiler that fully supports C++11/C++14

### ISSUE THREAD

**Issue by ttnghia** [g-truc/glm#673]
Hello,
Whenever I compile my code, I always get the compiler warnings:

`GLM: Using GLM_FORCE_CXX11 but there is no known version of Visual C++ compiler that fully supports C++11`

or:
`GLM: Using GLM_FORCE_CXX14 but there is no known version of Visual C++ compiler that fully supports C++14`

That annoys me. I am using VS2017 and I don't think VS2017 doesn't support C++11/C++14 fully. It seems that the GLM setup always prints out such warnings whenever it detects C++11/C++14 in MSVC compiler.

**Comment by Groovounet** [comment]
Why do you use GLM_FORCE_CXX11? 
Automatically GLM will use the version of C++ that the compiler support or that is requested to the compiler. GLM_FORCE_CXX11 & co is only for funky compilers or to restrict the feature set of C++ features used by GLM with more capable compilers.

Thanks,
Christophe
