### ISSUE TITLE
Too many pragma Message

### ISSUE THREAD

**Issue by nobledemon** [g-truc/glm#677]
When I compile, this message pops up around 500 times (glm is included in several parts of my code):
"GLM: Using GLM_FORCE_CXX11 but there is no known version of Visual C++ compiler that fully supports C++11"

Is there a way to deactivate it or only make it appear just once? It makes really hard to debug the rest of the code and unlike warnings it can't be hidden. Or at least I'm not aware of any way to do so.

Thanks.

**Comment by Groovounet** [comment]
Maybe it's just a legitimate message? :D 

Are you using GLM_FORCE_MESSAGES?
Why are you using GLM_FORCE_CXX11?

**Comment by nobledemon** [comment]
Well, you are actually right, I actually didn't need GLM_FORCE_CXX11. Removed it and I don't have any messages. 

Thanks.
