### ISSUE TITLE
install(EXPORT) versus export(PACKAGE)

### ISSUE THREAD

**Issue by MathiasMagnus** [g-truc/glm#678]
Hi!

I think it would make far more sense to use the [install(EXPORT)](https://cmake.org/cmake/help/latest/command/install.html#id7) syntax to populate the user package registry as opposed to the [export(PACKAGE)](https://cmake.org/cmake/help/latest/command/export.html?highlight=) syntax. The latter registers a file which references the current build directory, which might very well be deleted, as the user might expect "_well, if I installed the thing, then that's what will be picked up by the find_package command; the build directory is only a temporary thing, as opposed to the install dir_". The prior references the install dir.

Otherwise, nice work with the project. Up until now I still lived in the old days, when it was actually documented, that there's no way of populating the package registry in CMake terms. I only came to realize there's actually two ways. :)

Keep up the good work!

**Comment by Groovounet** [comment]
I don't really have the experience with this so I would suggest to make a PR. :D 

Thanks,
Christophe

**Comment by Groovounet** [comment]
This issue has been inactive for about a year, closing.

Thanks,
Christophe
