### ISSUE TITLE
warning C4309

### ISSUE THREAD

**Issue by rextimmy** [g-truc/glm#679]
I am getting a lot of 
`warning C4309: 'static_cast': truncation of constant value`
coming from gtc/bitfield.inl when compiling with VS 2017 64bit, not sure which glm update this started happening in but it's fairly recent or maybe it's from a recent visual studio update, not sure which one.

*Edit oops sorry forgot to link the code producing it [https://github.com/g-truc/glm/blob/master/glm/gtc/bitfield.inl#L88-L102](url) & [https://github.com/g-truc/glm/blob/master/glm/gtc/bitfield.inl#L175-L188](url)

**Comment by Groovounet** [comment]
Hi,

Are you sure that the issue didn't show up when you started using VS 2017?

Thanks,
Christophe

**Comment by akaltar** [comment]
Hello,

I am still seeing this warning come up on VS2015CE on x64 builds on lines 88-102 of bitfield.inl
https://github.com/g-truc/glm/blob/master/glm/gtc/bitfield.inl#L88-L102

It seems the fix for half of the lines was missed. I'll create a quick pull req for this.
