### ISSUE TITLE
Having GLM_FORCE_DEPTH_ZERO_TO_ONE as seperate functions

### ISSUE THREAD

**Issue by KarimIO** [g-truc/glm#680]
Hey there! Thanks for all the great work on GLM!

This is more of a suggestion than an issue. I'd like to be able to choose whether I use [0..1] or [-1..1] depth at runtime, as my engine uses different dynamic libraries for each of vulkan, directx, and opengl. Could there be seperate functions for it? Perhaps you could even wrap those in a new GLM_BOTH_DEPTH_METHODS define to provide both without adding more functions if that's an issue.

**Comment by Groovounet** [comment]
This feature is now supported in GLM master branch for GLM 0.9.9 release.

Thanks for contributing,
Christophe
