### ISSUE TITLE
glm::log2<int>() returns wrong value

### ISSUE THREAD

**Issue by ajuvolkov** [g-truc/glm#683]
Hi everyone!

I faced with one strange results when I call glm::log2 with integer argument
For example:

```
int v = 1024;
int a = glm::log2(v);
```

You will have value 6 in 'a' variable!
It is really surprised me, and I walked throught glm source code and found this:

```
template <typename genType>
genType log2(genType Value)
{
    return std::log(Value) * static_cast<genType>(1.4426950408889634073599246810019);
}
```

When you use integer argument, you will have wrong cast from floating point constant and get unexpected results

**Comment by Groovounet** [comment]
Hi,
Did you include <glm/gtc/integer.hpp>?
On master branch glm::log2 returns 10 as expected.

A static assert was missing to tell that <glm/gtc/integer.hpp> needs to be included for integer values. This is fixed.

Thanks,
Christophe
