### ISSUE TITLE
glm::step doesn't work with scalars

### ISSUE THREAD

**Issue by pdagobert** [g-truc/glm#684]
Using step with scalars won't compile:
```
glm::step( 0.0f, 1.0f )
```
Happens because glm::step is using glm::lessThan internally and lessThan has no scalar version in GLSL (and thus in GLM). Yet, glm::step has a scalar version in GLSL.

I'm not sure if this is intended or not, since the spec is quite ambiguous about this.

**Comment by Groovounet** [comment]
This issue is fixed in master branch.

Thanks for contributing,
Christophe
