### ISSUE TITLE
acsch incorrectly defined

### ISSUE THREAD

**Issue by Zuzu-Typ** [g-truc/glm#698]
So when working on a Python redistribution of GLM, I noticed an accidental recursion in reciprocal.inl.
```
[...]
// acsch
template<typename genType>
GLM_FUNC_QUALIFIER genType acsch(genType x)
{
	GLM_STATIC_ASSERT(std::numeric_limits<genType>::is_iec559, "'acsch' only accept floating-point values");
	return acsch(genType(1) / x);
}
[...]
```
it should be 

    return asinh(genType(1) / x);

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9 release.

Thanks for reporting,
Christophe
