### ISSUE TITLE
CUDA __device__ / __host__ annotation warnings

### ISSUE THREAD

**Issue by chaosink** [g-truc/glm#702]
It seems that these warnings come back again...

CUDA version: 9.0

glm version:
* Merge pull request #693 from cleeus/fix-exp2-precision-with-cxx11
* 0f956f6dbce485b2e71a8b901db0699f82ac3633

Version 0.9.8.5 has no this problem on my PC.

**Comment by chaosink** [comment]
It seems that when these warnings disappear, vectors as arguments of host functions will cause segmentation fault.

Am I right?

**Comment by n8vm** [comment]
Also running into this bug. Including glm in a CUDA 10 application results in the following warnings:

> glm/glm/detail/type_vec2.hpp(94): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec2.hpp(94): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec2.hpp(95): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec2.hpp(95): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec2.hpp(143): warning: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec2.hpp(143): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec3.hpp(98): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec3.hpp(98): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec3.hpp(99): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec3.hpp(99): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec3.hpp(176): warning: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec3.hpp(176): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec4.hpp(97): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec4.hpp(97): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec4.hpp(98): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec4.hpp(98): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec4.hpp(249): warning: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec4.hpp(249): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat2x2.hpp(35): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat2x2.hpp(35): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat2x3.hpp(36): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat2x3.hpp(36): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat2x4.hpp(36): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat2x4.hpp(36): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat3x2.hpp(36): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat3x2.hpp(36): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat3x3.hpp(35): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat3x3.hpp(35): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat3x4.hpp(36): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat3x4.hpp(36): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat4x2.hpp(36): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat4x2.hpp(36): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat4x3.hpp(36): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat4x3.hpp(36): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat4x4.hpp(35): warning: __device__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_mat4x4.hpp(35): warning: __host__ annotation is ignored on a function("mat") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec1.hpp(95): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec1.hpp(95): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec1.hpp(96): warning: __device__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec1.hpp(96): warning: __host__ annotation is ignored on a function("vec") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec1.hpp(132): warning: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
> 
> glm/glm/detail/type_vec1.hpp(132): warning: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

**Comment by christophe-lunarg** [comment]
This looks like very deprecated so closing.
