### ISSUE TITLE
Operations on vec* yield incorret results in host funcions in CUDA .cu files

### ISSUE THREAD

**Issue by chaosink** [g-truc/glm#705]
GLM version: 0.9.8.5
CUDA version: 9.0
GCC versoin: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

In host functions in CUDA `.cu` files, the following operations on `vec*` yield incorrect results:
* plus of two `vec*`
* multiple of `vec*` and `float`

For example,
```
	glm::vec4 u(1.f, 2.f, 3.f, 4.f), v(5.f, 6.f, 7.f, 8.f);
	u = u + v;
	cout << u.x << " " << u.y << " " << u.z << endl;
	v = v * 2.f;
	cout << v.x << " " << v.y << " " << v.z << endl;
```
gives:
```
9.59572e-27 3.37224e-29 3.52448e+13
9.59572e-27 3.37224e-29 3.52448e+13
```

This problem only happens in host funcions. In device functions, `vec*` works well.

- - -

The testing I did shows that only `vec*` have this problem. Other types like `uvec*`, `ivec*`, `dvec*`, `u8vec*`, `i8vec*` give correct results.

- - -

# This problem has gone today without knowing the reason...

Yestoday it really makes me upset...

- - -

Just now I reset my code to yestoday's version using git. And the problem comes again.
Don't know why for now.
Interesting...

- - -

The latest GLM has no this problem.
But after copying the data into GPU memory, the order of bytes is out of my expectation.
Maybe for alignment or some other reasons...

- - -

# OK. I have found the exact file change causing the problem gone!

After I tested each version until now, I **finally** found what makes the problem gone!

It's all because the compile option `-O`.

When the option is `-O3`, `-O2`, `-O1`, the problem doesn't occur.

However if the option is `-O0` or remove this option, the problem occurs agin.

Why the problem has such relation with optimization option?

- - -

And here lefts the problem of the latest GLM:
After copying the data into GPU memory, the order of bytes is out of my expectation maybe for alignment or some other reasons...

Maybe I should open another issue.

**Comment by christophe-lunarg** [comment]
Hi,
If this is still an issue, please submit a PR.
Thanks!
