### ISSUE TITLE
CUDA 9 and invalid memory access

### ISSUE THREAD

**Issue by asterycs** [g-truc/glm#707]
Hello everyone,

I am experiencing some issues with CUDA 9 and glm. In my project I pass some objects that include glm-types as member variables as parameters to __ global __ functions.

I tried to upgrade my project to CUDA version 9. After doing so I experience some invalid memory accesses on said objects. Downgrading to CUDA 8 again indeed makes problems disappear.

Memory checker show interestingly that some invalid memory accesses happen when accessing non-glm type member variables as well. This makes me believe that this could be an issue with alignment.

I have no idea how to help out with this other than reporting the behavior. If you need more information I'd be glad to help.

**Comment by christophe-lunarg** [comment]
Hi,
If this is still an issue, please submit a PR.
Thanks!
