### ISSUE TITLE
glm gives a wrong result when transforming a 3D vector using a rotation matrix

### ISSUE THREAD

**Issue by pnt1614** [g-truc/glm#718]
```
glm::vec4 x = glm::vec4(0.0f, 0.0f, 1.0f, 0.0f);
glm::vec4 y = glm::vec4(0.0f, 1.0f, 0.0f, 0.0f);
glm::vec4 z = glm::vec4(-1.0f, 0.0f, 0.0f, 0.0f);
glm::vec4 t(0.0f, 0.0f, 0.0f, 1.0f);

glm::mat4 rot(x, y, z, t);
glm::vec4 test = rot * glm::vec4(10.0f, 0.0f, 0.0f, 1.0f);
```

The "test" varible should be (0.0f, 0.0f, -10.0f, 1.0f) but the returned result is (0.0f, 0.0f, 10.0f, 1.0f). Is this a bug of glm?

**Comment by CaptainCarrot** [comment]
GLM stores matrices in the column-major form and the constructor you're using naturally takes the columns of the matrix, so the result is correct. You seem to be expecting it to take rows instead, and the result therefore differs from your expectation.

**Comment by pnt1614** [comment]
thanks for the reply.
