### ISSUE TITLE
Behaviour of quaternions

### ISSUE THREAD

**Issue by n-paukov** [g-truc/glm#721]
I use quaternions for storing orientation of the objects and have a question about their behaviour.
When I run this code: 

```
void printAngles(quat q) {
	vector3 angles = eulerAngles(q);
	std::cout << degrees(angles.x) << " " << degrees(angles.y) << " " << degrees(angles.z) << std::endl;
}
...
glm::quat q(vector3(0, 0, 0));
printAngles(q);

q *= quat(vector3(0, glm::radians(5.0f), 0));
printAngles(q);

q *= quat(vector3(0, glm::radians(90.0f), 0));
printAngles(q);
```
as a result I have in the output:
```
0 -0 0 // At the beginning
0 5 0 // After 5 degrees rotation
180 85 180 // After another 90 degrees rotation
```

Yaw and roll values are changed too... Is there a way to get values in order to rotations without such transforms?
I just want to get 0 95 0.

Thank you very much for exciting math library!

**Comment by KageKirin** [comment]
If I remember well (and I guess Wikipedia is correct: https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation), your order of multiplication is wrong, i.e. the vector/quaternion to transform goes in the middle of the multiplication, with the rotation and its conjugate on both sides:
`q_t = q_rot * q(t) * conjugate(q_rot)`
