### ISSUE TITLE
Conan package for GLM

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [g-truc/glm#722]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by dimi309** [comment]
Hi @ZaMaZaN4iK,
GLM is already in conan-center (since I had gotten it accepted there some time ago, we decided to not add it to the bincrafters repositories).

**Comment by dimi309** [comment]
Also, the packaging code has already been accepted to the main repository: https://github.com/g-truc/glm/tree/master/util/conan-package

That is why there is no conan-glm repository anywhere.

**Comment by ZaMaZaN4iK** [comment]
Ohm i don't know how i missed it...

**Comment by dimi309** [comment]
Bintray search lets us down sometimes...
