### ISSUE TITLE
Fails to build with gcc 7.3

### ISSUE THREAD

**Issue by oSoMoN** [g-truc/glm#726]
[ 0%] Building CXX object glm/CMakeFiles/glm_dummy.dir/detail/glm.cpp.o
cd /tmp/glm-0.9.8.4/obj-x86_64-linux-gnu/glm && /usr/bin/c++ -D_CRT_SECURE_NO_WARNINGS -I/tmp/glm-0.9.8.4 -I/tmp/glm-0.9.8.4/test/external -I/tmp/glm-0.9.8.4/glm/.. -g -O2 -fdebug-prefix-map=/tmp/glm-0.9.8.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -pedantic -O2 -o CMakeFiles/glm_dummy.dir/detail/glm.cpp.o -c /tmp/glm-0.9.8.4/glm/detail/glm.cpp
In file included from /tmp/glm-0.9.8.4/glm/detail/type_int.hpp:6:0,
                 from /tmp/glm-0.9.8.4/glm/fwd.hpp:6,
                 from /tmp/glm-0.9.8.4/glm/glm.hpp:61,
                 from /tmp/glm-0.9.8.4/glm/detail/glm.cpp:4:
/tmp/glm-0.9.8.4/glm/detail/setup.hpp:456:100: note: #pragma message: GLM: GCC older than 4.6 has a bug presenting the use of rgba and stpq components
 # pragma message("GLM: GCC older than 4.6 has a bug presenting the use of rgba and stpq components")
                                                                                                    ^
In file included from /tmp/glm-0.9.8.4/glm/detail/type_vec4.inl:968:0,
                 from /tmp/glm-0.9.8.4/glm/detail/type_vec4.hpp:453,
                 from /tmp/glm-0.9.8.4/glm/vec4.hpp:6,
                 from /tmp/glm-0.9.8.4/glm/glm.hpp:70,
                 from /tmp/glm-0.9.8.4/glm/detail/glm.cpp:4:
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In static member function 'static glm::tvec4<float, (glm::precision)5> glm::detail::compute_vec4_div<float, (glm::precision)5, true>::call(const glm::tvec4<float, (glm::precision)5>&, const glm::tvec4<float, (glm::precision)5>&)':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:156:11: error: 'struct glm::tvec4<float, (glm::precision)5>' has no member named 'data'
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
           ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:156:31: error: 'const struct glm::tvec4<float, (glm::precision)5>' has no member named 'data'
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
                               ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:156:50: error: 'const struct glm::tvec4<float, (glm::precision)5>' has no member named 'data'
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
                                                  ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)5]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:367:3: error: class 'glm::tvec4<float, (glm::precision)5>' does not have any field named 'data'
   data(_mm_set1_ps(s))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)4]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:372:3: error: class 'glm::tvec4<float, (glm::precision)4>' does not have any field named 'data'
   data(_mm_set1_ps(s))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)3]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:377:3: error: class 'glm::tvec4<float, (glm::precision)3>' does not have any field named 'data'
   data(_mm_set1_ps(s))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T) [with T = int; glm::precision P = (glm::precision)5]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:399:3: error: class 'glm::tvec4<int, (glm::precision)5>' does not have any field named 'data'
   data(_mm_set1_epi32(s))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T) [with T = int; glm::precision P = (glm::precision)4]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:404:3: error: class 'glm::tvec4<int, (glm::precision)4>' does not have any field named 'data'
   data(_mm_set1_epi32(s))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T) [with T = int; glm::precision P = (glm::precision)3]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:409:3: error: class 'glm::tvec4<int, (glm::precision)3>' does not have any field named 'data'
   data(_mm_set1_epi32(s))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T, T, T, T) [with T = float; glm::precision P = (glm::precision)5]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:431:3: error: class 'glm::tvec4<float, (glm::precision)5>' does not have any field named 'data'
   data(_mm_set_ps(d, c, b, a))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T, T, T, T) [with T = float; glm::precision P = (glm::precision)4]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:436:3: error: class 'glm::tvec4<float, (glm::precision)4>' does not have any field named 'data'
   data(_mm_set_ps(d, c, b, a))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(T, T, T, T) [with T = float; glm::precision P = (glm::precision)3]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:441:3: error: class 'glm::tvec4<float, (glm::precision)3>' does not have any field named 'data'
   data(_mm_set_ps(d, c, b, a))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = int; glm::precision P = (glm::precision)5]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:447:3: error: class 'glm::tvec4<int, (glm::precision)5>' does not have any field named 'data'
   data(_mm_set_epi32(d, c, b, a))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = int; glm::precision P = (glm::precision)4]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:453:3: error: class 'glm::tvec4<int, (glm::precision)4>' does not have any field named 'data'
   data(_mm_set_epi32(d, c, b, a))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = int; glm::precision P = (glm::precision)3]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:459:3: error: class 'glm::tvec4<int, (glm::precision)3>' does not have any field named 'data'
   data(_mm_set_epi32(d, c, b, a))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = float; glm::precision P = (glm::precision)5]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:465:3: error: class 'glm::tvec4<float, (glm::precision)5>' does not have any field named 'data'
   data(_mm_castsi128_ps(_mm_set_epi32(d, c, b, a)))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = float; glm::precision P = (glm::precision)4]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:471:3: error: class 'glm::tvec4<float, (glm::precision)4>' does not have any field named 'data'
   data(_mm_castsi128_ps(_mm_set_epi32(d, c, b, a)))
   ^~~~
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl: In constructor 'glm::tvec4<T, P>::tvec4(A, B, C, D) [with A = int; B = int; C = int; D = int; T = float; glm::precision P = (glm::precision)3]':
/tmp/glm-0.9.8.4/glm/detail/type_vec4_simd.inl:477:3: error: class 'glm::tvec4<float, (glm::precision)3>' does not have any field named 'data'
   data(_mm_castsi128_ps(_mm_set_epi32(d, c, b, a)))
   ^~~~
In file included from /tmp/glm-0.9.8.4/glm/detail/../detail/func_exponential.inl:144:0,
                 from /tmp/glm-0.9.8.4/glm/detail/../detail/func_exponential.hpp:103,
                 from /tmp/glm-0.9.8.4/glm/detail/../detail/func_geometric.inl:4,
                 from /tmp/glm-0.9.8.4/glm/detail/../detail/func_geometric.hpp:113,
                 from /tmp/glm-0.9.8.4/glm/detail/../geometric.hpp:6,
                 from /tmp/glm-0.9.8.4/glm/detail/func_matrix.inl:4,
                 from /tmp/glm-0.9.8.4/glm/detail/func_matrix.hpp:149,
                 from /tmp/glm-0.9.8.4/glm/detail/type_mat2x2.inl:4,
                 from /tmp/glm-0.9.8.4/glm/detail/type_mat2x2.hpp:182,
                 from /tmp/glm-0.9.8.4/glm/mat2x2.hpp:6,
                 from /tmp/glm-0.9.8.4/glm/glm.hpp:71,
                 from /tmp/glm-0.9.8.4/glm/detail/glm.cpp:4:
/tmp/glm-0.9.8.4/glm/detail/../detail/func_exponential_simd.inl: In static member function 'static glm::tvec4<float, (glm::precision)5> glm::detail::compute_sqrt<glm::tvec4, float, (glm::precision)5, true>::call(const glm::tvec4<float, (glm::precision)5>&)':
/tmp/glm-0.9.8.4/glm/detail/../detail/func_exponential_simd.inl:28:11: error: 'struct glm::tvec4<float, (glm::precision)5>' has no member named 'data'
    result.data = glm_vec4_sqrt_lowp(v.data);
           ^~~~
/tmp/glm-0.9.8.4/glm/detail/../detail/func_exponential_simd.inl:28:39: error: 'const struct glm::tvec4<float, (glm::precision)5>' has no member named 'data'
    result.data = glm_vec4_sqrt_lowp(v.data);
                                       ^~~~
In file included from /tmp/glm-0.9.8.4/glm/detail/func_matrix.inl:399:0,
                 from /tmp/glm-0.9.8.4/glm/detail/func_matrix.hpp:149,
                 from /tmp/glm-0.9.8.4/glm/detail/type_mat2x2.inl:4,
                 from /tmp/glm-0.9.8.4/glm/detail/type_mat2x2.hpp:182,
                 from /tmp/glm-0.9.8.4/glm/mat2x2.hpp:6,
                 from /tmp/glm-0.9.8.4/glm/glm.hpp:71,
                 from /tmp/glm-0.9.8.4/glm/detail/glm.cpp:4:
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl: In function 'typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type glm::outerProduct(const vecTypeA<T, P>&, const vecTypeB<T, P>&) [with T = float; glm::precision P = (glm::precision)5; vecTypeA = glm::tvec4; vecTypeB = glm::tvec4; typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type = glm::tmat4x4<float, (glm::precision)5>]':
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:67:27: error: 'const struct glm::tvec4<float, (glm::precision)5>' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                           ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:67:35: error: 'const struct glm::tvec4<float, (glm::precision)5>' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                   ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:67:79: error: 'glm::tmat4x4<float, (glm::precision)5>::col_type {aka struct glm::tvec4<float, (glm::precision)5>}' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                                                               ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl: In function 'typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type glm::outerProduct(const vecTypeA<T, P>&, const vecTypeB<T, P>&) [with T = float; glm::precision P = (glm::precision)4; vecTypeA = glm::tvec4; vecTypeB = glm::tvec4; typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type = glm::tmat4x4<float, (glm::precision)4>]':
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:75:27: error: 'const struct glm::tvec4<float, (glm::precision)4>' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                           ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:75:35: error: 'const struct glm::tvec4<float, (glm::precision)4>' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                   ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:75:79: error: 'glm::tmat4x4<float, (glm::precision)4>::col_type {aka struct glm::tvec4<float, (glm::precision)4>}' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                                                               ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl: In function 'typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type glm::outerProduct(const vecTypeA<T, P>&, const vecTypeB<T, P>&) [with T = float; glm::precision P = (glm::precision)3; vecTypeA = glm::tvec4; vecTypeB = glm::tvec4; typename glm::detail::outerProduct_trait<T, P, colType, rowType>::type = glm::tmat4x4<float, (glm::precision)3>]':
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:83:27: error: 'const struct glm::tvec4<float, (glm::precision)3>' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                           ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:83:35: error: 'const struct glm::tvec4<float, (glm::precision)3>' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                   ^~~~
/tmp/glm-0.9.8.4/glm/detail/func_matrix_simd.inl:83:79: error: 'glm::tmat4x4<float, (glm::precision)3>::col_type {aka struct glm::tvec4<float, (glm::precision)3>}' has no member named 'data'
   glm_mat4_outerProduct(c.data, r.data, *reinterpret_cast<__m128(*)[4]>(&m[0].data));
                                                                               ^~~~
glm/CMakeFiles/glm_dummy.dir/build.make:89: recipe for target 'glm/CMakeFiles/glm_dummy.dir/detail/glm.cpp.o' failed

**Comment by oSoMoN** [comment]
Nevermind, this is already fixed by https://github.com/g-truc/glm/commit/dd48b56e44d699a022c69155c8672caacafd9e8a.

**Comment by arteniioleg** [comment]
I get the same error with [0.9.8.5](https://github.com/g-truc/glm/releases)
`0.9.9-a2` works
