### ISSUE TITLE
Compilation warning glm 0.9.8.5 with visual studio 2017

### ISSUE THREAD

**Issue by SteveBoisvert** [g-truc/glm#729]
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec2.hpp(45): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec2.hpp(206): note: see the reference to model class instantiation 'glm :: tvec2 <T, P>' in progress compilation
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec2.hpp(46): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec2.hpp(47): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec3.hpp(45): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec3.hpp(227): note: see the reference to model class instantiation 'glm :: tvec3 <T, P>' in progress compilation
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec3.hpp(46): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec3.hpp(47): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec4.hpp(45): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec4.hpp(272): note: see the reference to model class instantiation 'glm :: tvec4 <T, P>' in progress compilation
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec4.hpp(46): warning C4201: non-standard extension used: struct / union without name
..\glm\glm-0.9.8.5\glm\glm\detail\type_vec4.hpp(47): warning C4201: non-standard extension used: struct / union without name

**Comment by Groovounet** [comment]
This is because you are building your project using C++ language extensions but using /W4 warnings.

If you use language extensions, GLM uses these extensions, if not it doesn't. Add /Za to you compilation parameters or use /W3 warnings to be consistent with your build arguments.

Thanks.
