### ISSUE TITLE
Bad Index in Getting Started Guide?

### ISSUE THREAD

**Issue by dbrakman** [g-truc/glm#733]
In an attempt to start using GLM, I visited the Getting Started Guide at [https://glm.g-truc.net/0.9.2/api/a00001.html](https://glm.g-truc.net/0.9.2/api/a00001.html). The first code sample defines a function foo(), which I renamed main() so that I could compile and run it. The code below is saved as sample.cpp:

```
#include <glm/glm.hpp>

int main()
{
        glm::vec4 Position = glm::vec4(glm::vec3(0.0), 1.0);
        glm::mat4 Model = glm::mat4(1.0);
        Model[4] = glm::vec4(1.0, 1.0, 0.0, 1.0);
        glm::vec4 Transformed = Model * Position;
        return 0;
}
```

After running the shell commands:

```
$ g++ -std=c++14 -g sample.cpp -o sample
$ ./sample
```

I get the error:
```
Assertion failed: (i < this->length()), function operator[], file /usr/local/include/glm/detail/type_mat4x4.inl, line 228.
Abort trap: 6
```

When stepping through with gdb, the sample code errors out after evaluating line 7, below:
```
Model[4] = glm::vec4(1.0, 1.0, 0.0, 1.0);
```

The error message and corresponding lines in sample.cpp and type_mat4x4.inl seem to indicate an attempt to write to memory not owned by the process. Is it simply that the 4x4 matrix should be indexed as `Model[3]` instead of `Model[4]`?

I'm not clear on the interaction between GLM and OpenGL, but if it's relevant, I'm running this code on a Mid-2015 Macbook Pro using the native OpenGL version 2.1 and running High Sierra 10.13.3.

**Comment by Groovounet** [comment]
You are referencing a pretty old version of GLM, maybe https://glm.g-truc.net/0.9.8/api/index.html will do better for you.

```Model[4]``` => should be Model[3]
