### ISSUE TITLE
Removal of default initialization of vector, matrix and quaternion types

### ISSUE THREAD

**Issue by acaudwell** [g-truc/glm#735]
I had a look into fixing the builds of a couple of programs that use GLM due to the new requirement to define GLM_ENABLE_EXPERIMENTAL to use GTX includes and discovered this change 4cf8a10af2bba678c2ad136006e6ec41118b6746. A lot of my code assumes vector components are initialized to 0.

IMO the way this used to work is preferable as it didn't break backwards compatibility. GLM is published as a dev library in various distros so software that doesn't bake a specific GLM version into it will likely have subtle or not so subtle uninitialized value bugs introduced by this change when this new version is packaged.

If you're dead set on removing default initialization, could it possibly just be changed to opt in initialization (e.g. GLM_DEFAULT_CTOR_INIT) and make it really prominent in the release notes?

**Comment by Groovounet** [comment]
This issue is resolved with the introduction of GLM_FORCE_CTOR_INIT define.

Thanks,
Christophe
