### ISSUE TITLE
Quaternion from/to euler 

### ISSUE THREAD

**Issue by JekaS178RUS** [g-truc/glm#737]
Hello!

When I create quaternion from Euler angles I found an issue: if yaw angle not in range [-90..90] degrees quaternion is incorrect.

In this code expected output is "0 100 0", but actual output is "180 80 180".
```
#include <iostream>
#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>

int main()
{
	float pitch = 0.f;
	float yaw = glm::radians(100.f);
	float roll = 0.f;
	glm::quat q = glm::quat( glm::vec3( pitch, yaw, roll ) );
	pitch = glm::pitch( q );
	yaw = glm::yaw( q );
	roll = glm::roll( q );
	std::cout <<
		glm::degrees( pitch ) << " " <<
		glm::degrees( yaw ) << " " <<
		glm::degrees( roll ) << std::endl;

	return 0;
}
```

I am using glm 0.9.8.3-1 from mingw64.

Best regards, Evgeniy.

**Comment by Zuzu-Typ** [comment]
Hello Evgeniy,

it appears that the output values are correct, under the assumption that you apply _roll_ first, _yaw_ second and _pitch_ last.
So it doesn't matter wether you say "0 100 0" or "180 80 180", because the rotation you end up with is the same.

**Comment by JekaS178RUS** [comment]
Hello, I can agree that these rotations are the same, but such behaviour is quite unexpected (for human at least). Especialy when one can assume that roll is always zero (as it was in my case) when only pitch and yaw can be changed, which is quite common situation.

Also I test [QQuaternion](http://doc.qt.io/qt-5/qquaternion.html) class from Qt library and it is worked as I expect.
