### ISSUE TITLE
infinite loop in ballRand and diskRand

### ISSUE THREAD

**Issue by Zuzu-Typ** [g-truc/glm#739]
(in glm/gtc/random.inl)
The functions 
`vec<3, T, defaultp> glm::ballRand(T Radius)` and `vec<2, T, defaultp> glm::diskRand(T Radius)` can result in an infinite loop if called with a negative value for **Radius**.
The reason for this is that they compare the length of a computed vector (which is _always_ positive or zero) to **Radius**.

One solution would be to throw an exception if a negative value is given (which shouldn't normally occur), or you could `fabs()` it.

**Comment by yuri-kilochek** [comment]
Why is it computing length (via expensive sqrt) in the first place instead of squared length (and comparing it without squared radius)?

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.1 release.

Now the functions checks that the parameters are positive values using an assert.

Thanks for reporting,
Christophe
