### ISSUE TITLE
Consider readding initialization

### ISSUE THREAD

**Issue by Zuzu-Typ** [g-truc/glm#740]
I think you should consider reverting https://github.com/g-truc/glm/commit/4cf8a10af2bba678c2ad136006e6ec41118b6746, not only because it's inconvenient, but also because it will result in lots of incompatibilities with existing GLM tutorials.
Also I don't see any benefit of doing so -- yes, in GLSL a matrix would not be initialized either, but does that really matter so much?

I would like to know what other people think about this.
To give you some context, in the latest (development) version of GLM, the following code would be broken:
`glm::mat4 model = glm::translate(glm::mat4(), glm::vec3(7.0f, 8.0f, 9.0f))`.
This code would have created a translated identity matrix in prior versions; now it creates an empty matrix.
```
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]
```
The reason is the removal of the initialization function.
To make the code work you would now have to do this:
`glm::mat4 model = glm::translate(glm::mat4(1.0f), glm::vec3(7.0f, 8.0f, 9.0f))`.
It outputs the following matrix:
```
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[7, 8, 9, 1]
```

**Comment by acaudwell** [comment]
I created a related issue #735, but this is another great example of it causing problems. I think it should just be an opt-in feature for performance as it was previously.

**Comment by b1uewizard** [comment]
I agree--what is the reason for removing initialization?

**Comment by acaudwell** [comment]
Debian (and now indirectly Ubuntu 14.08) has packed 0.9.9 a2. I've tried to point out the problem with this but they aren't being very receptive: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892861

**Comment by Groovounet** [comment]
This issue is resolved with the introduction of GLM_FORCE_CTOR_INIT define.

Thanks,
Christophe
