### ISSUE TITLE
How to check the version of GLM I am using?

### ISSUE THREAD

**Issue by zhou-heng** [g-truc/glm#742]
Since new version of GLM differs from old versions in initialization of matrix (zero vs identity), is there any mechanics, for example pre-processing directives, that I can use to tell the version of GLM I am using? Thank you.

**Comment by acaudwell** [comment]
I'm currently using:

`#if defined(GLM_VERSION) && GLM_VERSION >= 990`

**Comment by zhou-heng** [comment]
Thank you!
