### ISSUE TITLE
Missing glm/gtc/user_defined_type.hpp

### ISSUE THREAD

**Issue by dillonKneeland** [g-truc/glm#743]
I tried to compile my program and got this error:
```
fatal error: glm/gtc/user_defined_type.hpp: No such file or directory
 #include <glm/gtc/user_defined_type.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~``
```
I checked and I actually don't have that file even though my glm is copied directly from github.

**Comment by shamdooniz** [comment]
Did you manage to find a fix for this error? I'm having the same issue.
