### ISSUE TITLE
Tuple constructors?

### ISSUE THREAD

**Issue by p-groarke** [g-truc/glm#745]
Have you ever considered construction from tuples? It would add a dependency to the stl, which I do not know your stance on. I'd be happy to help out with a PR after some guidance.

edit: Or simply assignment.

**Comment by Groovounet** [comment]
I have no issue adding STL dependences but I am more concerned with compiler compatibility. GLM should still be able to run on a C++98 compiler so typically there are fallbacks to disable C++ 11 features in GLM implementation.

Additionally, tuple seems to be quite an overkill for GLM. You can already use initializer list with GLM types, isn't it enough?

I am quite tempted to not implement this to avoid complexing even more GLM but if you have a good use case, I am very happy to reconsider.

Thanks,
Christophe
