### ISSUE TITLE
glm::precision has not been declared

### ISSUE THREAD

**Issue by KofToZ** [g-truc/glm#747]
Hello,

I have this piece of code in a program we have, which used to work. 

template <typename T, glm::precision P = glm::defaultp>

Now we've upgraded to the newest glm version (0.9.9~a2-1) and it produces the following error

error: ‘glm::precision’ has not been declared
     template <typename T, glm::precision P = glm::defaultp>
                                ^~~~~~~~~

Do I need to include a new header or has the name simply changed or is the problem something else entirely? 

Best regards,
Ivan

**Comment by jmatzen** [comment]
The name of that type has changed.  Just look in the code.

**Comment by Groovounet** [comment]
This issue is fixed in master branch thanks to an alias between "precision" and "qualifier".

Thanks,
Christophe
