### ISSUE TITLE
Syntax error when compiling with GLM_FORCE_CTOR_INIT and GLM_ENABLE_EXPERIMENTAL

### ISSUE THREAD

**Issue by robertoraggi** [g-truc/glm#753]
Hi,

there's a typo in dual_quaternion.inl (in master) that prevents code to compile when GLM_FORCE_CTOR_INIT is defined.

$ g++ -xc++ -DGLM_FORCE_CTOR_INIT -DGLM_ENABLE_EXPERIMENTAL glm/gtx/string_cast.hpp 

In file included from glm/gtx/string_cast.hpp:23:
In file included from glm/gtx/../gtx/dual_quaternion.hpp:274:
glm/gtx/dual_quaternion.inl:31:20: error: use of undeclared identifier 'P'
                        : real(tquat<T, P>())

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9 release
