### ISSUE TITLE
[Suggestion] Easing GTX

### ISSUE THREAD

**Issue by Robadob** [g-truc/glm#761]
Easing functions are useful in animation and similar, currently as far I can tell, glm only has linear interpolation (`mix`, `lerp`) and spherical interpolation (`slerp` for quaternions).

Examples of the kind of things I'm talking about [here](https://easings.net/).

An easy strategy would be to convert [this](https://github.com/warrenm/AHEasing/blob/master/AHEasing/easing.c) file (it has one of the ultra liberal licenses), so that each contained function is templated and returns the result of forwarding the original return value to the corresponding linear interpolation function.

I'm happy to produce the above if you agree that it would be a useful addition.

**Comment by Robadob** [comment]
Slow evening, so I made a version that builds for `vec`, `dvec` and `quat` types [here](https://gist.github.com/Robadob/4cfb10a51e6712c4e01b0d5ea4d664a2).

If you want any refinements made, or it's worth submitting a pull request, let me know.

Thanks

**Comment by Groovounet** [comment]
Hi,
I added you proposed implementation with some edits to the master repository.
I can picture that additional work is needed but PRs are welcome.

Thanks for contributing,
Christophe
