### ISSUE TITLE
gtx::quaternion::intermediate function error

### ISSUE THREAD

**Issue by thechosenone124** [g-truc/glm#774]
The current intermediate function has some math errors

```
tquat<T, Q> invQuat = inverse(curr);
return exp((log(next + invQuat) + log(prev + invQuat)) / static_cast<T>(-4)) * curr;
```

You shouldn't be adding the next and prev to the invQuat, that should be a multiplication (based on http://web.mit.edu/2.998/www/QuaternionReport1.pdf)

I resolved it in https://github.com/g-truc/glm/pull/772

**Comment by Groovounet** [comment]
The PR is merged in master branch.
Thanks for contributing,
Christophe
