### ISSUE TITLE
Choose SIMD instruction set in runtime

### ISSUE THREAD

**Issue by Xottab-DUTY** [g-truc/glm#776]
It will be great if glm will automatically choose the best available instruction set right in runtime and will use it.

Is this feature possible or it will be hard to implement it?

**Comment by Groovounet** [comment]
Hi,
This would be extremely difficult to do with slowing down the code significantly at runtime.
My guess is that if this is something useful for you, it should be resolved on the application side.

Thanks,
Christophe
