### ISSUE TITLE
glm::translate doesn't accept single vec3 as argument

### ISSUE THREAD

**Issue by theo-walton** [g-truc/glm#780]
just upgraded glm from 0.9.8.5 to 0.9.9.0 and glm::translate doesn't compile with a single argument anymore, but I cant see it on the deprecated list. Whats going on?

**Comment by Groovounet** [comment]
Hi,
We need the following to use the single argument overload: 
#define GLM_ENABLE_EXPERIMENTAL
#include <glm/gtx/transform.hpp>
