### ISSUE TITLE
Can not get the latest version on cocoapods

### ISSUE THREAD

**Issue by DikeyKing** [g-truc/glm#781]
-> glm (0.9.4.6)
   OpenGL Mathematics (GLM).
   pod 'glm', '~> 0.9.4.6'
   - Homepage: http://glm.g-truc.net
   - Source:   https://github.com/g-truc/glm.git
   - Versions: 0.9.4.6, 0.9.4.3 [master repo]

The latest listed on pod is Versions: 0.9.4.6

**Comment by Groovounet** [comment]
Hi,
This is not a GLM issue, I guess this is something to see directly with cocoapods.
Thanks,
Christophe
