### ISSUE TITLE
Warning C4701: potentially uninitialized local variable 'Result' used

### ISSUE THREAD

**Issue by Tw1ddle** [g-truc/glm#782]
The following code: https://github.com/g-truc/glm/blob/0d973b40a49e550b1ea7df22a8573bc5fff84f24/glm/detail/func_vector_relational.inl#L8-L18

Produces this warning with MSVC 2013 update 5:

> include\glm\detail\func_vector_relational.inl(17): warning C4701: potentially uninitialized local variable 'Result' used

This isn't a bug because the `Result` vector is always populated in the loop, and there is already an assertion to check the lengths are equal to be sure. I guess it'd be wasteful to initialize the result vector at the beginning, but it would be nice to silence such warnings within glm.

**Comment by Groovounet** [comment]
Hi,
This issue should be fixed in master branch for GLM 0.9.9.1 release.
Thanks for reporting,
Christophe
