### ISSUE TITLE
Incorrect LxNorm calculation.

### ISSUE THREAD

**Issue by l90lpa** [g-truc/glm#784]
I am unfamiliar with the term lx-norm but I am assuming that it is meant to be the same as the p-norm that defines Lp-space? See https://en.wikipedia.org/wiki/Norm_(mathematics)#p-norm for a description. In this norm the magnitude of the components is taken for the calculation, but in the implementation of the `glm::lxNorm` in "glm/gtx/norm.inl" the magnitude (absolute value) of the components is not taken. 

When `glm::lxNorm` is used to computed the norm of a vector with some combination of negative components, and the "depth" (exponent) is odd, then this causes the norm to be different compared to a norm that takes the magnitude of each component i.e 
`pow(pow(abs(v.x), T(Depth)) + pow(abs(v.y), T(Depth)) + pow(abs(v.z), T(Depth)), T(1) / T(Depth));`. 

Is this meant to be the desired functionality? I notice in `glm::l1Norm` that the absolute value is taken.

**Comment by Groovounet** [comment]
No updated on this issue in 6 months so closing.

Thanks!
