### ISSUE TITLE
I havea error in the file type_half.inl

### ISSUE THREAD

**Issue by rubenesda** [g-truc/glm#787]
Dear
I have a error in the visual studio 2017 when build a script with libraries GLM, I followed the tutorial of the next link https://www.youtube.com/watch?v=aJRrgka4dpU&list=PLRtjMdoYXLf6zUMDJVRZYV-6g6n62vet8&index=16. But when I run this script. I get this error and the script doesn't work

This kind of function may not throw. Declare it 'noexcept' (f.6).
c:\opengl stuff\headers\glm\detail\type_half.inl	

Are there solution about this?
Thanks
Ruben

**Comment by Groovounet** [comment]
Hi,
Could you define #define GLM_FORCE_MESSAGES before including<glm/glm.hpp> then build and report the GLM messages in the build log?

Thanks,
Christophe
