### ISSUE TITLE
syntax error in intersect.inl

### ISSUE THREAD

**Issue by eindacor** [g-truc/glm#793]
I'm getting two syntax errors when trying to rebuild an old project on a new machine. I'm using Windows 10 SDK in Visual Studio 2017. Let me know if you need any more info about my environment. 

```
Error	C2760	syntax error: unexpected token 'identifier', expected ')'	   intersect.inl:53	
Error	C2760	syntax error: unexpected token 'typename', expected ')'	   intersect.inl:145	
```

**Comment by Groovounet** [comment]
I can't reproduce this issue on master branch...

Could you define GLM_FORCE_MESSAGES before including <glm/glm.hpp>, build and report the messages reported by GLM?

Thanks,
Christophe

**Comment by eindacor** [comment]
Update: the error seems to go away when the conditions on either side of the `||` operater are wrapped with parentheses, like so:

```
if ((position.y < typename genType::value_type(0)) || (position.y > typename genType::value_type(1)))
    return false;
```
instead of 
```
if (position.y < typename genType::value_type(0) || position.y > typename genType::value_type(1))
    return false;
```

**Comment by Groovounet** [comment]
Is this still happening for you on master branch?

**Comment by eindacor** [comment]
Yes, the same issue occurs at lines 53, 118, and 124.

**Comment by Groovounet** [comment]
I still can't manage to reproduce this issue. I tried another tentative fix in master branch.

The code at line 53, 118, and 124 looks perfectly valid and I am wondering whether this issue is caused by macros in the client project.

Thanks,
Christophe
