### ISSUE TITLE
Passing in values in glm::vec3 crashes Visual Studio 2017

### ISSUE THREAD

**Issue by limepixl** [g-truc/glm#796]
I have an example of this happening. 
![image](https://user-images.githubusercontent.com/24658281/43476414-d67868b2-94f8-11e8-898e-fffa9d698afe.png)
I can't type the last value for the vec3. If I try, after adding in the comma, in this case after the 0, Visual Studio crashes. I have to copy and paste the vector values in order to finish passing in the values.

Edit: This isn't dependent on glm::rotate at all. Happens in other circumstances.

**Comment by Groovounet** [comment]
My understanding is that this is not a GLM issue but a Visual Studio issue.

Thanks,
Christophe

**Comment by limepixl** [comment]
It happens exclusively with glm so I posted just in case. 

Although it does look to be mostly an intellisense issue.
