### ISSUE TITLE
Creating Identity matrix - different result between versions 9.9.0 and 9.5.0

### ISSUE THREAD

**Issue by demensdeum** [g-truc/glm#797]
After updating to new Ubuntu 18.04, I couldn't see anything in my game. I found reason in GLM.
Trying to create identity matrix:

`auto matrix = glm::mat4();`

Gives different result on 9.9.0 and 9.5.0, which leads to incorrect matrix in my game.
Here is diff between 9.5.0 and 9.9.0 in apitrace calls:
![apicalls](https://user-images.githubusercontent.com/19148646/43682157-fb3e9064-987b-11e8-9a3a-0ea609687469.png)

And if I create identity matrix that way:
`auto matrix = glm::mat4(1.0);`

Then everything good in both versions.

Related source code:
https://gitlab.com/demensdeum/FSGL/blob/master/Data/Object/FSGLObject.cpp#L45
Line 45 (glm::mat4 FSGLObject::matrix())

**Comment by Groovounet** [comment]
Hi,

GLM types are not initialized by default. If you want types to be initialized you can define GLM_FORCE_CTOR_INIT before including GLM headers.

Thanks,
Christophe
