### ISSUE TITLE
Documentation request: A guide for contributing to glm

### ISSUE THREAD

**Issue by neverhood311** [g-truc/glm#798]
I'm a bit of a C++ noob when it comes to large open source projects. Also a CMake noob. It would be helpful if there were a guide for getting set up to contribute to the glm project. Things I'm having trouble with include:

- using CMake GUI to generate Visual Studio project files
- running unit tests locally
- adding new unit tests

Is there documentation of this already and I just can't find it? This would be super helpful.

**Comment by Groovounet** [comment]
Hi,
Do you have a reference that you think would be a good base to write this documentation?

**Comment by neverhood311** [comment]
The Processing project has a good article in their wiki on how to build the project. Their level of detail is probably overkill for seasoned Java developers, but would be extremely helpful for a less experienced person. [https://github.com/processing/processing/wiki/Build-Instructions](https://github.com/processing/processing/wiki/Build-Instructions). They also have a helpful page on how to contribute, good for Git newbies, but not needed for Git experts [https://github.com/processing/processing/wiki/Contributing-to-Processing-with-Pull-Requests](https://github.com/processing/processing/wiki/Contributing-to-Processing-with-Pull-Requests).

A link to a good, basic CMake tutorial would be helpful as long as some of the GLM-related quirks were mentioned. And maybe a screenshot of Visual Studio showing the solution and projects once CMake has successfully run.

The dbachecks project has a good article on how to run their unit tests [https://github.com/sqlcollaborative/dbachecks/wiki/Running-Unit-Tests](https://github.com/sqlcollaborative/dbachecks/wiki/Running-Unit-Tests). I find screenshots of command line windows very helpful because I can see the exact commands they typed, see from what folder the command was run, what the output should look like, etc.

Then maybe a tutorial on how to write and run a new unit test for GLM. Does the test happen locally? In the cloud? Started from within Visual Studio? Started from the command line?

I realize this is a substantial request, and that some of it is not specific to GLM, but any of these would be an extremely helpful addition to the project.

**Comment by Groovounet** [comment]
The guide is added in master branch manual for GLM 0.9.9.1 release.

Thanks for contributing!
