### ISSUE TITLE
Build issue - multiple declarations and includes of the same inl file

### ISSUE THREAD

**Issue by sagaceilo** [g-truc/glm#799]
Hey !

I've just integrated newest glm (beside that default typedefs like i16vecX are no longer visible by default - You need to include glm/gtc/type_precision.hpp manualy) and the glm throws with multiple declaration of classes. Seems like .inl files are included from multiple places. So far found that [#pragma once](url) in those files ...
**quaternion_simd.inl** (included by type_quat.inl and quaternion.inl)
**matrix_transform.inl** (probably related to quaternions, sice they use this include also)
Stops the errors to show up. 

The only file Iinclude that I use is the <glm/gtc/type_precision.hpp> that is used in build.h (the PCH header).

**Comment by Groovounet** [comment]
Hi,
Which version of GLM are you using? A release and a branch?

**Comment by sagaceilo** [comment]
The very latest from master branch (cca8569a4147cf1f8acd3ce7b650804d790e86fa).

**Comment by sagaceilo** [comment]
Perfect ! Thank you :)
