### ISSUE TITLE
GLM_HAS_CXX11_STL is not defined for gcc under ubuntu

### ISSUE THREAD

**Issue by feng-lab** [g-truc/glm#802]
Seems like there is no way to define GLM_HAS_CXX11_STL for GCC as "((GLM_COMPILER & GLM_COMPILER_GCC) && (GLM_COMPILER >= GLM_COMPILER_GCC48))" was removed for some reason.

I got errors like "# error "GLM_GTX_hash requires C++11 standard library support"".

Thanks!

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.1 release

Thanks for reporting,
Christophe
