### ISSUE TITLE
Typo in SIMD platform detection code.

### ISSUE THREAD

**Issue by itsuhane** [g-truc/glm#805]
I was trying to compile glm in emscripten. Compiler complained about missing `GLM_ARCH_UNKNOWN`.

As can see in the code, `GLM_ARCH_UNKNOWED` is defined.
After changing it to `GL_ARCH_UNKNOWN`, compile will pass.
https://github.com/g-truc/glm/blob/02c4d8b15ecc40b8725403993dcbdbe39a0ddaac/glm/simd/platform.h#L242

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.1 release

Thanks for reporting,
Christophe
