### ISSUE TITLE
Why was glm::mat4() initialization deprecated?

### ISSUE THREAD

**Issue by jpaoneMines** [g-truc/glm#809]
Just downloaded the latest stable branch snapshot of v0.9.9.0.

A call to glm::translate() generates the wrong transformation matrix.  For instance

`glm::mat4 transMtx1 = glm::translate( glm::mat4(), glm::vec3(-50.0f, -50.0f, 0.0f) );`

Creates the following contents into transMtx1:
```
0.0    0.0 0.0    4.5
0.0    4.5 0.0    0.0
0.0    0.0 0.0    4.0
0.0 -225.0 0.0 -225.0
```

instead of the expected
```
  1.0   0.0 0.0 0.0
  0.0   1.0 0.0 0.0
  0.0   0.0 1.0 0.0
-50.0 -50.0 0.0 1.0
```

**Comment by jpaoneMines** [comment]
It actually appears that the root error lies with making a new matrix.  The following snippet
```
	glm::mat4 m = glm::mat4();
	printf("new matrix:\n");
	for(int i = 0; i < 4; i++ ) {
		for(int j = 0; j < 4; j++ ) {
			printf("%f ", m[i][j]);
		}
		printf("\n");
	}
	printf("\n");
	fflush(stdout);
```
produces the following output
```
0.000000 0.000000 0.000000 0.000000 
-454343011387561076949254144.000000 0.000000 1948.267212 0.000000 
-454343011387561076949254144.000000 0.000000 1950.739380 0.000000 
0.000000 0.000000 0.000000 0.000000 
```

A prior version  of glm that I had previously been using correctly generated the identity matrix
```
1.000000 0.000000 0.000000 0.000000 
0.000000 1.000000 0.000000 0.000000 
0.000000 0.000000 1.000000 0.000000 
0.000000 0.000000 0.000000 1.000000 
```

Has the usage changed with the newer version?  And how can I check what version my prior version is?  The files have timestamps from Feb. 2015.

**Comment by jpaoneMines** [comment]
A work around for the time being is to use the overloaded constructor
```
glm::mat4 identity = glm::mat4(1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1);
glm::mat4 transMtx1 = glm::translate( identity, glm::vec3( -50.0f, -50.0f, 0.0f );
```

**Comment by jpaoneMines** [comment]
Alternatively, defining GLM_FORCE_CTOR_INIT has the default constructor create an identity matrix.  Why is this definition needed in the latest version?

Also works as expected
```
#define GLM_FORCE_CTOR_INIT
#include <glm/glm.hpp>
```

**Comment by jpaoneMines** [comment]
Any insights why the deprecation was introduce in v0.9.9.0?

Improvements:
No more default initialization of vector, matrix and quaternion types
Deprecation:
Removed default initialization, use GLM_FORCE_CTOR_INIT to restore the old behavior

**Comment by Groovounet** [comment]
Hi,
GLM tries to follow closely the GLSL specification to provide a C++ implementation. GLSL doesn't default initialize as a result GLM 0.9.9 catch up with that behavior. GLM_FORCE_CTOR_INIT is provided for backward compatibility.

Furthermore, it allows using C++11 default contructors which, for example, make memcpy available for GLM types.
Thanks,
Christophe

**Comment by jpaoneMines** [comment]
Understood, that makes sense.  Thanks for providing the clarification.  I'll be sure to update my usages and not rely on the backwards fix.

**Comment by mosra** [comment]
> Furthermore, it allows using C++11 default contructors which, for example, make memcpy available for GLM types.

I don't want to be the nitpicky guy here, but this is not true -- memcpy() can be used on any type that [is_trivially_copyable](https://en.cppreference.com/w/cpp/types/is_trivially_copyable) and as far as I'm aware, GLM can work with that as long as the *copy* constructors are either `default`ed or not specified at all. Doesn't have anything to do with implicit constructors. 

In particular, in the [Magnum::Math](http://doc.magnum.graphics/magnum/namespaceMagnum_1_1Math.html) library I'm having default constructors that zero-initialize everything (or set matrices to identities etc.) and memcpy() has never been a problem.

**Comment by richardeakin** [comment]
I think it's also worth pointing out that even though the GLSL spec doesn't mandate it, the drivers / vendor specific GLSL compilers seem to default init to zero anyways. This has been my experience in practice,
