### ISSUE TITLE
cmake script does not always work

### ISSUE THREAD

**Issue by sancelot** [g-truc/glm#810]
cmake 3.10

I have got a project that use glm math api with cmake, it runs fine from my system.

But when the project is compiled by jenkins continuous integration pipeline , I have the next message coming from find_package(glm):

```
-- GLM is a header only library, no need to build it. Set the option GLM_TEST_ENABLE with ON to build and run the test bench
GLM: GCC - GNU compiler
-- Found OpenGL: /usr/lib32/libGL.so   
CMake Error at Release/glm-0.9.9.0/glmConfig.cmake:5 (include):
  include could not find load file:

    /nfs/solaris/JENKINS_BUILDS/R21_developpement-VF2RO6QEGJNOO575NWKS4N3DEEDKNDILXY7XZHTZLURHWSU2ZOZA/workspace/Release/glm-0.9.9.0/glmTargets.cmake
Call Stack (most recent call first):
  API_SIMULATION/CMakeLists.txt:5 (find_package)


-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Failed
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
```

the glmTargets.cmake in this case is not present 

I checked too from the cmdline in the same directory and it has not worked too.

I may have missed something ?

In my main CMake file I added 
add_subdirectory(glm-0.9.9.0) 

and then used find_package(glm) when needed

**Comment by Groovounet** [comment]
I would suggest to submit a PR if you want improvements for CMake support of install and uninstall.

Thanks!

**Comment by jbsolomon** [comment]
@Groovounet -- I have the same problem during local development, which prevents me from using the library at all.  I wasn't able to resolve it by checking out old versions, since my usage is via `add_subdirectory(dep/glm)`.
