### ISSUE TITLE
Missing code?

### ISSUE THREAD

**Issue by manstie** [g-truc/glm#815]
matrix_transform.inl file is practically empty?

Downloaded the zip from https://github.com/g-truc/glm/releases/tag/0.9.9.2

Was trying to use translate/rotate, nothing renders. Switched to an older version provided to us, works perfectly, that version has code in the matrix_transform.inl file.

**Comment by Groovounet** [comment]
Hi,
The code has moved to ../ext/matrix_transform.inl but it's including in ../gtc/matrix_transform.hpp with ../ext/matrix_transform.hpp
Thanks,
Christophe

**Comment by manstie** [comment]
Well whatever you have changed, it no longer allows the transformations tutorial ( https://learnopengl.com/Getting-started/Transformations ) to display anything compared to the previous version I just downloaded 0.9.8.5
