### ISSUE TITLE
Regression: no constexpr on gcc

### ISSUE THREAD

**Issue by kiwixz** [g-truc/glm#816]
[Godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5NwDMeFsgYisAag6yAwsAYBbAPQ7dAOgQAHMxuwcADAEFbdtC0EFMADzPFV6UQCMGTB91WQARVSMQEGImfFZBCABOG2MbAEoNPntHBQJVXSYFCAyAdiy7VUqqyuJMAjEWH0zHDhLQxyk0xmkAVilSFmkbftRpTX5%2BVWExCXUuWVp%2BgiHOroBrEFlZYy3dvf2ANm6pABZ%2Bwalh0lGpfsEQG1Jly87SOFgYRBRUXTM8QLIFAgaF%2B/0wxBAwEELCYZkECFQBFIADN/m5iPcIH4VqQ/AomMQAJ7SRakEG6TAsAgAeRYDGJL1IWAKbECOPwtWQBDwADdMPdGR5MMgRG4Sf1cpgGDiCMQ8LpxV1mGwUBNeIw8H57rAYRTIXpSHyIbKRCw1mkuqgzNzUC5pHdROJJLQlb1zjibu4ABwHAC0BxOEWQyFUEBNZrSodwhBIcwWpFUmh%2BfwBcZdibVPCWKwtpAQmFi4Mo6xAPUe0tO/QVZYGHvtQgeTxzb0%2BECQogIZlF5EoIJTRfomHwRAh9AA7jEzIrjn1a4ybnJaKox4QEKpvX6A0GQ2HiKbzdmXrn84WIcVjmdSNXHhcrjc7o3nsNcxstjt9h%2BtkcK7J3fP60%2BrzvFArZIH2YKAr2yYQZC0KwvCiIomi4KYtijJ4jCRLimSPwUlStL0uymAsjokiMhywrcnyApXEKIpilIpKShWVyyvK07KuwmYalq8AQLqkhGIaRaXIkySrNc1p4LaAoOjMzqulIs63iM0gbv6gbAMGobhuaUbDrGi4JkmoKpnIXCRuMvD8Iez4lm%2Bn6fheValjeda3A2jyAV0wFtiAHZdkiQLgQCIBcKQQ4xqOpATrCHFunOd7SOZy6ruuPoaduOl7hGtkSSeWBnopl7XolqkefcXk5vZ2yOR%2Bxy/mV1wAdVxxcH%2BSUed5XRGoI0mDCcQA%3D%3D)

0.9.9.0 is working as expected, but 0.9.9.2 is not.

**Comment by Groovounet** [comment]
Hi,
To use constexpr you need to define GLM_FORCE_PURE before including GLM. This is not ideal and a better solution would be great but that all we have at this point.

This is to deal with the issue that compilers SIMD intrinsics are not constexpr...
