### ISSUE TITLE
[question] Migration from GLM 0.9.8.5 to GLM 0.9.9.2 issues 

### ISSUE THREAD

**Issue by Shot511** [g-truc/glm#817]
Hey,

Yesterday I migrated from `glm 0.9.8.5` to `glm 0.9.9.2`. The project [(VertexEngine)](https://github.com/Shot511/VertexEngine/) builds fine, but my sample game's scene vanished. When I moved back to `glm 0.9.8.5` everything works fine.

What else has changed between these versions (apart from removing default constructors which, I think, I'm not using) that could destroy my transformations? Is there any define that will tell me if I abuse the use of glm?

**Comment by Groovounet** [comment]
Hi,

Did you try to define GLM_FORCE_CTOR_INIT to double check?

**Comment by Shot511** [comment]
Yup, it solved the problem. I just had to add it in every file that included glm files.
