### ISSUE TITLE
attributes are not allowed here

### ISSUE THREAD

**Issue by zhiansht** [g-truc/glm#819]
complied CUDA .cu  file with glm in vs 2015.
used CUDA version: 9.0.
got error  in  qualifier.hpp  in 	96	and  104：

92 #	if GLM_HAS_ALIGNOF
93 		template<length_t L, typename T>
94 		struct storage<L, T, true>
95		{
96			typedef struct alignas(L * sizeof(T)) type {
97				T data[L];
98			} type;
99		};
100
101		template<typename T>
102		struct storage<3, T, true>
103		{
104			typedef struct alignas(4 * sizeof(T)) type {
105				T data[4];
106			} type;
107		};
108    #	endif

Did anyone knowed why did l get this error?

**Comment by aole** [comment]
I am having the same issue. I had to comment out the section to compile again.

**Comment by zhiansht** [comment]
#define GLM_FORCE_PURE 
it work for me

**Comment by jclay** [comment]
I encountered this as well and `#define GLM_FORCE_PURE` didn't work for me. I'm using CUDA 10 and MSVC 19.9.4.

The section of the code it is referencing compiles fine here https://godbolt.org/z/UYU7Sa.

I did some more digging and couldn't figure out what was causing it. I ended up moving the glm includes from the `.cu` file to the appropriate `.h`. It works fine now, not sure what causes this issue.
