### ISSUE TITLE
Error with Clang on Android,  implicit conversion increases floating-point precision

### ISSUE THREAD

**Issue by caseymcc** [g-truc/glm#824]
In the hunter CI upon updating to the latest 0.9.9.2 I ran into this error on Clang 6.0.2 (https://travis-ci.org/caseymcc/hunter/jobs/443382785)

 /home/travis/build/caseymcc/hunter/_testing/Hunter/_Base/3d67606/9040522/10fdb02/Build/glm/Source/glm/gtc/ulp.inl:212:34: error: implicit conversion increases floating-point precision: 'float' to 'double' [-Werror,-Wdouble-promotion]

I traced it to the following code, I am assuming that FLT_MAX should be DBL_MAX?

    template<>
    GLM_FUNC_QUALIFIER double next_float(double const& x)
    {
    #		if GLM_HAS_CXX11_STL
        return std::nextafter(x, std::numeric_limits<double>::max());
    #		elif((GLM_COMPILER & GLM_COMPILER_VC) || ((GLM_COMPILER & GLM_COMPILER_INTEL) && (GLM_PLATFORM & GLM_PLATFORM_WINDOWS)))
        return detail::nextafter(x, std::numeric_limits<double>::max());
    #		elif(GLM_PLATFORM & GLM_PLATFORM_ANDROID)
        return __builtin_nextafter(x, FLT_MAX);
    #		else
        return nextafter(x, DBL_MAX);
    #		endif
    }

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.3, thanks for reporting!
