### ISSUE TITLE
Problem with SWIZZLE

### ISSUE THREAD

**Issue by Mikez2015** [g-truc/glm#825]
#define GLM_SWIZZLE
now not working

glm::vec4 v;
String like this: 
v,xyz()
now generate error

**Comment by Groovounet** [comment]
This issue is fixed on master branch for GLM 0.9.9.3 release. 
This said, GLM_SWIZZLE is deprecated, replaced by GLM_FORCE_SWIZZLE.

Thanks for reporting,
Christophe
