### ISSUE TITLE
member variable of type "static constexpr glm::vec3" doesn't work anymore since 0.9.9.2

### ISSUE THREAD

**Issue by Mutantpenguin** [g-truc/glm#826]
It throws the following error:
**with clang 7.0.0**
```
/home/charon/Projekte/glmtest/glmtest/main.cpp:8:29: error: constexpr variable 'Z' must be initialized by a constant expression
        static constexpr glm::vec3 Z    { 0.0f, 0.0f, 1.0f };
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~
```
**with g++ 8.2.1**
```
/home/charon/Projekte/glmtest/glmtest/main.cpp:8:50: error: call to non-'constexpr' function 'glm::vec<3, T, Q>::vec(T, T, T) [with T = float; glm::qualifier Q = (glm::qualifier)0]'
  static constexpr glm::vec3 Z { 0.0f, 0.0f, 1.0f };
                                                  ^
```

With 0.9.9.0 everything works as expected.

See attachment for a small example.
[main.cpp.txt](https://github.com/g-truc/glm/files/2521724/main.cpp.txt)

**Comment by Groovounet** [comment]
Hi,
`constexpr` requires that SIMD instructions are not used because compiler instrinsics don't implement `constexpr`. An easy solution is to define `GLM_FORCE_PURE` before including GLM headers.

Thanks!
