### ISSUE TITLE
weird failures with partial GLM_SWIZZLE since 0.9.8

### ISSUE THREAD

**Issue by maddanio** [g-truc/glm#828]
Hello,

Thanks a lot for providing glm, great toolset. I just wanted to draw attention to very weird failures we encountered recently (0.9.8) when partially definining GLM_SWIZZLE, i.e. in a subset of the translation units. It leads to seemingly corrupted stacks. So far this has only happened when calling from objective-c++ code where GLM_SWIZZLE was defined, to pure c++ code which did not have it defined. This was not the case in 0.9.7. I could not complete fence this in yet. I did not find any layout differences yet. Still it happens quite consistently when having glm types in the call, and only with 0.9.8 (possible above) and the mixed GLM_SWIZZLE defines.

**Comment by christophe-lunarg** [comment]
Closing this issue only because it's very old and nobody else commented on this.

I hope this resolved itself !
