### ISSUE TITLE
Bug in Matrix conversion code in 0.9.9.3

### ISSUE THREAD

**Issue by eric1221bday** [g-truc/glm#829]
Hi

I've been using glm HEAD from homebrew and encountered a bug in one of the matrix conversion constructors due to the change to initializer lists starting from this version. Specifically, in commit dee806ea3f034afe803a1c00b8d027d542fe55a9, 
https://github.com/g-truc/glm/blob/dee806ea3f034afe803a1c00b8d027d542fe55a9/glm/detail/type_mat4x3.inl#L174-L186

The initializer list is incorrect and indeed is inconsistent with the old implementation.
```cpp
#		if GLM_HAS_INITIALIZER_LISTS
			: value{col_type(m[0]), col_type(m[1]), col_type(m[2]), col_type(0)}
#		endif
	{
#		if !GLM_HAS_INITIALIZER_LISTS
			this->value[0] = col_type(m[0]);
			this->value[1] = col_type(m[1]);
			this->value[2] = col_type(m[2]);
			this->value[3] = col_type(m[3]);
# endif
```

The new implementation would leave the last column as 0 whereas it should be filled with the corresponding column of the 4x4 matrix when converting to 4x3.

This results in a mat4x3 which would have the last row be empty no matter what the mat4 is.

**Comment by Groovounet** [comment]
This issue is in master branch for GLM 0.9.9.4 release.

Thanks for contributing!
