### ISSUE TITLE
vec2(2,2) * 4. doesn't compile

### ISSUE THREAD

**Issue by FabriceNeyret** [g-truc/glm#834]
vec2(2,2) * 4. doesn't compile while vec2(2,2) * 4.0f does.

**Comment by tigert1998** [comment]
Because `4.` is a double while `4.0f` is a float. Meanwhile, `vec2` is actually:
```cpp
typedef vec< 2, float, defaultp > vec2
```
Therefore, to some extent, I think compile error an appropriate way to alert you the type of a vector when you write the multiplier.

**Comment by FabriceNeyret** [comment]
I see. The problem is that 2 or 2. were accepted in the constructor (I know why, but it's misleading :-) ).
"compile error an appropriate way": uh, I got the usual dozens of unreadable error messages, not so easy to parse.

But would it be that difficult to have double accepted as well (and casted to float) ? 
The problem is that GLSL makes no difference between the 2 writting of constants, so that copy-pasting GLSL code to glm create an incompatibility. If glm could smooth it easily, it would be a cool thing.

**Comment by Groovounet** [comment]
There is already a feature request for this: https://github.com/g-truc/glm/issues/532

The implementation requires C++11 and a lot of work...
