### ISSUE TITLE
smoothstep(double, double, float) doesn't compile

### ISSUE THREAD

**Issue by FabriceNeyret** [g-truc/glm#835]
more generally, when there is a mix of float and doubles.
Shouldn't they be automatically converted ?

**Comment by Sarvadi** [comment]
This is correct. The templated type is ambiguous, so the compiler can't tell if you want `smoothstep<float>` or `smoothstep<double>`. You can fix this by explicitly specifying `smoothstep<double>`, or promoting the float yourself.

**Comment by Groovounet** [comment]
This is a duplicate of #532

Thanks for reporting,
Christophe
