### ISSUE TITLE
Doc: gtx_projection update comment on proj()

### ISSUE THREAD

**Issue by dtrebilco** [g-truc/glm#836]
I was wondering what the point of the gtx_projection extension was when I realized that it allows projecting one vector on another without needing the "Normal" vector to be of unit length. (and does not perform any expensive sqrt() operations)

I think the documentation on the method should be updated to indicate that the "Normal" parameter does not need to be of unit length.

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.4.

Thanks for contributing!
