### ISSUE TITLE
Constexpr disabled for non-SIMD functions via global architecture #ifdef

### ISSUE THREAD

**Issue by ghassanpl** [g-truc/glm#841]
In `setup.hpp` there's a line:

`#if (GLM_ARCH & GLM_ARCH_SIMD_BIT) // Compiler SIMD intrinsics don't support constexpr...`

and it's used to globally enable or disable constexpr, even for files like `type_vec2.hpp/inl` which don't use SIMD intrinsics.

I'm sure there's a reason for it, but is there anything preventing me from redefining `GLM_CONSTEXPR` as `constexpr` for the `vec2` files in my personal copy of glm?

**Comment by alexanderbock** [comment]
Same issue here, it automatically disables `constexpr` for all methods in the library

**Comment by Groovounet** [comment]
If you want to use constexpr, define `GLM_FORCE_PURE`.

Also it's not done yet *vec2 could use SIMD instructions for example for dvec2.

Thanks,
Christophe
