### ISSUE TITLE
Potential bug with `mix` in 0.9.9.3?

### ISSUE THREAD

**Issue by alexanderbock** [g-truc/glm#842]
Just updated our code base from 0.9.8.x to 0.9.9.3 and a previously working code no longer compiles:
```
glm::dmat4 start = ...;
glm::dmat4 end = ...;
float t = "...";
glm::dmat4 res = glm::mix(start, end, t);
```
Fails in the 
```
	template<typename T, typename U>
	struct compute_mix
	{
		GLM_FUNC_QUALIFIER static T call(T const& x, T const& y, U const& a)
		{
			GLM_STATIC_ASSERT(std::numeric_limits<U>::is_iec559 || GLM_CONFIG_UNRESTRICTED_GENTYPE, "'mix' only accept floating-point inputs for the interpolator a");

			return static_cast<T>(static_cast<U>(x) + a * static_cast<U>(y - x));
		}
	};

```
with the second `static_cast` from the left, where it tries to cast a `glm::dmat4` into a `float`

**Comment by nealmcb** [comment]
If previously-working code doesn't work with newer versions, is that a regression, rather than an enhancement request?

**Comment by Groovounet** [comment]
This issue is resolve in master branch for GLM 0.9.9.4 release.

Please include <glm/ext/matrix_common.hpp> to access this feature.

Thanks!
