### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by tilkinsc** [g-truc/glm#850]
I was using mingw and was in a windows shell with command `cmake -G "MinGW Makefiles"`. When I `make -j4`'d everything went okay, but when I installed, it tries to `make install` exclusively to program files (x86) without the PREFIX variable taking effect.

![image](https://user-images.githubusercontent.com/7494772/50386853-67b4d280-06bd-11e9-85b5-dbd5027a233f.png)

When I went into x86 and changed the permissions on my folders to user modifyable and relaunched the command, it worked.

**Comment by Groovounet** [comment]
CMake installer and uninstaller scripts are gone for now. Why not adding it back in the future if there is high demand but the PR will require manual change to add documentation about the how to use the installer scripts and their features.

Thanks,
Christophe
