### ISSUE TITLE
Error with GLM_HAS_CXX11_STL detection with Clang and VS Toolchain

### ISSUE THREAD

**Issue by maniatic0** [g-truc/glm#858]
Hello,

Thanks for this awesome library!

I found a small bug with the GLM_HAS_CXX11_STL detection using Clang and VS Toolchain on Windows due to the lack of libc++ on Windows.

On file _glm\detail\setup.hpp:146_ :
`#	if (defined(_LIBCPP_VERSION) && GLM_LANG & GLM_LANG_CXX11_FLAG) || defined(GLM_LANG_STL11_FORCED)`

I think the fix should be checking if **_MSC_VER** is defined like this:
```
#	if ((defined(_LIBCPP_VERSION) || defined(_MSC_VER)) && GLM_LANG & GLM_LANG_CXX11_FLAG) || \
		defined(GLM_LANG_STL11_FORCED)
```

This is my macros dump from Clang if it's needed [macros_clean.txt](https://github.com/g-truc/glm/files/2767112/macros_clean.txt).

Btw, on _glm\simd\platform.h:130_ Clang's detection could be affected by the VS detection if the order of the if's were to be inverted.

**Comment by muusbolla** [comment]
GLM_HAS_CXX11_STL does not work on Linux with clang.

_LIBCPP_VERSION is not defined by clang. It is only defined when including libc++ on certain platforms so it is not appropriate to use inside of the
`#elif GLM_COMPILER & GLM_COMPILER_CLANG`
block. I'm not sure how this block works exactly on Windows, but on Linux __cplusplus is properly defined, so just testing GLM_LANG & GLM_LANG_CXX11_FLAG is good enough. I ripped out the whole windows specific bit in my version 0.9.9.5-1 line 145 and just have the following:

```
#elif GLM_LANG & GLM_LANG_CXX11_FLAG || defined(GLM_LANG_STL11_FORCED)
#	define GLM_HAS_CXX11_STL 1
```
