### ISSUE TITLE
GLM_CONSTEXPR used on vec::length()

### ISSUE THREAD

**Issue by PazerOP** [g-truc/glm#860]
When using SIMD, GLM_CONSTEXPR is disabled (defined as nothing) due to incompatibilities. However, some functions (like vec::length()) also use GLM_CONSTEXPR and thus are not constexpr either. 

Since functions like vec::length simply return a constant, they are not affected in any way by the usage of SIMD instructions.

I believe there should be some other define used on these functions so constexpr versions of them are usable even when compiling with SIMD.

**Comment by Groovounet** [comment]
Also I agree it's possible for implementation simplicity GLM is implementing constexpr as a all or nothing feature.

Thanks!

**Comment by PazerOP** [comment]
So this is never going to be added "because it's too complicated", despite the work already being done?
