### ISSUE TITLE
Support for non EEE 754 floats.

### ISSUE THREAD

**Issue by nVxx** [g-truc/glm#861]
As of GLM v. 0.9.9.3 `float`s are required to comply to `IEEE 754` (`std::numeric_limits<float>::is_iec559` should be `true`).

But that's not the case for Greenhills (`GHS`) compiler for `ARM`.  It guarantees, that `float`s in-memory representation is `IEEE 754` conform, but the operations might yield less precise results, thus (`std::numeric_limits<float>::is_iec559` is `false`).

Is it possible to make more `GLM` configurable, so it supports non `IEEE 754` conform floats?

**Comment by Groovounet** [comment]
Hi!

How can we check the compiler use non EEE 754 floats?

**Comment by nVxx** [comment]
Hi!

Unfortunately the documentation is not available via public link.  The manuals are in toolchain package and supposedly one also can get the documentation [through subscribing](https://www.ghs.com/products/MULTI_IDE.html).

but here's the excerpt from Arm 64 build manual:

> Floating-Point Support—Floating-point values use IEEE-754 format (32- and 64-bit) and are in the same byte order as other values. Although the compiler uses the IEEE-754 floating-point format, floating-point operations may not generate the precise values required by the specification.

**Comment by Groovounet** [comment]
Is there a define I could check?

**Comment by nVxx** [comment]
> Is there a define I could check?

Not sure I understand, can you please elaborate?

The situation is, that when compiling with Greenhills compiler (version 2018.1) `std::numeric_limits<float>::is_iec559` assertions in GLM code fail, which is expected since the documentation also states so.
So my initial query was whether it is possible to make `IEEE 754` conformity optional.

Unfortunately there is no licence-free or trial version of the compiler that I know about.

**Comment by nVxx** [comment]
Found a link to documentation:
http://www.ece.ualberta.ca/~cmpe490/documents/ghs/build_arm.pdf

Page 102.
