### ISSUE TITLE
bitfieldRotateRight() & bitfieldRotateLeft() are backwards

### ISSUE THREAD

**Issue by TLHobbes** [g-truc/glm#862]
bitfieldRotateRight() is implemented as a LEFT rotate; and bitfieldRotateLeft() is implemented as a RIGHT rotate. Also test/gtc/gtc_bitfield.cpp currently does not have tests for those functions.

**Comment by Groovounet** [comment]
I just implemented a couple of tests to check this issue but the implementation is correct.

Thanks
