### ISSUE TITLE
glm::mix does not comply with GLSL specification

### ISSUE THREAD

**Issue by UniQP** [g-truc/glm#866]
The GLSL specification of `mix(x, y, a)` says
```
Returns the linear blend of x and y, i.e., x⋅(1−a) + y⋅a.
```

However, the current glm implementation uses
```
x + a⋅(y-x)
```
, which does not guarantee `mix(x, y, 1) == y`.

**Comment by Groovounet** [comment]
This issue should be fixed in master branch for GLM 0.9.9.4 release.
Thanks for reporting!
