### ISSUE TITLE
Build error c2440 at line 156 in type_vec.inl "'static_cast' cannot convert from 'U' to 'T'"

### ISSUE THREAD

**Issue by N00TN00T** [g-truc/glm#868]
I'm getting c2440 build error at line 156 in type_vec.inl with the message "'static_cast' cannot convert from 'U' to 'T'". This happened after I changed from using vec3 everywhere to using vec2. I have absolutely no clue what could cause this and don't know how to find the problem.

**Comment by satvik-tiwari** [comment]
i am getting the same error, how did u fix it?
