### ISSUE TITLE
"glm::decompose()" is using float-type instead of templated-type

### ISSUE THREAD

**Issue by cofenberg** [g-truc/glm#869]
"glm::decompose()" is using float-type instead of templated-type in line

- "float root, trace = Row[0].x + Row[1].y + Row[2].z;"

Resolved by changing to

- "T root, trace = Row[0].x + Row[1].y + Row[2].z;"

(line 156 of "glm\gtx\matrix_decompose.inl" in latest version, last changed 7 August 2018 - commit 8c9d16d868045ad9c59ff954eeceb1f61454289a)

Noticed this when adding 64 bit world space position support to my spare time renderer project.

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.9.4 release.

Thanks!
