### ISSUE TITLE
mingw64 gcc8.1 qt project compile error

### ISSUE THREAD

**Issue by ZYV037** [g-truc/glm#870]
error: 'constexpr const T& glm::vec<2, T, Q>::operator[](glm::vec<2, T, Q>::length_type) const' cannot be overloaded with 'constexpr T& glm::vec<2, T, Q>::operator[](glm::vec<2, T, Q>::length_type) const'
   GLM_FUNC_DECL GLM_CONSTEXPR T const& operator[](length_type i) const;
                                        ^~~~~~~~
eliminate this error by ban constexpr.

glm/detail/setup.hpp
#if GLM_HAS_CONSTEXPR
#	define GLM_CONSTEXPR /*constexpr*/
#else
#	define GLM_CONSTEXPR
#endif

env: msys2 mingw64, gcc8.1, c++11

**Comment by htmlboss** [comment]
set your compiler std version to c++14. I believe glm now requires c++14 as a minimum due to relaxed constexpr rules provided by it.

**Comment by ZYV037** [comment]
tested. it's ok now.
qt project .pro: CONFIG += c++14

**Comment by ZYV037** [comment]
qt project .pro: CONFIG += c++14 needed.
