### ISSUE TITLE
CMake Include Directory

### ISSUE THREAD

**Issue by moepmoep12** [g-truc/glm#873]
Hi, 

I'm using glm as a submodule in my project. The Include Directory for my specific project is `../thirdParty/glm`. But the headers for glm are defined within `../thirdParty/glm/glm`. This leads to unecessary folders being within the relative include search path such as` ../thirdParty/glm/cmake.` 

I'd like to propose to move the headers into` ../glm/include/glm` and change the include directory to `/glm/include` . Like many other libraries already do.

This way includes such as `#include "glm/glm.h` would be possible.

**Comment by Groovounet** [comment]
This changes would break too many project relying on GLM...

Thanks
