### ISSUE TITLE
Tons of errors.  I'm new to GLM please give me some guidance

### ISSUE THREAD

**Issue by hpiper3097** [g-truc/glm#875]
I'm on Debian and had made some headway into a rendering engine using Code::Blocks.  Recently I stopped using it, and I have been trying to compile and link my project manually.  The only errors I'm getting seem to be from GLM, but I have no idea why.  I'll leave  the output with GLM_FORCE_MESSAGES defined.  I'll also post my makefile in case I'm putting it together wrong. Thanks, and sorry for beginner problems!
[log.txt](https://github.com/g-truc/glm/files/2921307/log.txt)

GitHub doesn't support the raw makefile in the post, so I pasted the contents into a text file instead.

[make.txt](https://github.com/g-truc/glm/files/2921309/make.txt)

**Comment by BrianBeuken** [comment]
I have the same issues with the latest version of GLM, masses of errors, like this.
error : conflicting declaration of template `template<class T, glm::qualifier P> struct glm::tvec2'

**Comment by hpiper3097** [comment]
I was just a monkey and forgot some #pragma once 's throughout my code
If your error is like mine, then you have headers being included multiple times

**Comment by BrianBeuken** [comment]
yeah had 2 copies (old and new) and it the build was picking up both of
them..
the const expr issue has been fixed too so it can compile in C++11 again


Brian Beuken
Lecturer Game Programming
Breda University of Applied Sciences (formally NHTV Breda,  *email
addresses are in transition)
+3176 533 2472
University website www. <http://www.nhtv.nl>buas.nl


Personal website : www.scratchpadgames.net
Please note, I suffer from mild dyslexia, and spill chuckers don't always
catch my errors. ;) If my mail makes no sense, please just let me know,
I'll find another way to mess it up.
