### ISSUE TITLE
manual.md line 112

### ISSUE THREAD

**Issue by whitequill** [g-truc/glm#880]
There is a mistake in **manual.md** on line 112.
It currently looks like this:
`![](https://github.com/g-truc/glm/blob/manual/doc/manual/frontpage1.png)` but it shows as broken when reading it on a viewer like Typora.

To correct it all that needs to be done is it needs to be written as: `![](/doc/manual/frontpage1.png)` and the image loads fine.

**Comment by kennycastro007** [comment]
Is this issue still open? I'd like to fix it really quick

**Comment by Groovounet** [comment]
This issue has been fixed a white ago on master branch.

thanks for reporting,
Christophe
