### ISSUE TITLE
CMake: GLM_INSTALL_ENABLE removed

### ISSUE THREAD

**Issue by aliu** [g-truc/glm#894]
I noticed in a23dd2f800185a5e233534fed82fc5c2840fbe5c you removed the `GLM_INSTALL_ENABLE` option that was added in #585.

I feel like this is a useful option and it would be nice if this could be re-added.

**Comment by Groovounet** [comment]
The installer CMake installer and uninstaller scripts are gone for now. Why not adding it back in the future if there is high demand but the PR will require manual change to add documentation about the how to use the installer scripts and their features.

Thanks,
Christophe
