### ISSUE TITLE
error in compile

### ISSUE THREAD

**Issue by daisy20170101** [g-truc/glm#899]
Hi, 

Our software SeisSol uses glm and we found an error in the compilation:

in glm/detail/func_common.inl (631 and 665): 
  return ::isnan(x)
  return ::isinf(x)

we fix it by adding std:  **return std::isnan(x) and return std::isinf(x)**
Hope this should work for everyone.

Best,
Duo

**Comment by Groovounet** [comment]
This issue should be fixed in master branch for GLM 0.9.9.6 release.

Thanks for contributing !
Christophe
