### ISSUE TITLE
All types are incomplete in Visual Studio 2019

### ISSUE THREAD

**Issue by suleyth** [g-truc/glm#911]
In a fresh new project only copy pasting the `glm` folder inside of this repo in the same directory as the project, when using any of the glm types, example:
```cpp
#include "glm/glm.hpp"

int main() {
    glm::vec2 a = glm::vec2(0.5f, -0.5f);
}
```
An error appears: `type 'glm::vec<2, float, 0>' is incomplete` on the type declaration and any other part in the code you reference that variable. This happens with every glm type
The program builds and runs with no issues, however with this output:
```
message :  see reference to class template instantiation 'glm::vec<2,T,Q>' being compiled (compiling source file <the source>.cpp)
<path to glm>glm\detail\type_vec2.hpp(47,1): warning C4201:  nonstandard extension used: nameless struct/union (compiling source file <the source>.cpp)
<path to glm>glm\detail\type_vec2.hpp(48,1): warning C4201:  nonstandard extension used: nameless struct/union (compiling source file <the source>.cpp)
```
Defining `GLM_FORCE_CXX11`  or `GLM_FORCE_CXX14` doesn't seem to do anything
I'm using the latest version downloaded from the website, what could be happening? Thanks

**Comment by giordi91** [comment]
I am actually able to replicate on latest Visual Studio 2017. Code compiles just fine, Intellisense is just going mental. 

In my case I am generating the solution from my CMake but should not affect at all.

**Comment by giordi91** [comment]
By doing a simple bysecting for me the issue seems to start showing up since 0.9.9.0 version. 0.9.8.5 is fine.

**Comment by suleyth** [comment]
Thanks for the info. I think VS IntelliSense is just going crazy? Is there any way to fix it?

**Comment by giordi91** [comment]
Not sure, I am not involved in the project but it was working with 9.8.5 version. Might be best to wait for someone from the project.

**Comment by Groovounet** [comment]
My guess is that you are enabling VC C++ language extensions and using /W4 warnings. However, language extensions are W4 warnings so I would suggest to use one or the other.

Thanks

**Comment by suleyth** [comment]
If you actually read my post you would have seen that I tried a blank project, which means I didn't turn on or off anything. I just looked it up and the default project warning setting is /W3.

**Comment by giordi91** [comment]
@Groovounet @suleyth 
I think language extensions might be enabled by default. I will go and investigate. 
Would be good to keep the issue open until that is verified.

**Comment by suleyth** [comment]
Checked, extensions are indeed enabled by default, however it shouldn't cause any issue since it's also /W3 right?

**Comment by ncook-vero** [comment]
Visual Studio 2019 (vc142) .. ?
