### ISSUE TITLE
Documentation reports 'angle expressed in degrees' instead of 'radians'

### ISSUE THREAD

**Issue by MassimoCastrioto** [g-truc/glm#912]
At this link:
https://glm.g-truc.net/0.9.4/api/a00206.html#ga9a123708926335a4c097eee1157d4791

All the rotation function report needing an angle in degrees, while I'm pretty sure they work with
radians.

**Comment by Groovounet** [comment]
This error has been fixed on newer version of the documentation.

Thanks for reporting,
Christophe
