### ISSUE TITLE
GLM_HAS_CXX11_STL broken on Clang with Linux

### ISSUE THREAD

**Issue by muusbolla** [g-truc/glm#926]
GLM_HAS_CXX11_STL does not work on Linux with clang. It sees that the compiler is clang, then goes inside of the elif and tests for _LIBCPP_VERSION and _MSC_VER which are not defined, then exits. This happens at line 145-147 of setup.hpp.

_LIBCPP_VERSION is not defined by clang. It is only defined when including libc++ on certain platforms so it shouldn't be checked inside of the
#elif GLM_COMPILER & GLM_COMPILER_CLANG
block. I'm not sure how this block works exactly on Windows, but on my build with -std=c++17, __cplusplus is properly defined, so just testing GLM_LANG & GLM_LANG_CXX11_FLAG is good enough. I ripped out the whole windows specific bit in my setup.hpp line 145 (version 0.9.9.5-1 Manjaro Linux AUR) and just have the following:

```
#elif GLM_LANG & GLM_LANG_CXX11_FLAG || defined(GLM_LANG_STL11_FORCED)
#	define GLM_HAS_CXX11_STL 1
```

**Comment by Groovounet** [comment]
This issue should be fixed in master branch for GLM 0.9.9.6 release.

Thanks for reporting,
Christophe
