### ISSUE TITLE
Error When Using Aligned Gentypes Despite Setting GLM_FORCE_ALIGNED_GENTYPES

### ISSUE THREAD

**Issue by KTRosenberg** [g-truc/glm#930]
I receive the following error from the preprocessor despite having defined GLM_FORCE_ALIGNED_GENTYPES:

```
/usr/local/include/glm/gtc/type_aligned.hpp:16:3: error: "GLM: Aligned gentypes require to enable C++ language extensions. Define GLM_FORCE_ALIGNED_GENTYPES before including GLM headers to
      use aligned types."
#       error "GLM: Aligned gentypes require to enable C++ language extensions. Define GLM_FORCE_ALIGNED_GENTYPES before including GLM headers to use aligned types."
```

Looking into the file, `GLM_CONFIG_ALIGNED_GENTYPES == GLM_DISABLE` causes the error, so setting the force aligned gentypes define doesn't have anything to do with this. 

By setting `GLM_FORCE_INTRINSICS`, the error disappears. Why is this the case? Is this a bug?

I am using MacOS 10.13.6 and clang 7.0 installed via homebrew. I did not have the issue with previous versions of glm.

**Comment by christophe-lunarg** [comment]
This issue is obsolete as the error message doesn't exist anymore.

Thanks for reporting.
