### ISSUE TITLE
Functors Causing Build Failure in (OptiX-Flavored) CUDA

### ISSUE THREAD

**Issue by geometrian** [g-truc/glm#956]
Getting a build failure on current NVIDIA driver 436.30 (it's worth noting that this error did not occur on the previous driver):

> Error: Taking the address of functions is illegal because indirect function calls are illegal. Address of function _ZN3glm3absIfEET_S1_ is taken and used in function _ZN3glm6detail18compute_abs_vectorILy3EfLNS_9qualifierE0ELb0EE4callERKNS_3vecILy3EfLS2_0EEE ([path]/glm/detail/func_common.inl:76:11)

That is, a function pointer for absolute value is being used (by `detail::functor1`). Offhand, it looks like several other functions would suffer from the same problem.

**Comment by christophe-lunarg** [comment]
Only closing because it's a very old issue and I hope the issue resolved itself.

Thanks!
