### ISSUE TITLE
MSVC warning

### ISSUE THREAD

**Issue by seanmiddleditch** [g-truc/glm#958]
Builds with newer versions of glm using `add_subdirectory` from a parent project cause this warning:

`cl : Command line warning D9025: overriding '/W3' with '/W4'`

It's generally very bad form in CMake to blanket set flags like `/W4` in libraries (same applies to `-Wall` or whatnot on gcc/clang).

Better practice is to use a CMake option like `GLM_PEDANTIC` or something to control whether these are set for your own local builds or CI purposes, assuming you _really_ need these in the `CMakeLists.txt` itself (and not your local `CMakeSettings.json` or CI build scripts).

**Comment by Groovounet** [comment]
I would suggest to submit a PR if you want this issue to be resolve. I have no idea how to implement your suggestion.

Thanks,
Christophe
