### ISSUE TITLE
Looking for a CMake install/uninstall script maintainer

### ISSUE THREAD

**Issue by Groovounet** [g-truc/glm#961]
GLM 0.9.9.5 had a CMake install/uninstall script which was essentially working 5f352ec. That work was a user contribution however I don't have the appropriate knowledge or time to maintain it so I am unable to fix submitted bugs on review PR change.

The community would greatly appreciate if a someone could volunteer to restore this feature and maintain it.

Thanks,
Christophe

**Comment by handsomematt** [comment]
Was there an issue with how 5f352ec was working at all? It looks like a perfectly normal CMake configuration, nor does it really need maintaining, if it was broken in anyway one of the 100s of projects depending on it would submit a PR to fix it.

As far as I can see a maintainer would revert 5f352ec and then not need to do anything?

**Comment by Groovounet** [comment]
There are regularly issues and PRs submitted for CMake changes. 
As an example, the last one was this one: https://github.com/g-truc/glm/pull/935 which seems to be wait too disruptive to be accepted but maybe there were valid points, I have just no idea.

Also there is no documentation at all on how to use the install and uninstall features with these scripts and whatever all this is suposed to do so when a change is submitted I have no idea how to test it does break things. So a section in the documentation is required.

This also leads that there is no automated test for these features. Can it be tested? No idea but that would be a great plus.

Finally, I have no clue why anyone would use these scripts, so if someone wants to bother with this, I am fine with this but that won't be me.
