### ISSUE TITLE
0.9.9.6: no install target

### ISSUE THREAD

**Issue by kloczek** [g-truc/glm#962]
Full build log is in attachment

[glm.log](https://github.com/g-truc/glm/files/3724486/glm.log)

**Comment by kloczek** [comment]
0.9.9.6 is broken now :/
Any plans to fix this and make new release soon?

**Comment by Groovounet** [comment]
Any one to review this PR (https://github.com/g-truc/glm/pull/968) to resolve this issue ?

**Comment by MarkVabulas** [comment]
Removing the CMake install scripts (as seen in the changelog as deprecated) completely removes the possibility to use this as an ExternalProject in CMake without terrible hacks.

**Comment by Groovounet** [comment]
Feel free to review this PR to get it back https://github.com/g-truc/glm/pull/968

Thanks

**Comment by mmallet-youilabs** [comment]
#968 was closed in favour of #966 which unfortunately does not provide an `install` target.

**Comment by christophe-lunarg** [comment]
This is resolved on master branch as far as I understand such things.

**Comment by kloczek** [comment]
Any chance tto release new version? 🤔
