### ISSUE TITLE
glm::equal(val1, val2, int ULPs) gives the wrong answer

### ISSUE THREAD

**Issue by petersteneteg** [g-truc/glm#965]
This test
https://github.com/g-truc/glm/blob/ea678faff9340ae4a79f50f2edd947141405e128/glm/ext/scalar_relational.inl#L27-L31

will return true for any two number of different sign but with equal magnitude.

the test on line 30 should be `return x==y;` 

Example
https://godbolt.org/z/iR8unh

**Comment by Groovounet** [comment]
This issue should be fixed in master branch.

Thanks for contributing,
Christophe

**Comment by petersteneteg** [comment]
Should not -0.0f be equal to 0.0f?

**Comment by petersteneteg** [comment]
Btw this code is also in vector_relational.inl

**Comment by petersteneteg** [comment]
@Groovounet see above

**Comment by Groovounet** [comment]
Do you have an idea how to implement this correctly?

**Comment by petersteneteg** [comment]
This is definitely not in my expertise, but looking at the article referenced from
https://github.com/g-truc/glm/blob/master/glm/detail/type_float.hpp

https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

I would guess something similar to this...

```
    // Different signs means they do not match.
    if (uA.Negative() != uB.Negative())
    {
        // Check for equality to make sure +0==-0
        if (A == B)
            return true;
        return false;
    }
```
