### ISSUE TITLE
if constexpr tied to SIMD BIT

### ISSUE THREAD

**Issue by p-groarke** [g-truc/glm#967]
Using glm 0.9.9.5

In setup.hpp, line ~278, `GLM_HAS_CONSTEXPR` is disabled when compiling with `GLM_ARCH_SIMD_BIT`.

This makes no sense, as `GLM_HAS_CONSTEXPR` is an independent check to see if the compiler supports `constexpr` and `if constexpr`. These are independent features from SIMD.

It creates warnings at, for example, matrix_clip_space.inl, line 326, `GLM_IF_CONSTEXPR(GLM_CONFIG_CLIP_CONTROL == GLM_CLIP_CONTROL_LH_ZO)`. Since this is a `if constexpr` check and my compiler supports the feature.

```
matrix_clip_space.inl(326,1): error C2220:  warning treated as error - no 'object' file generated
matrix_clip_space.inl(326,1): warning C4127:  conditional expression is constant
matrix_clip_space.inl(326,1): message :  consider using 'if constexpr' statement instead
```
The compiler is right. Use `if constexpr` there.

Instead of disabling `constexpr` and `if constexpr` for everything when using SIMD, simply don't mark SIMD functions as `constexpr`. Done. Or, mark them as `constexpr`, since it doesn't matter as a `constexpr` function can be both compile time or runtime, and that evaluation depends on the caller context.

Plus, there is no good reason not to use an `if constexpr` inside a SIMD function, to enable/disable things at compile time. Both work hand-in-hand.

**Comment by Groovounet** [comment]
This is because compiler SIMD intrinsics don't support constexpr. If this has been fixed by compilers, I'll need to know the version of the compilers.

Thanks for reporting,
Christophe

**Comment by p-groarke** [comment]
What do you mean by intrinsics don't support `constexpr` exactly? Can you write a snippet to show the problem?

**Comment by p-groarke** [comment]
@Groovounet 
```
#include <array>
#include <intrin.h>

// Currently, your SIMD macros is a HUGE performance pessimization, for all
// functions that don't use simd.

#define USE_SIMD

// Constexpr is still useful, even if you are using SIMD. Don't disable it for
// all your library.
constexpr bool do_simd = true;
constexpr float my_val = 42.f;

// Simplistic example. Rethink your macros to make SIMD independent from
// constexpr compiler capabilities.
#if defined(USE_SIMD)
void my_func(std::array<float, 4>& arr) {
	// You can is if constexpr inside the simd func no problem
	if constexpr (do_simd) {
		__m128 v = _mm_set_ps(my_val, -my_val, my_val, -my_val);
		_mm_store_ps(arr.data(), v);
	}
}
#else
constexpr void my_func(std::array<float, 4>& arr) {
	arr = { my_val, -my_val, my_val, -my_val };
}
#endif

int main(int, char**) {

	alignas(16) std::array<float, 4> floats;

	my_func(floats);

	for (float f : floats) {
		printf("%f, ", f);
	}
	printf("\n");

	return 0;
}
```

**Comment by p-groarke** [comment]
For functions that return a value, mark them `constexpr` if you dont use simd, not `constexpr` if you do. Then, when the user tries to do this, it won't compile.
```c++
constexpr glm::vec3 = some_func(); // doesn't compile if some_func is SIMD
```
And now its up to the user to decide whether to disable SIMD and use `constexpr`, or to keep SIMD and not use constexpr.
