### ISSUE TITLE
glm::fma can use the std::fma implementation

### ISSUE THREAD

**Issue by TheJhonny007** [g-truc/glm#969]
Currently glm::fma implementation just returns `a * b + c`, which defeats the purpose of fma.
It should instead use the std::fma function, which invokes an optimized machine instruction if available. This gives higher precision in this calculation, which is the whole reason why fma exists at all.

**Comment by Groovounet** [comment]
This issue is resolved in master branch for GLM 0.9.9.7 release.

Thanks for reporting
