### ISSUE TITLE
Both rotate_vector.hpp and tranform.hpp include glm.hpp

### ISSUE THREAD

**Issue by alexfrasson** [g-truc/glm#970]
Given how glm can negatively impact compile time, I think it is paramount that all headers include only the strictly necessary. In the given example, it can not possibly be that both headers require the entire library in order for them to work.

Could this please be addressed in a future release?

**Comment by Groovounet** [comment]
What version of GLM are you using? I don't believe that on master branch it's the case.

Thanks,
Christophe
