### ISSUE TITLE
Integer matrix multiplication doesn't yield ivecN

### ISSUE THREAD

**Issue by r0mai** [g-truc/glm#977]
I'm using glm-0.9.9.6.

Consider the following code:

```cpp
#include <glm/glm.hpp>
#include <glm/gtc/matrix_integer.hpp>

void test_int() {
    glm::imat2 m{1};
    glm::ivec2 v0;

    auto v1 = m * v0;
    
    glm::min(v0, v1); // <-- doesn't compile, because v0 and v1 have different types
}
```

The `glm::min` call fails, because the last template parameter (`qualifier Q`) is different for `v0` and `v1`. `ivec2` and `imat2` uses different qualifiers by default and after the `mat2 * ivec2` multiplication `v1` inherits the qualifier value from `m`.

I found this behavior surprising and it's probably unintentional, as qualifiers don't really affect anything for integer arithmetic (I think).

An relatively easy workaround is to replace `auto` with an explicit `glm::ivec2`. 

The same code works with float or double vectors/matrices.

Demonstration: https://godbolt.org/z/njpKP7

**Comment by christophe-lunarg** [comment]
It looks like this issue was resolved with GLM 0.9.9.8 released so it was resolved a long time ago...

Thanks for reporting!
