### ISSUE TITLE
What happened to hvec4?

### ISSUE THREAD

**Issue by crazydef** [g-truc/glm#979]
Hi,

I'm just trying to update the version of GLM that this code I'm working with is using.

It seems support for half types has gone AWOL in newer versions of GLM.  Is this really the case, or have they been renamed and moved somewhere else?

**Comment by Groovounet** [comment]
Hi,

Yes it's gone. It was extremely slow and a high maintenance cost. 
I would recommend to use  `unpackHalf2x16` and `packHalf2x16` from core functions.
You can also use extension functions from GTC_packing https://glm.g-truc.net/0.9.9/api/a00298.html

**Comment by crazydef** [comment]
ok, thanks for clarifying.
