### ISSUE TITLE
Unnecessary warnings from matrix_clip_space.inl

### ISSUE THREAD

**Issue by crazydef** [g-truc/glm#980]
The `if` statements between lines 70 and 115(ish) in the aforementioned file generate a ton of "conditional expression is constant" warnings.

These should probably be preprocessor control statements.  (#if, #elif, #else, etc.)

**Comment by Groovounet** [comment]
This issue is fixed on master branch for GLM 0.9.9.7 release.

Thanks for reporting,
Christophe

**Comment by crazydef** [comment]
You even found some I missed.  Nice.  :)
