### ISSUE TITLE
glm conflicts with AVFoundation: Call to 'simd_char' is ambiguous (iOS + XCode)

### ISSUE THREAD

**Issue by gh123man** [g-truc/glm#981]
I am building an iOS game that includes glm. I also use AVFoundation APIs to play videos in some screens of the app. Including glm in the header search paths causes many of the following error if I attempt to import AVFoundation.
```
/Applications/Xcode_10.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/simd/conversion.h:1069:73: Call to 'simd_char' is ambiguous
```

I assume this is because `AVfoundation` pulls in something that defines `simd_char` and glm pulls in a different version - however I cannot figure out where this actually happens. 

Steps to repro this are:

1. create iOS app project in XCode
2. include glm in header search paths
3. import AVFoundation anywhere in the project
4. I have created a sample project that reproduces this issue [here](https://github.com/gh123man/GLM-conflicts-with-AVFoundation).

Is there a way to disable/fix the simd includes in GLM or disable it? I suppose the only other solution is to compile GLM into a framework and static link it, but that would also be a cross architecture maintenance nightmare.

**Comment by Groovounet** [comment]
You can disable it using `GLM_FORCE_PURE`

I couldn't find any reference to `simd_char` in GLM master branch code...
