### ISSUE TITLE
Update license date

### ISSUE THREAD

**Issue by Zuzu-Typ** [g-truc/glm#984]
Hi Christophe,

I think you should update your [license information](https://github.com/g-truc/glm/blob/master/copying.txt), which currently only gives copyright from 2005 to 2014.

I would recommend you simply remove the "to" part and simply state 
`Copyright (c) 2005 G-Truc Creation`
which would imply since 2005.

**Comment by Groovounet** [comment]
Hi,

This issue is fixed in master branch for GLM 0.9.9.7 release.

Thanks!
