### ISSUE TITLE
License statement grammer issue.

### ISSUE THREAD

**Issue by VanDiSarzio** [g-truc/glm#990]
Changing the license statement in the _readme.md_ (from an _and_ to and _or_) seems to have left the sentence grammatically incorrect.

_The source code and the documentation are licensed under both the [Happy Bunny License (Modified MIT) or the MIT License](manual.md#section0)._

I would suggest replacing the word _both_ with _either_, which gives:

_The source code and the documentation are licensed under either the [Happy Bunny License (Modified MIT) or the MIT License](manual.md#section0)._

Whilst a seemingly trivial issue, anything pertaining to legal matters should really be as correct and crystal clear as possible.

**Comment by christophe-lunarg** [comment]
This was resolved
